### ISSUE TITLE
build on Windows

### ISSUE THREAD

**Issue by damian123** [msgpack/msgpack-c#10]
Moved from jira

March 17 - 7:00 PM

Damian commented on MSGPACK-84 (msgpack_vc.postbuild.bat fails with The system cannot find the file specified.) saying:
As a quick workaround I took the header files from my fedora build.

March 17 - 12:00 PM

Damian commented on MSGPACK-84 (msgpack_vc.postbuild.bat fails with The system cannot find the file specified.) saying:
Now I have a problem with zone.hpp which is not found. I can find a file called zone.hpp.erb which I also suppose needs the autotools from Linux?

 Damian commented on MSGPACK-84 (msgpack_vc.postbuild.bat fails with The system cannot find the file specified.) saying:
So now my new .bat file looks like this:

IF NOT EXIST include MKDIR include
IF NOT EXIST include\msgpack MKDIR include\msgpack
IF NOT EXIST include\msgpack\type MKDIR include\msgpack\type
IF NOT EXIST include\msgpack\type\tr1 MKDIR include\msgpack\type\tr1
copy pack_define.h include\msgpack\
copy pack_template.h include\msgpack\
copy unpack_define.h include\msgpack\
copy unpack_template.h include\msgpack\
copy sysdep.h include\msgpack\
copy src\msgpack.h include\
copy src\msgpack\sbuffer.h include\msgpack\
copy src\msgpack\version.h include\msgpack\
copy src\msgpack\vrefbuffer.h include\msgpack\
copy src\msgpack\zbuffer.h include\msgpack\
copy src\msgpack\pack.h include\msgpack\
copy src\msgpack\unpack.h include\msgpack\
copy src\msgpack\object.h include\msgpack\
copy src\msgpack\zone.h include\msgpack\
copy src\msgpack.hpp include\
copy src\msgpack\sbuffer.hpp include\msgpack\
copy src\msgpack\vrefbuffer.hpp include\msgpack\
copy src\msgpack\zbuffer.hpp include\msgpack\
copy src\msgpack\pack.hpp include\msgpack\
copy src\msgpack\unpack.hpp include\msgpack\
copy src\msgpack\object.hpp include\msgpack\
copy src\msgpack\zone.hpp include\msgpack\
copy src\msgpack\type.hpp include\msgpack\
copy src\msgpack\type\bool.hpp include\msgpack\type\
copy src\msgpack\type\deque.hpp include\msgpack\type\
copy src\msgpack\type\fixint.hpp include\msgpack\type\
copy src\msgpack\type\float.hpp include\msgpack\type\
copy src\msgpack\type\int.hpp include\msgpack\type\
copy src\msgpack\type\list.hpp include\msgpack\type\
copy src\msgpack\type\map.hpp include\msgpack\type\
copy src\msgpack\type\nil.hpp include\msgpack\type\
copy src\msgpack\type\pair.hpp include\msgpack\type\
copy src\msgpack\type\raw.hpp include\msgpack\type\
copy src\msgpack\type\set.hpp include\msgpack\type\
copy src\msgpack\type\string.hpp include\msgpack\type\
copy src\msgpack\type\vector.hpp include\msgpack\type\
copy src\msgpack\type\tuple.hpp include\msgpack\type\
copy src\msgpack\type\define.hpp include\msgpack\type\
copy src\msgpack\type\tr1\unordered_map.hpp include\msgpack\type\tr1\
copy src\msgpack\type\tr1\unordered_set.hpp include\msgpack\type\tr1\

Damian commented on MSGPACK-84 (msgpack_vc.postbuild.bat fails with The system cannot find the file specified.) saying:
Some of the header files are in d:\dev\GitHub\msgpack-c so that is easy to solve, by copying from there instead.

But version.h.in needs to run though configure which I don't have on Windows. I can manual create the version.h file from version.h.in

March 17 - 11:00 AM

Damian created MSGPACK-84 (msgpack_vc.postbuild.bat fails with The system cannot find the file specified.)

**Comment by redboltz** [comment]
Now msgpack-c supports windows(MSVC) build using cmake. You can use it. See https://github.com/msgpack/msgpack-c#gui-on-windows
