### ISSUE TITLE
Serialization of 64-bit floats broken on iOS ARM 32-bit

### ISSUE THREAD

**Issue by darknoon** [msgpack/msgpack-c#101]
This has to do with the `__ARM_EABI__` conditional in unpack_template.h / pack_template.h.

If I set a build setting `__ARM_EABI__ = 1`, then it works, but this kinda sucks. Is there another way to conditionalize this hack for that platform without messing up the build for iOS?

**Comment by rggjan** [comment]
Maybe a different endianness check like this one would be more robust:
http://stackoverflow.com/a/12792301/369009

Alternatively, a patch along these lines:
https://code.google.com/p/v8/issues/attachmentText?id=1312&aid=13120010000&name=v8-ios.patch&token=704fa2b9305af97f5c33d2aaad55fb30

Might also work:
-#if defined(__arm__) && !defined(__ARM_EABI__)
+#if defined(__arm__) && !defined(__APPLE__) && !defined(__ARM_EABI__)

**Comment by redboltz** [comment]
This issue has been fixed by #270
