### ISSUE TITLE
At what point is it safe to delete the source object?

### ISSUE THREAD

**Issue by dlandtaa** [msgpack/msgpack-c#1014]
What if I create an object using `new`, create a `msgpack::buffer` for that object, then delete the object? Is that `msgpack::buffer` still valid? The code below works but I'm not sure if that's just random chance with old data still left on the heap.

```
class C
{
public:
    C(int a, int b, int c): a(a), b(b), c(c) {}
    MSGPACK_DEFINE_MAP(a, b, c);
    int a;
    int b;
    int c;
};

int main()
{
    C* c1 = new C(1, 2, 3);
    msgpack::sbuffer buff;
    msgpack::pack(buff, *c1);
    delete c1;
    
    // is this safe now that I have deleted c?
    msgpack::object_handle handle = msgpack::unpack(buff.data(), buff.size());
    msgpack::object obj = handle.get();

    C c2(0, 0, 0);
    obj.convert(c2);

    // prints 123
    cout << c2.a << c2.b << c2.c << endl;

    return 0;
}

```

**Comment by redboltz** [comment]
Yes, it is safe.

`buff` allocate the memory internally. `buff` stores msgpack formatted string (bytes). It is converted from `*c1` and it doesn't have a reference of `*c1`.

**Comment by dlandtaa** [comment]
Thank you!
