### ISSUE TITLE
msgpack-c++ creates an interface library instead of a shared library

### ISSUE THREAD

**Issue by aliawan01** [msgpack/msgpack-c#1026]
I was trying to build a shared library of msgpack-c (on the cpp_master branch) so that I could compile [jubatus-mspack-rpc](https://github.com/jubatus/jubatus-msgpack-rpc/tree/master/cpp), however after taking a quick look at the cmakelists.txt I could see this line `ADD_LIBRARY (msgpackc-cxx INTERFACE)` which seemed to be creating a interface library instead of a shared library which was causing problems as from what I found online it means that this libary can only be used with cmake via find_package, however the jubatus-mspack-rpc project uses gnu autotools to build the project and this was causing me problems as cmake was not creating any physical shared library I could use (I am also a complete beginner when it comes to using cmake so I may have misunderstood how interface libraries work, if so please correct me and I would appreciate it if you could explain how I could create a shared library from the cpp_master branch.

**Comment by redboltz** [comment]
I'm not 100% sure what are you asking but I try to answer.
msgpack-c(C++) is a header-only library so no shared librariy is generated.
Simply add include path to your project.
See https://github.com/msgpack/msgpack-c/tree/cpp_master#dependency

**Comment by aliawan01** [comment]
I'm sorry if I didn't explain the problem properly, I am also pretty new to cmake. The problem is that I need a msgpack shared library to be able to build this project: [jubatus-mspack-rpc](https://github.com/jubatus/jubatus-msgpack-rpc/tree/master/cpp) because whenever I run ./configure in that project it checks for a msgpack library and the include files.

**Comment by redboltz** [comment]
There is no shared library msgpack-c (C++). I guess that [jubatus-mspack-rpc](https://github.com/jubatus/jubatus-msgpack-rpc/tree/master/cpp) b need to be updated.

**Comment by aliawan01** [comment]
I tried using the c version of msgpack-c which builds the library but the include files which are generated seem to be incorrect, do you think that there is any other way I could fix this?

**Comment by redboltz** [comment]
I guess that [jubatus-mspack-rpc](https://github.com/jubatus/jubatus-msgpack-rpc/tree/master/cpp) is no longer maintained.
See https://github.com/jubatus/jubatus-msgpack-rpc/commits/master/cpp

If you want to use rpc using msgpack-c, you need to serach other one or create it.

**Comment by redboltz** [comment]
Or use very old msgpack-c https://github.com/msgpack/msgpack-c/releases?page=3
FYI: very old msgpack-c is also no longer maintained;)

**Comment by aliawan01** [comment]
Thanks, I'll give they a try!
