### ISSUE TITLE
Questions about internal allocation of the CPP library

### ISSUE THREAD

**Issue by freak82** [msgpack/msgpack-c#1035]
Hi there,

I intend to use the `msgpack` library in a project were every heap allocation goes through custom allocator facilities. 
As far as I checked the Cpp library provides interfaces for pack/unpack which allow the users of the library to use whatever allocation strategies they want. 
- For the packing part if the user provides it's own [buffer](https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_packer#user-content-buffer) the library will use it and won't do any memory allocations internally. Is my understanding correct here?
- For the unpacking part the user can use the [visitor functionality](https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_visitor) and then the library won't do any additional allocations internally. I'll just parse the input and call the visitor member functions. Is my understanding correct here?

Thanks,
Pavel.

**Comment by redboltz** [comment]
> * For the packing part if the user provides it's own [buffer](https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_packer#user-content-buffer) the library will use it and won't do any memory allocations internally. Is my understanding correct here?

Yes.

> * For the unpacking part the user can use the [visitor functionality](https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_visitor) and then the library won't do any additional allocations internally. I'll just parse the input and call the visitor member functions. Is my understanding correct here?

Almost yes, but one exception.
parse() function uses class context.

See the following execution sequence:

https://github.com/msgpack/msgpack-c/blob/fb64ea0b68cda185f1e45b87713ba9cd7be3e394/include/msgpack/v2/parse.hpp#L1014-L1015
https://github.com/msgpack/msgpack-c/blob/fb64ea0b68cda185f1e45b87713ba9cd7be3e394/include/msgpack/v2/parse.hpp#L1008-L1010
https://github.com/msgpack/msgpack-c/blob/fb64ea0b68cda185f1e45b87713ba9cd7be3e394/include/msgpack/v2/parse.hpp#L1032-L1042
https://github.com/msgpack/msgpack-c/blob/fb64ea0b68cda185f1e45b87713ba9cd7be3e394/include/msgpack/v2/parse.hpp#L1022-L1026

The class context has `m_stack`.
MessagePack is recursive data format. Roughly speaking, `m_stack` store the level of recursion.
`m_stack` is `std::vector`.

https://github.com/msgpack/msgpack-c/blob/fb64ea0b68cda185f1e45b87713ba9cd7be3e394/include/msgpack/v2/parse.hpp#L35-L36
https://github.com/msgpack/msgpack-c/blob/fb64ea0b68cda185f1e45b87713ba9cd7be3e394/include/msgpack/v2/parse.hpp#L223
https://github.com/msgpack/msgpack-c/blob/fb64ea0b68cda185f1e45b87713ba9cd7be3e394/include/msgpack/v2/parse.hpp#L152
https://github.com/msgpack/msgpack-c/blob/fb64ea0b68cda185f1e45b87713ba9cd7be3e394/include/msgpack/v2/parse.hpp#L214

The vector doesn't have allocator template argument, so default allocator is used.
You need to care about that. For example, override default new.

**Comment by freak82** [comment]
I see. Thanks for the explanation. Will try your suggestion.
