### ISSUE TITLE
error C2011: "iovec": "struct" type redefinition

### ISSUE THREAD

**Issue by PhilippPaetzold** [msgpack/msgpack-c#1059]
**Describe the bug**

When compiling under Windows 11 22H2 (Build 22621.1413) using CMake 3.25.1, VS2022 and Vcpkg version of msgpack 3.3.0 (msgpack[core]:x64-windows -> 3.3.0)

I get the following compilation error:

```
D:\_repos\sw-dev\cmake-build-debug\vcpkg_installed\x64-windows\include\msgpack\v1\vrefbuffer.hpp(28): error C2011: "iovec": "struct" type redefinition
```

I can fix the issue, by modifying vrefbuffer.hpp(28)  and moving  struct iovec into the msgpack-namespace:
```cpp
#if defined(unix) || defined(__unix) || defined(__APPLE__) || defined(__OpenBSD__)
#include <sys/uio.h>
#endif
namespace msgpack {
     struct iovec
    {
        void* iov_base;
        size_t iov_len;
    };
...
```

I think its related to #952.

**Comment by redboltz** [comment]
It seems that iovec definition has already been in namespace msgpack on HEAD.
If you still have the problem on the HEAD, please post a PR.
