### ISSUE TITLE
Bitfield support with Msgpack

### ISSUE THREAD

**Issue by DakshKK** [msgpack/msgpack-c#1062]
I already have a predefined system with more than 1000 `struct`s defined. Initially there was no transmission, only data storage and conversion, hence serialization was never implemented.

I now have a need to implement serialization since data is going to be transmitted, and shared across a Python-C/C++ interop system.

Msgpack seems to provide the most hassle-free header-only setup for this, but I am unable to implement serialization due to bitfield `struct`s.

Is there a way to go around this, and implement serialization, in a method unlike as mentioned in #700 .

**Comment by redboltz** [comment]
No, [non-intrusive-approach](https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#non-intrusive-approach) the way to adapt bitfield.
