### ISSUE TITLE
Can't build because cmake option MSGPACK_BUILD_TESTS is now on by default

### ISSUE THREAD

**Issue by T5100** [msgpack/msgpack-c#1066]
This line:
OPTION (MSGPACK_BUILD_TESTS "Build msgpack tests." ON)
from this commit
https://github.com/msgpack/msgpack-c/commit/2f543923d23faeb41e53b2624a1d053d3c9424db

caused this error message

CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR

Because I don't have google test.

**Expected behavior**
OPTION (MSGPACK_BUILD_TESTS "Build msgpack tests." OFF)

**Comment by redboltz** [comment]
Thank you for reporting the issue.
I think that the expected behavior you mantioned is right. Could you post the PR to fix it ?

**Comment by redboltz** [comment]
Fixed by #1069
