### ISSUE TITLE
Detect msgpack-cxx <= 6.0.0 with cmake

### ISSUE THREAD

**Issue by aberaud** [msgpack/msgpack-c#1079]
Hi,
What is the recommended way to detect and use msgpack-cxx with CMake that would work with msgpack 6.0.0 and also be backward-compatible with older versions ?

Many thanks

**Comment by uyha** [comment]
that depends on how you install msgpack-cxx, if you clone this project and use cmake to install it, then using `find_package` should work, similarly for Conan.

**Comment by aberaud** [comment]
Thanks.

I currently use:
```cmake
find_package(msgpack REQUIRED NAMES msgpack msgpack-cxx)
target_link_libraries(mylib PUBLIC msgpack-cxx)
```
However this only works with the latest version 6.0.0.

What's the recommended way to include and link msgpack **that would be backward compatible with older msgpack versions** ? Thanks.

**Comment by uyha** [comment]
the problem is this library makes a breaking change in version v6.0.0, so for versions earlier than that, you’ll have to use `msgpackc-cxx`. In you CMake script, you can do something like

```cmake
if(MSGPACK_VERSION VERSION_LESS 6.0.0)
  find_package(msgpack REQUIRED NAMES msgpackc msgpackc-cxx)
  add_library(msgpack-cxx ALIAS msgpackc-cxx)
else()
  find_package(msgpack REQUIRED NAMES msgpack msgpack-cxx)
endif()
```

Then you can link your targets with `msgpack-cxx` regardless of the version.

**Comment by uyha** [comment]
or if you just want to detect the whether the library is installed and use it, the following snippet may be useful.

```cmake
find_package(msgpackc-cxx)
if(msgpackc-cxx_FOUND)
  add_library(msgpack-cxx ALIAS msgpackc-cxx)
else()
  find_package(msgpack-cxx REQUIRED)
endif()
```

**Comment by aberaud** [comment]
Many thanks :)

Maybe this should be documented in the README because older versions will be around for a while.

**Comment by uyha** [comment]
I’ll create a PR when i have time

**Comment by aberaud** [comment]
@uyha It seems that older versions of msgpack-c++ (like version 3.0 in Ubuntu 20.04 and version 3.3 in Ubuntu 22.04) use 'msgpack' instead of  'msgpack-cxx' or 'msgpackc-cxx' ?

So there would be a need for a 3-level checks ?

Something like:

```cmake
find_package(msgpackc-cxx QUIET CONFIG)
if(msgpackc-cxx_FOUND)
  add_library(msgpack-cxx ALIAS msgpackc-cxx)
else()
  find_package(msgpack-cxx CONFIG)
  if(NOT msgpack-cxx_FOUND)
    find_package(msgpack CONFIG REQUIRED)
    add_library(msgpack-cxx ALIAS msgpack)
  endif()
endif()
```

Does this makes sense ?

**Comment by uyha** [comment]
looks fine for me

**Comment by aberaud** [comment]
We ended up using:

```cmake
find_package(msgpackc-cxx QUIET CONFIG NAMES msgpackc-cxx msgpack)
if(msgpackc-cxx_FOUND)
  add_library(msgpack-cxx ALIAS msgpackc-cxx)
else()
  find_package(msgpack-cxx CONFIG REQUIRED)
endif()
```

**Comment by redboltz** [comment]
I added the document about that in Wiki.
https://github.com/msgpack/msgpack-c/wiki/Q%26A#how-to-support-both-msgpack-c-c-version-5x-and-6x-

User can find the information using search box like this:
https://github.com/search?q=repo%3Amsgpack%2Fmsgpack-c+cmake&type=wikis
