### ISSUE TITLE
The dynamic library generated has wrong version

### ISSUE THREAD

**Issue by joelguittet** [msgpack/msgpack-c#1080]
**Describe the bug**
The current version of msgpack-c is 6.0.0. So I expect the libmsgpack-c.so file be libmsgpack-c.so.6.0.0. Actually it is libmsgpack-c.so.2.0.0 because the version of the library is hardcoded here: https://github.com/msgpack/msgpack-c/blob/c_master/CMakeLists.txt#L128

**To Reproduce**
Just build the project.

**Expected behavior**
Version of the library to be used to build the so file instead of hardcoding.

**Comment by redboltz** [comment]
so version and msgpack-c(C) version is different. When ABI updated, then so version is up.
