### ISSUE TITLE
missing sysdep.h, pack_template.h, predef.h and predef folder in msgpck-c

### ISSUE THREAD

**Issue by Luis550** [msgpack/msgpack-c#1084]
**Describe the bug**e the bug**
I have been working with msgpack -c 3.0.0 for 6 or 5 years. I have just downloaded msgpack-c 6.0.0 but I noticed that some include files are missing.  I could not find then in 4.0.0 or 5.0.0 either

**Comment by redboltz** [comment]
It is not a bug.
You need to install msgpack-c.

See https://github.com/msgpack/msgpack-c/tree/c_master#usage

Those files are genereted by installing process using https://github.com/msgpack/msgpack-c/tree/c_master/cmake

I noticed that one reference to predef directory but it is never used ( it should be removed ).
https://github.com/msgpack/msgpack-c/blob/c_master/cmake/sysdep.h.in#L111

**Comment by Luis550** [comment]
Hello redboltz

I used cmake and It worked all fine.
I´m using msgpack-c inside a STM32 micro so I used an ubuntu to run cmake and then I´ve isntalled it in the microcontroller

Thanks!!
