### ISSUE TITLE
Question, when packing, are the values already supposed to be in big endian

### ISSUE THREAD

**Issue by timbo100** [msgpack/msgpack-c#1102]
I've navigated all the documentation and there are references to msgpack using big endian, even says so in the format, etc.
but what is unclear to me is when I call pack functions for multi-byte values, I'm I providing big-endian or can I provide little-endian and the functions convert for us?

**Comment by redboltz** [comment]
msgpack-c detects system's endian and converts endian if needed.

See:

https://github.com/msgpack/msgpack-c/blob/2c0040cef6e0cd9f871979bb6e6b57fa74de0d46/include/msgpack/v1/pack.hpp#L790

https://github.com/msgpack/msgpack-c/blob/2c0040cef6e0cd9f871979bb6e6b57fa74de0d46/include/msgpack/sysdep.hpp#L97

So basically user doesn't need to care about the endian.

Detail:

## Big Endian environment
C++ value --pack (no convert) --> msgpack format
msgpack format -- unpack(no convert) --> msgpack::object -- convert(no cconvert) --> C++ value

## Little Endian environment
C++ value --pack (convert to big endian) --> msgpack format
msgpack format -- unpack(convert to little endian) --> msgpack::object -- convert(no cconvert) --> C++ value

**Comment by timbo100** [comment]
@redboltz 

Thanks for answer my question and providing a very helpful response.
