### ISSUE TITLE
someting about msgpack::object.convert()

### ISSUE THREAD

**Issue by luanhaixin** [msgpack/msgpack-c#1115]
``` cpp
vector<int> onm ;
msgpack_object.convert( onm );
```

I wonder that the behavior of the method convert() is either copy the data from msgpack object in memory to my target data(onm) or directly access the msgpack object data using pointer or reference.

Because I want to manage memory and haven't seen a detailed discussion on the convert method in the wiki.

**Comment by redboltz** [comment]
At first, onm is empty vector. After you call convert, onm would have members corresponding to msgpack_objecft.
The values are copied.
