### ISSUE TITLE
Where can i find `msgpack` library??

### ISSUE THREAD

**Issue by woongdam** [msgpack/msgpack-c#1116]
Hello 
I'm a student in University
I'm interested in your project.
So. I want to try to build.

But, I can't find msgpack library.
Could you give me how to use this project.

I don't understand "link `msgpack` library to use MessagePack on your program." which you find QUICKSTART-CPP

Thank you.

**Comment by redboltz** [comment]
Thank you for reporting the issue.
C++ version of msgpack-c is a header only library. So you don't need to link libraries.

It seems that the following document should as follows:

Before:

> Include msgpack.hpp header and link msgpack library to use MessagePack on your program.

After:

> Include msgpack.hpp header to use MessagePack on your program.

I will fix the document.

**Comment by redboltz** [comment]
Fixed by #1117 .
If you have further questions about this issue, feel free to reopen the issue.
