### ISSUE TITLE
CMake <3.5 deprecation warning msgpack-c (cpp)

### ISSUE THREAD

**Issue by berhoeckner** [msgpack/msgpack-c#1132]
Hi,

we use a rather new CMake (3.29) and now we started seeing deprecation warnings about minimum require versions < 3.5.

i was wondering if https://github.com/msgpack/msgpack-c/pull/1097 is planed to be committed to the CPP branch as well?

**Comment by redboltz** [comment]
If you or someone create a PR for C++, I will review and merge it.

**Comment by redboltz** [comment]
Fixed by #1133
