### ISSUE TITLE
Init Helper for msgpack_obj 

### ISSUE THREAD

**Issue by Athishpranav2003** [msgpack/msgpack-c#1134]
For complex datatypes such as String, Map, Array and Bin since they have same structure it makes sense to have a common init function to make it easy for dev purposes.

**Comment by Athishpranav2003** [comment]
@redboltz What about the release cycle for the same?

**Comment by redboltz** [comment]
Released https://github.com/msgpack/msgpack-c/releases/tag/c-6.1.0
