### ISSUE TITLE
Allow using existing zone when unpacking

### ISSUE THREAD

**Issue by spatz** [msgpack/msgpack-c#184]
Currently every call to `msgpack::unpack()` allocates a new zone in a `std::unique_ptr`. Unless I've missed something, there is no way to use an existing zone for unpacking.
Can this functionality please be added? I think it would be simpler and more efficient as it will allow the user to avoid an unneeded allocation.

Thanks.

**Comment by redboltz** [comment]
Thank you for the proposal.

> Can this functionality please be added? I think it would be simpler and more efficient as it will allow the user to avoid an unneeded allocation.

I think that in some case it would more efficient. But it is pretty difficult to implement it simpler.

When msgpack::object that are allocated on the same zone have similar lifetime, it's efficient. But their lifetime is different very much, you need keeping zone until the last msgpack::object's lifetime is over.

See:
https://github.com/msgpack/msgpack-c/wiki/cpp_unpacker#memory-management

The lifetime of msgpack::object depends on application design. 

Let's consider how to implement the unpack API with zone. I found some issues as follows:

1. How to pass the existing zone to new unpack API?
   Move from somewhere? e.g.) previous msgpack::unpacked instance.
   When unpack error happens, the zone should move back to the original holder. How to do that?

2. For the consistency, should msgpack::unpacker have a API with existing zone? 

I think that it is worth having the unpack APIs with zone if there is a good way to implement it simple.

**Comment by spatz** [comment]
You are correct that it would be the user's responsibility to ensure that the zone passed to unpack() lives at least as long as the created objects.
I think that a new overload for unpack() should be added that gets a zone by reference, and the resulting unpacked object does not contain a zone (i.e. the unique_ptr is null). It should be documented that taking care of the zone lifetime is the user's responsibility. I don't know how simple that would be to implement.

**Comment by redboltz** [comment]
It seems that passing zone by reference is a good idea. I think that it is better the new API returns msgpack::object than msgpack::unpacked. Anyway, I will try implementing it.
