### ISSUE TITLE
How to use optional field in msgpack-c

### ISSUE THREAD

**Issue by sophyphilo** [msgpack/msgpack-c#187]
Use the @optional for adding new fields maintaing the compatibility when using msgpack-java (https://github.com/msgpack/msgpack-java/wiki/QuickStart), but I want to know how to use optional field when using msgpack-c.
Thanks!

**Comment by redboltz** [comment]
Here is an example that maintaing compatibility using msgpack-c way:

https://github.com/msgpack/msgpack-c/blob/master/example/cpp03/custom.cpp

**Comment by redboltz** [comment]
I will close the issue. If you have additional questions, please let me know.

**Comment by iyedb** [comment]
Hi,
The example shows the case of `new_class` adding a new field "at the end", but how to handle the case when I have a class with 3 fields say `a, b and c` and in the **new version of the class** I decide to remove `field b`. I did a test but it segfaulted. Is there a way to unpack a buffer created with the old version, to the new version of the class (without field b)?. 
Thanks and regards.

**Comment by redboltz** [comment]
Since version 1.2.0, MSGPACK_DEFINE_MAP is added. You can use it as follows:
http://melpon.org/wandbox/permlink/8Cek3K3fjp8kJgF0

Here is a document:
https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_adaptor#defining-custom-adaptors

**Comment by iyedb** [comment]
Thank you very much for the prompt answer. Great stuff. I am wondering if it has been or will be backported to 1.1.x 
Regards.

**Comment by redboltz** [comment]
There is no plan to backport it to 1.1.x.
Updating 1.1.0 to 1.2.0 is easy. See https://github.com/msgpack/msgpack-c/releases/tag/cpp-1.2.0
There are only two small breaking changes. I'd be glad if you update your msgpack to 1.2.0. C++ part of msgpack-c is a header only library. You don't need to install it. Of course you can install it.

**Comment by redboltz** [comment]
BTW, the example I posted is written in C++11. You can use MSGPACK_DEFINE_MAP in C++03.
http://melpon.org/wandbox/permlink/Klir1QcpanvglACN

**Comment by iyedb** [comment]
Great! Thank you very much.
