### ISSUE TITLE
Pack map or array

### ISSUE THREAD

**Issue by dawnlucky** [msgpack/msgpack-c#189]
Hi guy,

   Another question, when I pack map or array, I must set the size of pack_map/pack_array.
   But I do not know the size of it when I do the pack_map/pack_array, Do there have other ways?  

Best,
Mack

**Comment by redboltz** [comment]
Due to msgpack format https://github.com/msgpack/msgpack/blob/master/spec.md#formats-array , you need to set size first. 

When you don't know the size of them, you could use std::vector or std::map as a buffer. But I'm not sure about your usecase.

**Comment by dawnlucky** [comment]
Thank you, redboltz.
