### ISSUE TITLE
msgpack-c calls the double in msgpack_object_union illogically `dec`

### ISSUE THREAD

**Issue by ztane** [msgpack/msgpack-c#191]
which most probably refers to "decimal", which the doubles after all are not, as they are encoded in IEEE-754 binary.

Furthermore, since the documentation seems to be "read the source", I had to read the headers to find it out.

**Comment by redboltz** [comment]
@ztane, thank you for your comment.

> which most probably refers to "decimal", which the doubles after all are not, as they are encoded in IEEE-754 binary.

True. It is misleading. 

'dec' is corresponding to 'float format family':
https://github.com/msgpack/msgpack/blob/master/spec.md#float-format-family

It should have a different name. But it is already a part of public interface. It might break existing client codes. So I think that the next MAJOR version up is a good timing to change the name. 


> Furthermore, since the documentation seems to be "read the source", I had to read the headers to find it out.

I'm trying to improve the documentation. But it is under development.

Here is information about dec:

https://github.com/msgpack/msgpack-c/wiki/cpp_object#what-is-msgpackobject

Unfortunately it is in the picture. So it can't be hit as a search word.

By the way, I think that 'f64' is a good name. 'float' is reserved by the languace C/C++. 'f64' is the same mannar as 'i64' and 'u64'.

**Comment by nobu-k** [comment]
I discussed this with redboltz. Because we use union, we can add a new `f64` field while maintaining obsolete `dec` field. So, we can fix this issue without losing compatibility. redboltz is now preparing a pull request for it.

**Comment by redboltz** [comment]
I added a document on the wiki https://github.com/msgpack/msgpack-c/wiki/cpp_configure
