### ISSUE TITLE
Compilation warnings on MSVC

### ISSUE THREAD

**Issue by ibell** [msgpack/msgpack-c#226]
When I compile my package which uses msgpack using MSVC 2010 in 64-bit compilation, I get a handful of warnings like these:

```
c:\users\ian\slave\64bit_shared_library-windows\build\externals\msgpack-c\include\msgpack/unpack.hpp(630): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\ian\slave\64BIT_SHARED_LIBRARY-windows\build\build\CoolProp.vcxproj]
```

**Comment by redboltz** [comment]
Thank you for reporting the issue. I understand the problem. I don't have x64 MSVC environment now. But I will get it and will fix the issue.

**Comment by ibell** [comment]
Thanks
