### ISSUE TITLE
Packing int numbers should not produce uint results

### ISSUE THREAD

**Issue by thinxer** [msgpack/msgpack-c#247]
When packing an positive int number, say 1427252004348, it is packed into a uint number, based on the code for `pack_imp_int64`. The spec says:

> If an object can be represented in multiple possible output formats, serializers SHOULD use the format which represents the data in the smallest number of bytes.

However, I don't think uint should be used instead of int. Also, in this case, both int and uint encodes to the same number of bytes.

**Comment by thinxer** [comment]
https://github.com/msgpack/msgpack/issues/164 An older issue from the spec.

**Comment by redboltz** [comment]
Agreed. I am writing a PR to fix the issue.

**Comment by redboltz** [comment]
Here is the PR to solve the issue:
https://github.com/msgpack/msgpack-c/pull/250

**Comment by redboltz** [comment]
I've wrote #250. But now, I think the original implementation is better. So I think that #250 should be rejected. See https://github.com/msgpack/msgpack/issues/164#issuecomment-86368081

**Comment by redboltz** [comment]
I will close the issue if @thinxer won't add any comments.
My conclusion is that msgpack-c should always use uint for positive numbers.
https://github.com/msgpack/msgpack/issues/164#issuecomment-86368081

**Comment by redboltz** [comment]
FYI:
msgpack::packer has pack_fix_intXX and pack_fix_uintXX member functions to enforce the serialized type. See:
https://github.com/msgpack/msgpack-c/blob/cpp-1.0.0/include/msgpack/pack.hpp#L44
https://github.com/msgpack/msgpack-c/blob/cpp-1.0.0/include/msgpack/pack.hpp#L53

**Comment by thinxer** [comment]
Thanks for the clarification. Always using uint for positive numbers is good choice for now, though I still hope that the spec could make this clearer. Closing.
