### ISSUE TITLE
a possible bug of msgpack-c

### ISSUE THREAD

**Issue by zhangbiao2009** [msgpack/msgpack-c#254]
Hello, I use msgpack-c 1.0 to pack the following string:
{"code":20004,"ex":"Unknow method","msg":"Socket: 5, address: 127.0.0.1:49120","raiser":"setasdf"}

the result byte stream is different from which msgpack.org's demo gives.
my result is 82 bytes(hex):
84a4636f6465cd4e24a26578ad556e6b6e6f77206d6574686f64a36d7367d923536f636b65743a20352c20616464726573733a203132372e302e302e313a3439313230a6726169736572a773657461736466

but  the result of msgpack.org's demo is 83 bytes(hex):
84a4636f6465cd4e24a26578ad556e6b6e6f77206d6574686f64a36d7367da0023536f636b65743a20352c20616464726573733a203132372e302e302e313a3439313230a6726169736572a773657461736466

I'm not sure whether it's a bug of msgpack-c.  Any suggestion?

Thank you!

**Comment by redboltz** [comment]
Which demo are you talking about? Could you show me the code?

**Comment by zhangbiao2009** [comment]
The demo that I mean is the *"Try!"* button on http://msgpack.org web site. 
My code below:
````c
#include <msgpack.h>
#include <stdio.h>
#include <string.h>

int main(void)
{
        /* msgpack::sbuffer is a simple buffer implementation. */
        msgpack_sbuffer sbuf;
        msgpack_sbuffer_init(&sbuf);

        // {"code":20004,"ex":"Unknow method","msg":"Socket: 5, address: 127.0.0.1:49120","raiser":"setasdf"}
        /* serialize values into the buffer using msgpack_sbuffer_write callback function. */
        msgpack_packer pk;
        msgpack_packer_init(&pk, &sbuf, msgpack_sbuffer_write);

        msgpack_pack_map(&pk, 4);
        char* str = "code";
        msgpack_pack_str(&pk, strlen(str));
        msgpack_pack_str_body(&pk, str, strlen(str));
        msgpack_pack_int(&pk, 20004);
        str = "ex";
        msgpack_pack_str(&pk, strlen(str));
        msgpack_pack_str_body(&pk, str, strlen(str));
        str = "Unknow method";
        msgpack_pack_str(&pk, strlen(str));
        msgpack_pack_str_body(&pk, str, strlen(str));
        str = "msg";
        msgpack_pack_str(&pk, strlen(str));
        msgpack_pack_str_body(&pk, str, strlen(str));
        str = "Socket: 5, address: 127.0.0.1:49120";
        msgpack_pack_str(&pk, strlen(str));
        msgpack_pack_str_body(&pk, str, strlen(str));
        str = "raiser";
        msgpack_pack_str(&pk, strlen(str));
        msgpack_pack_str_body(&pk, str, strlen(str));
        str = "setasdf";
        msgpack_pack_str(&pk, strlen(str));
        msgpack_pack_str_body(&pk, str, strlen(str));

        int i;
        for(i=0; i<sbuf.size; i++){
            unsigned char byte = *((unsigned char*)sbuf.data + i);
            printf("%x", (unsigned int)byte);
        }

        printf("\n");

        msgpack_sbuffer_destroy(&sbuf);

        return 0;
}
````

**Comment by redboltz** [comment]
Thank you! Now I understand the issue. The first different byte is 'da' and 'd9'. msgpack-c supports msgpack format v5. See https://github.com/msgpack/msgpack/blob/master/spec.md

'd9' is the header of STR8. It has been introduced since v5 format. 
Before v5 format, 'da' is used. It is the header of STR16.

STR8 holds 1byte to explain the length. Str16 holds 2 bytes to do so.

It seems that Try! demo not support v5 packing.

**Comment by zhangbiao2009** [comment]
Thanks for the quick reply, redboltz. I tried msgpack for other languages such as Objective-C and PHP,  both the result are the same as Try! demo. So I guess in order to interact correctly with other languages I should use msgpack-c 0.5.9 instead of msgpack-c 1.0.0. Is that right?

**Comment by redboltz** [comment]
Good point. Most of implementation apply the two phase migration.

Phase 1. Support only unpack for the new types.
Phase 2. Support both unpack and pack for the new types.

Checking packed bytes is not enough to distinguish the library is in phase 1 or 2. If all your target libraries in at least phase1, you can use them with phase2 libraries such as msgpack-c 1.0.0 or leter.

**Comment by zhangbiao2009** [comment]
Thank you, redboltz.

**Comment by redboltz** [comment]
I've just sent the PR to support v4 format. See https://github.com/msgpack/msgpack-c/pull/258

I recommend that if you need to support v4 format, use #258 instead of use older version. Because, newer version includes many bug fixes.

You can compare the msgpack format 
v5:
https://github.com/msgpack/msgpack/blob/master/spec.md
v4:
https://github.com/msgpack/msgpack/blob/master/spec-old.md

**Comment by redboltz** [comment]
Packing old v4 raw format is supported now.
https://github.com/msgpack/msgpack-c/commit/9e7564c9d745e18fc042b838a01f0b5171ec4def

You can use v4raw adaptor in C++ and msgpack_pack_v4raw() and msgpack_pack_v4raw_body() in C.
