### ISSUE TITLE
two suggestions

### ISSUE THREAD

**Issue by dawnlucky** [msgpack/msgpack-c#273]
Hey guys,

In object.hpp: operator<< function：
1，when type is STR and have symbol(") in the string, could we escape it？
2，when type is MAP, could we change symbol(=>) to symbol(:)? then we can parse it.

Mack

**Comment by redboltz** [comment]
Hi @dawnlucky, thank you for the suggestions. Currently, msgpack::object's stream output format is a JSON like format but not a JSON. I imagine that outputs are used for debug. If the output format is JSON, it is a good interface for other module that requires JSON inputs. It's worth supporting. I will update the format.

**Comment by dawnlucky** [comment]
Great, Thanks @redboltz

**Comment by dawnlucky** [comment]
any update?

**Comment by redboltz** [comment]
Just merged by @nobu-k.

**Comment by dawnlucky** [comment]
Thanks. @redboltz @nobu-k
