### ISSUE TITLE
msgpack::object copy constructor issue?

### ISSUE THREAD

**Issue by shilkin** [msgpack/msgpack-c#280]
It seems that msgpack::object copy constructor doesn't copy all memory of one object to another.
I found that there is a "hanging" pointers on a memory, which shared with other objects, for example union_type::object_map, union_type::array and other have pointers to external memory, which can be damaged from some other thread (in my case):
```c
struct object_map {
    uint32_t size;
    msgpack::object_kv* ptr; // here it is!
};
```
Copy constructor copy only pointer on msgpack::object_kv, but not the whole memory:
```c
inline object::object(const msgpack_object& o)
{
    // FIXME beter way? 
    std::memcpy(this, &o, sizeof(o));
}
```
Is it correct assumption?

**Comment by redboltz** [comment]
msgpack::object's copy constructor do a shallow copy. The msgpack::object that is the elements of arrays and maps are located on the memory pool named 'zone'.
See https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_object

If you want to do a deep copy, do as follows:

```C++
//　src is a msgpack::object
msgpack::zone z;
msgpack::object dest(src, z);
```
All subobjects in the src are deep copied on to dest's subobjects located on z.
You need to manage z's lifetime.

**Comment by shilkin** [comment]
Thanks! I hoped that msgpack::zone is a low-level internal structure, but unfortunately it's not.
Ok, I'll be manage z's lifetime and read documentation:-)
