### ISSUE TITLE
How do I handle pointer to heap object when use MSGPACK_DEFINE or adapter

### ISSUE THREAD

**Issue by blueseason** [msgpack/msgpack-c#289]
struct A {
int a;
MSGPACK_DEFINE(a);
};

struct A1: struct A {
char* str;
MSGPACK_DEFINE(MSGPACK_BASE(A),str);
};

struct A2: struct A {
double d;
MSGPACK_DEFINE(MSGPACK_BASE(A),d);
};
struct  B {
int b;
struct A * p;
MSGPACK_DEFINE(b,*p);
}

and it needs allocat/delete p by user, also need to know the concrete child object.
is this usage ok? or need to write adapter manually? or any other good method to achieve the goal?

**Comment by redboltz** [comment]
You need to write a custom adapter manually using non intrusive approach.

See
https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_adaptor

The 'pack' adapter for char* exists.
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/adaptor/char_ptr.hpp#L69
But 'convert' adapter doesn't. General pointer adapters such as struct A* doesn't exist neither.

When you implement adapters manually, If the actual object could be a derived class instance, you would need to use RTTI or a custom type field.

**Comment by redboltz** [comment]
I will close the issue. If you have any comments, please let me know.
