### ISSUE TITLE
zbuffer cannot pack empty strings

### ISSUE THREAD

**Issue by llchan** [msgpack/msgpack-c#291]
Empty strings cause problems with zbuffers.  In the write function for both C and C++, there is a zlib deflate call, and in order for that call to be treated as successful, it must return `Z_OK`.  However, the zlib docs say that `Z_BUF_ERROR` can be returned in the case that "no progress is possible," which includes the case when `avail_in` (a.k.a. `len` in this case) is 0.

There's already a check to see if `avail_in` is 0, but it sits in a do/while condition rather than a regular while loop.  My current fix just switches that around.  Is there a reason it was originally written as a do/while rather than a while loop?  I'm not super familiar with the entirety of msgpack internals, so I'd like some feedback on this before sending in a pull request.

In case anyone wants to test, here's a trivial test case, and I imagine the C equivalent would hit a similar error.

```cpp
#include <msgpack.hpp>
#include <msgpack/zbuffer.hpp>

int main(int argc, const char* argv[]) {
    msgpack::zbuffer zbuf;
    msgpack::pack(zbuf, "");
    zbuf.flush();
}
```

**Comment by redboltz** [comment]
Hi @llchan , thank you for reporting the issue. I can't see any special reason to use do/while loop. I believe that your observation is correct. Could you send a pull request?
If you include C/C++ and their tests in your pull request, it would be very helpful.

**Comment by llchan** [comment]
Been a bit backlogged, but I should get to it soon.  And yep, I'll add some unit tests.
