### ISSUE TITLE
MSGPACK_BASE issue?

### ISSUE THREAD

**Issue by blueseason** [msgpack/msgpack-c#297]
struct A {
int a;
MSGPACK_DEFINE(a);
};

struct A1: struct A {
char* str;
MSGPACK_DEFINE(MSGPACK_BASE(A),str);
};

The MSGPACK_BASE is define as following:
#define MSGPACK_BASE(base) (*const_cast<base *>(static_cast<base const*>(this)))

A1 may be encoded as [ [a], str], but not [a. str],
 the super class in encoded as a separate object, but not with its child members, I think it is not conform to msgpack's protocol?

**Comment by redboltz** [comment]
Hi @blueseason , thank you for reporting the issue.

A1 may be encoded as [ [a], str], but not [a. str], as you mentiond.
However, msgpack specification doesn't define class layout. See https://github.com/msgpack/msgpack/blob/master/spec.md
It defines only primitive types format like JSON.

The goal of MSGPACK_BASE design is adding a functionality that serialize and deserialize instances of the class including their base classes using msgpack-c.

**Comment by blueseason** [comment]
Hi redboltz,
Thanks for your quick confirmation. I just think this layout is not intuitive to understand. And I wondered what's situation of on of the compatibility between different language implementation. As I know the msgpack-javascript uses the latter implementation. What do you think of this library? Seems has  no update for a long time.

**Comment by redboltz** [comment]
I don't have good ideas to implement latter way. The classes are serialized as array in msgpack-c. I think that the former implementation is work well with simple recursive algorithm. If you want to serialize  instances of your class, you can implement it as non-intrusive approach:
https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_adaptor#non-intrusive-approach

I don't think msgpack-javascript is implemented as the latter way. javascript doesn't have classes and inheritance conceptually. It is prototype and function based language.

By the way, I forked msgpack-javascript and implemented some updates:
https://github.com/redboltz/msgpack-javascript

It supports up to date msgpack format except EXT family.

**Comment by redboltz** [comment]
I will close the issue. If you have any comments, please let me know.
