### ISSUE TITLE
1.0 migration docs

### ISSUE THREAD

**Issue by swills** [msgpack/msgpack-c#298]
The release notes for 1.0 say:

This is the first major version up of msgpack-c. It isn't compatible with the previous version 0.5.9. Please look at wiki to learn how to migrate your project to the new version.

The link to "wiki" to learn how to migration is however missing and I can't seem to find it in the current wiki. Is it just missing or can I simply not find it? If it's missing, could it be added?

**Comment by redboltz** [comment]
Hi @swills , thank you for reporting the issue. The correct wiki page is https://github.com/msgpack/msgpack-c/wiki

After version 1.1.0 released, I reorganized wiki pages but I didn't update 1.0.0 documentation. The problem has been fixed in version 1.1.0. It has also been fixed cpp-1.0 branch https://github.com/msgpack/msgpack-c/commits/cpp-1.0

By the way, I strongly recommend that version 1.1.0 rather than 1.0.x.

**Comment by swills** [comment]
Thanks, I'll look at using 1.10 instead. My goal is to get https://github.com/tmm1/rbtrace updated to work with newer msgpack as it currently bundles msgpack 0.5.7. But since I'm not that familiar with msgpack, I need more detail on the changes. The main file I'm looking at is https://github.com/tmm1/rbtrace/blob/master/ext/rbtrace.c which has calls to msgpack_pack_raw and msgpack_pack_raw_body which seem to have disappeared in 1.x. I think those should be replaced with msgpack_pack_str and msgpack_pack_str_body instead. Is that right? Also, what about MSGPACK_OBJECT_RAW? Thanks for any help!

**Comment by redboltz** [comment]
This is new spec https://github.com/msgpack/msgpack/blob/master/spec.md
and this is old spec https://github.com/msgpack/msgpack/blob/master/spec-old.md

RAW family can contain any binary data in the old spec. One user uses it to contain strings, another user uses it to contain binary data. In the new spec, BIN family can contain any binary data. STR family can contain utf8 strings. You can choose appropriate one for your purpose.

**Comment by ogis-kondo** [comment]
I will close the issue. If you have any comments, please let me know.

**Comment by redboltz** [comment]
I will close the issue. If you have any comments, please let me know.
