### ISSUE TITLE
A good way to check environment

### ISSUE THREAD

**Issue by redboltz** [msgpack/msgpack-c#300]
msgpack-c checks the environment at several part of the code. 
For example,
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/unpack.hpp#L274

However, the checking is sometimes not complete, for example #296. I wrote a code to fix it https://github.com/redboltz/msgpack-c/commit/c63afb664029d12e83e652174bb265c4793bc50f but it is complecated and it requires license notice. If users use msgpack-c in their closed-source project, they need to add the license notice in their supporting documentation.

I was looking for a good way to check the environment, and found it. I think that Boost.Predef is a good candidate.

http://www.boost.org/doc/libs/1_58_0/libs/predef/doc/html/index.html

1. Boost.Predef is independent library. It doesn't depend on other parts of Boost libraries.
1. Boost.Predef is a header only library.
1. We can get Boost.Predef from https://github.com/boostorg/predef/tree/boost-1.58.0/include/boost
1. Boost.Predef can be used from C. See https://gist.github.com/redboltz/fd95a671ca1b764137de
1. Permissive License http://www.boost.org/users/license.html IIUC, if msgpack-c includes Boost.Predef and users use msgpack-c in their closed-source project, they don't need to add license notice. 
1. High quality code, it is peer reviewed by experts.

If this idea would be accepted, then I'd like to discuss how to deploy.

Any ideas?

**Comment by redboltz** [comment]
> how to deploy.
I think that using git submodule mechanism is good in this case as follows:
https://github.com/redboltz/subm_test

**Comment by redboltz** [comment]
### Here is in detail about my idea.
Prepare a directory for external header only libraries named "external".
```
msgpack-c/include/external
```
Locate external libraries under external directory. e.g.) boost
```
msgpack-c/include/external/boost/predef/include/boost/predef.h
                          /otherlib1
                          /otherlib2
```
In this case, "predef" is a mount point of submodule "predef".

In msgpack-c/include/msgpack/sysdep.h, include predef.h as follows:
```C++
#include <external/boost/predef/include/boost/predef.h>
```

### Consideration about boost libraries user

Consider the case that client code includes boost predef the following order:
```C++
#include <boost/predef.h> // From Boost Libraries. Regardless of whether direct or indirect
#include <msgpack.hpp>
```
#### Effect to msgpack-c
If the Boost Libraries version in the user environment is older than msgpack-c's one, and if the Boost Libraries has predef, then older predef is used, otherwise msgpack's one is used. In both cases, there is no problem because endian checking macros are defined from the initial version of predef.

#### Effect to user code
If the Boost Libraries version in the user environment contains predef, that is used. It's no problem. Otherwise msgpack-c's predef is defined in the user code. However, predef is independent library and the Boost Libraries in the user environment never refer to predef because the version of Boost Libraries doesn't have predef. There is no problem too.

Consider the case that client code includes boost predef the following order:
```C++
#include <msgpack.hpp>
#include <boost/predef.h> // From Boost Libraries. Regardless of whether direct or indirect
```
#### Effect to msgpack-c
No effects. Because msgpack-c refer to own version of predef.

#### Effect to user code
If the Boost Libraries version in the user environment is older than msgpack-c's one, then there is no problem. The reason is same as the above case. 
If the Boost Libraries version in the user environment is new than msgpack-c's one, msgpack-c's one might not have new macros in predef. Also some macros returns different results due to bug fix. That is a problem.

So far, I don't have good ideas to avoid the problem except forcing include order like "Please include boost libraries prior to including msgpack.hpp".

**Comment by redboltz** [comment]
I found a good solution. It is from @faithandbrave's idea. Thanks!

In order to solve the include order problem between the Boost Libraries in the user environment and in msgpack-c, I edit Boost.Predef's code by script.

Boost.Predef is placed msgpack-c/external/boost/ as a submodule. Then, all header files that have .h extension are read by cmake. Then, replace "BOOST_" with "MSGPACK_" and "boost/" with "msgpack/". Finally, write files that have replaced contents to msgpack-c/include/msgpack/.

After applying this process, all macros name are different, so we can inclulde both Boost Libraries in user environment and converted msgpack-c's Boost.Predef.

Converted files is a part of msgpack-c's package. You don't need to covert every time. Only when Boost.Predef is updated, and msgpack-c is applying the update, converting process is required.

I'm implementing and testing this mechanism. I will send a PR soon.

**Comment by redboltz** [comment]
Boost License permits a kinds of modification above. See http://www.boost.org/users/license.html
Modified version of Boost.Predef's sources keeps Boost License.

**Comment by nobu-k** [comment]
I merged the PR. Is there any remaining task for this?

**Comment by redboltz** [comment]
No. Everything is fine :)

Fixed by #312

**Comment by mikapak** [comment]
Hi Redboltz,
I want to use msgpack -c in embedded system project where cpu is ARM CORTEX M4. I can't use windows or linux files. getting error with os dependent file.
Is it possible to use msgpack-c in non-OS system. if so, could please provide me the procedure

**Comment by starthal** [comment]
@mikapak See issue #369 .

**Comment by mikapak** [comment]
Hi Starthal,

Thanks for your reply.
getting errors:
 msgpack-c supports only big endian and little endian.
 cannot open source input file "arpa/inet.h": No such file or directory
could you tell me what are the changes I have to make.

**Comment by redboltz** [comment]
Hi @mikapak , I wrote a comment at #369.
