### ISSUE TITLE
Can we make MSGPACK_DEFINE automatically pack all class members w/o manually specifying them?

### ISSUE THREAD

**Issue by dengliu** [msgpack/msgpack-c#317]
It would be greatly helpful if we have this feature because most of the time we want to pack the entire class but not part of the class.

**Comment by darknoon** [comment]
There isn't a way to statically find all of the member functions in C++ AFAIK, so I don't think this is possible.

**Comment by redboltz** [comment]
@darknoon is right. C++ doesn't have a functionality that detects member variables such as reflection. 

Recently, msgpack-c started to support Boost.Fusion sequence. See https://github.com/msgpack/msgpack-c/blob/master/test/boost_fusion.cpp#L18
You need to define MSGPACK_USE_BOOST.

You can define your own struct using BOOST_FUSION_DEFINE_STRUCT. It can adapt to msgpack-c function. I know it is not a solution that you expected but it could be a approximate solution.

**Comment by dengliu** [comment]
Thanks @darknoon and @redboltz.
I also found a idl Code Generator which seems to be able to serve the same purpose:
http://melpon.org/mpidl

**Comment by redboltz** [comment]
@dengliu , thank you for the information :)
I close the issue.
