### ISSUE TITLE
Read offsets are wrong

### ISSUE THREAD

**Issue by alexkamp** [msgpack/msgpack-c#348]
hey, 

The following code tries to read from a char * array. The array contains msgpack-data, namely: 

(uint_16) 3707, (positive fixnum) 64, (positive fixnum) 45, (uint_16) 3708, (uint_8) 128

when I unpack from the array, I use 6 as array size, while the real size is 10. This way the second uint_16 can not be read completely. 

I **expect** to get an offset of 5, because the second uint_16 starts at position 5, so the next read should start at 5. 

I **get** a value of 6. 

This bug causes problems when I am trying to read a file. The code in http://stackoverflow.com/questions/31969518/how-to-unpack-a-msgpack-file/32047245#32047245 depends on the offset to be correct. 

    #include<msgpack.h>
    
    int main(int argc, char **argv) {
        char *data = (char *)malloc(10*sizeof(char));
        data[0] = 0xCD; // uint_16
        data[1] = 0x0E;
        data[2] = 0x7B;
        data[3] = 0x40; // positive fixnum, 64
        data[4] = 0x2D; // positive fixnum, 45
        data[5] = 0xCD; // uint_16
        data[6] = 0x0E;
        data[7] = 0x7C;
        data[8] = 0xCC; // uint_8
        data[9] = 0x80;

        msgpack_unpacked unpacked;
        msgpack_unpacked_init(&unpacked);
        size_t offset = 0;
        while(MSGPACK_UNPACK_SUCCESS == msgpack_unpack_next(&unpacked, data, 6, &offset)) {
            msgpack_object_print(stdout, unpacked.data);
            puts("");
        }
        fprintf(stderr, "offset: %lu", offset);

    }

**Comment by n1tehawk** [comment]
Hi Alex!

In a reply at StackOverflow I've already pointed out that `msgpack_unpack_next()` probably isn't the way to go if you want a "streaming" deserializer. You might prefer the `msgpack_unpacker` struct and its associated functions instead, see https://github.com/msgpack/msgpack-c/blob/master/example/c/lib_buffer_unpack.c

Apart from that, I'm not sure that this can really be considered a bug. You'd be relying on side effects of a "partial" read (after all you get back MSGPACK_UNPACK_CONTINUE at this point) on the 'internal' offset. If you want to do it "the `msgpack_unpack_next()` way", then you should probably keep track of the next read offset yourself (while you get MSGPACK_UNPACK_SUCCESS):

```c
#include<msgpack.h>

int main(int argc, char **argv) {
    char *data = (char *)malloc(10*sizeof(char));
    data[0] = 0xCD; // uint_16
    data[1] = 0x0E;
    data[2] = 0x7B;
    data[3] = 0x40; // positive fixnum, 64
    data[4] = 0x2D; // positive fixnum, 45
    data[5] = 0xCD; // uint_16
    data[6] = 0x0E;
    data[7] = 0x7C;
    data[8] = 0xCC; // uint_8
    data[9] = 0x80;

    msgpack_unpacked unpacked;
    msgpack_unpacked_init(&unpacked);
    size_t next = 0;
    size_t offset = 0;
    while(MSGPACK_UNPACK_SUCCESS == msgpack_unpack_next(&unpacked, data, 6, &offset)) {
        next = offset;
        msgpack_object_print(stdout, unpacked.data);
        puts("");
    }
    fprintf(stderr, "offset: %lu\n", offset);
    fprintf(stderr, "next: %lu\n", next);
    return 0;
}
```
Regards, NiteHawk

**Comment by alexkamp** [comment]
Mhhh...First of all, you are right, it does work if I do it the "unpacker way". 

However, I still think that this is a bug. 

You said that this is "the internal offset". However, it is exposed to the user of the API and thereby not internal. If you do not want the offset to be used this way, you should not expose it to the user of the API. Maybe the entire function should not be exposed. 

Second, I am not sure what the meaning of MSGPACK_UNPACK_CONTINUE is here. I understood it as "the object continues behind what I can see", which would indicate the unpacker can go on if I give it more data. The streaming unpacker in fact can. So maybe MSGPACK_UNPACK_CONTINUE has two different meanings in different parts of the API? 

I think the very least would be to document that the offset is invalid for every return value except "MSGPACK_UNPACK_SUCCESS". In general, some source code comments to explain what the methods do wouldn't hurt.

**Comment by redboltz** [comment]
@alexkamp, thank you for reporting the issue. As you and @n1tehawk commented, offset updating behavior is correct on "unpacker way". However, it seems that the behavior is not appropriate on "unpack way". I didn't consider about that. So both C part and C++ part of msgpack-c share unpacking internal procedure including offset updating policy.

I think that offset should be 5 too in in the first comment as you expected. I will fix the problem.
