### ISSUE TITLE
Variant doesn't use STR/BIN/EXT templates

### ISSUE THREAD

**Issue by jpetso** [msgpack/msgpack-c#371]
Sorry that I didn't review the code on a timely basis, and correct me if I'm just reading it wrong.
`msgpack::type::basic_variant` takes three template types (STR, BIN, EXT) and passes them nicely all throughout the code where necessary, but in the lines that make it derive from boost::variant<...>, those template types are not passed down to boost::variant.

This seems like an oversight, and might have implications on providing both `as_string()` and `as_string_ref()` (or `as_vector_char()` and `as_raw_ref()`) in the same class... at least judging from the variant/variant_ref typedefs that use the templates as they were presumably intended.

(As an aside, which probably shouldn't be part of this issue but I wanted to mention it anyway, it would be nice if I could include msgpack_variant.hpp directly without having to #define MSGPACK_USE_BOOST first.)

**Comment by redboltz** [comment]
> Sorry that I didn't review the code on a timely basis, and correct me if I'm just reading it wrong.
msgpack::type::basic_variant takes three template types (STR, BIN, EXT) and passes them nicely all throughout the code where necessary, but in the lines that make it derive from boost::variant<...>, those template types are not passed down to boost::variant.

STR, BIN, and EXT are passed to boost::variant indirectly.
See:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/adaptor/boost/msgpack_variant.hpp#L67

They are passed to boost::recursive_wrapper. boost::recursive_wrapper is a facility that makes recursive variant as follows:
http://www.boost.org/doc/libs/1_59_0/doc/html/variant/tutorial.html#variant.tutorial.recursive.recursive-wrapper

> This seems like an oversight, and might have implications on providing both as_string() and as_string_ref() (or as_vector_char() and as_raw_ref()) in the same class... at least judging from the variant/variant_ref typedefs that use the templates as they were presumably intended.

When you convert to msgpack::type::variant from msgpack::object, std::string, std::vector<char>, and msgpack::type::ext are used. So is_string() returns true but is_boost_string_ref() returns false. Even if you use msgpack::type::variant, you can add reference types such as boost::string_ref to msgpack::type::variant. Then you can pack it. They are nicely mixed.

Similarly, when you convert to msgpack::type::variant_ref from msgpack::object, boost::string_ref, msgpack::type::raw_ref, and msgpack::type::ext_ref are used. So is_string() returns false but is_boost_string_ref() returns true. Even if you use msgpack::type::variant_ref, you can add value types such as std::string to msgpack::type::variant_ref.

I should write a documentation about that but I don't have much time, so far.

> (As an aside, which probably shouldn't be part of this issue but I wanted to mention it anyway, it would be nice if I could include msgpack_variant.hpp directly without having to #define MSGPACK_USE_BOOST first.)

Yes, https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/adaptor/boost/msgpack_variant.hpp#L21 should be removed. I will do it later. 

Thanks.

**Comment by jpetso** [comment]
> STR, BIN, and EXT are passed to boost::variant indirectly.
> See:
> https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/adaptor/boost/msgpack_variant.hpp#L67

What I see in these lines is that STR, BIN and EXT are passed to basic_variant again, not to boost::variant. Recursively speaking, all this means is that they show up again as templates in the original class declaration:
```
template <typename STR, typename BIN, typename EXT>
struct basic_variant : ...
```
So that the type of child item is the same as the type of the original class. However, unless these typenames are passed down to boost::variant or used directly, this will not have any effect other than changing the type of the variant. STR, BIN and EXT won't be used as storage for their respective msgpack types, and the variant will not provide e.g. std::get<STR>() accessors.

**Comment by redboltz** [comment]
I believe that I understand what you want to say now.

In my design, msgpack::type::variant and msgpack::type::variant_ref are public interfaces, msgpack::type::basic_variant is not. I should wrap it in detail namespace. Sorry about that.

I use STR, BIN, and EXT as type selectors for convert. And I assume that the types STR, BIN, and EXT are already in template arguments of boost::variant. In other words, choosing appropriate types from template arguments of boost::variant.

See:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/adaptor/boost/msgpack_variant.hpp#L259

If basic_variant and STR, BIN, and EXT are open to clients, it would be more flexible. But it is out of my scope, so far. I just a little bit think about that now. I need to find a way to avoid STR, BIN, and EXT and pre-prepared type conflict, they are the same type.

**Comment by jpetso** [comment]
Ah, I see. I don't actually have a use for creating my own templatized basic_variant yet, it just seemed like this was intended but not working. Thank you for explaining the actual reason for the template arguments. I'll close the issue since it isn't one.
