### ISSUE TITLE
libmsgpackc isn't built/installed when using CMake

### ISSUE THREAD

**Issue by jamessan** [msgpack/msgpack-c#395]
When using the autoconf-based build, both libmsgpackc.a/.so/.so.2 and libmsgpack.a/.so/.so.4 are created and installed.  When using the CMake build, only libmsgpack.a/.so/.so.3 (will be .4 when #394 is merged) are installed.

**Comment by redboltz** [comment]
@jamessan, thank you for reporting the issue. I think that libmsgpackc.a is the same as libmsgpack.a.

See:
https://github.com/msgpack/msgpack-c/blob/master/src/Makefile.am#L5
https://github.com/msgpack/msgpack-c/blob/master/src/Makefile.am#L18

I think that libmsgpackc.a should be removed to avoid confusion.

@nobu-k, what do you think?

**Comment by redboltz** [comment]
The C++ part of msgpack-c is a header only library now. In version 0.5.x, it was not a header only library. So libmsgpack.a was the C++ part of the library. libmsgpackc.a is the C part of the library. libmsgpack.a contains not only C++ part but also C part.

See:
https://github.com/msgpack/msgpack-c/blob/cpp-0.5.9/src/Makefile.am#L12

I think that we should remove libmsgpack.a. Not libmsgpackc.a.

**Comment by jamessan** [comment]
Ok, so is the declared SOVERSION in the makefiles related to the old C++ library or the C library?  Based on the way the autoconf-based makefiles run, it's for the C++ library.  In that case, #394 wouldn't be relevant as is and should be reworked to reflect the SOVERSION of the C library.

**Comment by redboltz** [comment]
I merged #394. Because inconsistent SOVERSION should be fixed. Removing libmsgpack.a is a different issue. I need to check the history of C and C++ library. I will report the result here.

**Comment by redboltz** [comment]
The C++ parts of msgpack-c no longer has a library file. So libmsgpack.a and libmsgpack.so should be removed. The C parts of msgpack-c has library files named libmsgpackc.a and libmsgpackc.sp. The so-version of libmsgpackc.so is 2.0.0. The interface of C parts doesn't update since 0.5.*. So the version 1.3.0 still has libmsgpackc.so 2.0.0.

**Comment by jamessan** [comment]
Ok.  Thanks for clarifying the situation.

**Comment by redboltz** [comment]
I sent #402 to solve the issue.

**Comment by anatol** [comment]
I believe these changes caused `neovim` to fail at my Arch Linux machine:

```
$ nvim 
nvim: error while loading shared libraries: libmsgpack.so.4: cannot open shared object file: No such file or directory
```

I am trying to rebuild `neovim` with newer version of `msgpack-c` and the build fails:

```
-- Looking for sendfile in sendfile - not found
-- Found LibUV: /usr/lib64/libuv.so  
CMake Error at /usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Msgpack (missing: MSGPACK_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindMsgpack.cmake:46 (find_package_handle_standard_args)
  CMakeLists.txt:274 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/anatol/sources/community-arch/neovim/trunk/src/build/CMakeFiles/CMakeOutput.log".
See also "/home/anatol/sources/community-arch/neovim/trunk/src/build/CMakeFiles/CMakeError.log".
```

Here is the `neovim` CMake file that fails https://github.com/neovim/neovim/blob/master/cmake/FindMsgpack.cmake


What is the best way to resolve the issue?

**Comment by jamessan** [comment]
neovim should be using libmsgpackc (the C library), not libmsgpack (historically the C++ library, but now not relevant since C++ code is all header only).

**Comment by redboltz** [comment]
@jamessan, thank you for following up. @anatol, sorry for your inconvenience.

I had ought to emphasize the change on https://github.com/msgpack/msgpack-c/releases/tag/cpp-1.4.0. I updated the wiki top page https://github.com/msgpack/msgpack-c/wiki to provide the information. I also updated C documentaion on the wiki https://github.com/msgpack/msgpack-c/wiki/v1_1_c_overview
