### ISSUE TITLE
Doxyfile isn't present in the release tarball

### ISSUE THREAD

**Issue by jamessan** [msgpack/msgpack-c#396]
I tried to build the documentation from the release tarball, but there is no Doxyfile present.

**Comment by jamessan** [comment]
Also related to the release process, there are empty ChangeLog and NEWS files in the tarball.  At least ChangeLog has a corresponding, non-empty file (CHANGELOG.md) in git.

**Comment by redboltz** [comment]
@jamessan, thank you for reporting the issue. I fixed it on #397.
