### ISSUE TITLE
Tests fail on big-endian systems

### ISSUE THREAD

**Issue by jamessan** [msgpack/msgpack-c#403]
Now that the unsigned char issue is fixed (thanks @redboltz!), Debian's [builds](https://buildd.debian.org/status/logs.php?pkg=msgpack-c&ver=1.3.0-2&suite=experimental) are looking better.  However, all the big-endian architectures failed on the same set of tests.

    [ RUN      ] cases.format
    cases.cpp:33: Failure
    Value of: result.get()
      Actual: 18446744069414584320
    Expected: result_compact.get()
    Which is: 4294967295
    cases.cpp:33: Failure
    Value of: result.get()
      Actual: 554050781183
    Expected: result_compact.get()
    Which is: -2147483648
    [  FAILED  ] cases.format (1 ms)

and

    [ RUN      ] MSGPACKC.unpack_array_uint64
    msgpack_c.cpp:1253: Failure
    Value of: obj.via.array.ptr[0].via.u64
      Actual: 72057594037989631
    Expected: 0xFFF0000000000001LL
    Which is: 18442240474082181121
    [  FAILED  ] MSGPACKC.unpack_array_uint64 (1 ms)

I haven't had a chance to look into the code yet, but I wanted to report the problem.

**Comment by redboltz** [comment]
Thank you for reporting the problem. I will take a look the problem. However, I don't have big-endian environment. Do you know any way to get a (virtual) big-endian environment?

**Comment by jamessan** [comment]
You might be able to use [QEMU](http://qemu.org/) to perform some testing.  I can also easily do rebuilds using Debian's porterboxes, if you have a patch to test.

When I get home tonight, I'll also take a look at the code.

**Comment by redboltz** [comment]
Thank you for the comment.

> You might be able to use QEMU to perform some testing.

 I will try QEMU. It seems to be a little difficult to setup ;) 

> I can also easily do rebuilds using Debian's porterboxes, if you have a patch to test.
>
>When I get home tonight, I'll also take a look at the code.

Thank you. It's very helpful :) I analyzed the code using your test result. Let's share that.

The failure msgpack_c.cpp:1253 https://github.com/msgpack/msgpack-c/blob/master/test/msgpack_c.cpp#L1253 is an unpacking test.

msgpack formatted data is 
    (char)0x91, (char)0xcf, (char)0xff, (char)0xf0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01
https://github.com/msgpack/msgpack-c/blob/master/test/msgpack_c.cpp#L1253

Actual value is 72057594037989631 (decimal). It is 0x0100 0000 0000 F0FF

It seems that little-endian unpacking logic is applied.

The implementation of little-endian and the big-endian is defined the following point:

Little-endian
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h#L120

Big-endian
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h#L135

The endian is checked at https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h#L81 and https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h#L131.

The macro MSGPACK_ENDIAN_LITTLE_BYTE and MSGPACK_ENDIAN_BIG_BYTE are defined in 
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/predef/other/endian.h

endian.h is from Boost.Predef http://www.boost.org/doc/libs/1_60_0/libs/predef/doc/html/index.html
 
The expected result of the macros definition on a big-endian environment are MSGPACK_ENDIAN_LITTLE_BYTE is not defined and MSGPACK_ENDIAN_BIG_BYTE is defined.

Could you check those macro definitions?

**Comment by jamessan** [comment]
> The expected result of the macros definition on a big-endian environment are MSGPACK_ENDIAN_LITTLE_BYTE is not defined and MSGPACK_ENDIAN_BIG_BYTE is defined.

Not quite. :) The expected result is that `MSGPACK_ENDIAN_LITTLE_BYTE` is "false" and `MSGPACK_ENDIAN_BIG_BYTE` is "true".  The macros which are (un)defined depending on the endianness are `MSGPACK_BIG_ENDIAN`/`MSGPACK_LITTLE_ENDIAN` (from include/msgpack/predef/detail/endian_compat.h).

PR 404 fixes this.
