### ISSUE TITLE
CMP0054 policy

### ISSUE THREAD

**Issue by morozovcookie** [msgpack/msgpack-c#424]
Need to remove double quotes from IF() and ELSEIF()

**Comment by reza-ebrahimi** [comment]
I think your issue related to ```CMake```, Please provide more information about it.

**Comment by edsiper** [comment]
Looks like he refer to this:

https://cmake.org/cmake/help/v3.1/policy/CMP0054.html

I don't see an issue with cmake 3.5.1 and the latest version from Git.

**Comment by redboltz** [comment]
Sorry for my late reply. I don't see how should I solve the issue. Set the policy to OLD seems to be not an essential solution.

For example,

https://github.com/msgpack/msgpack-c/blob/master/CMakeLists.txt#L47
```
   IF ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
```

How should I modify the code above? Any help will be welcome :)

**Comment by redboltz** [comment]
I found the way to suppress warnings. I sent the PR #491

**Comment by redboltz** [comment]
Fixed by #491
