### ISSUE TITLE
Crash when packing empty vector<char>

### ISSUE THREAD

**Issue by sirbrialliance** [msgpack/msgpack-c#433]
Attempts to pack an empty std::vector<char> result in undefined behavior.

This:
```
msgpack::sbuffer msgBuf;
std::vector<char> data(0);
msgpack::pack(msgBuf, data);
```
ultimately calls data.front():
```
//vector_char.hpp:54
o.pack_bin_body(&v.front(), size);
```
which is only valid on a vector of nonzero length.

**Comment by redboltz** [comment]
@sirbrialliance, thank you for reporting the issue. I sent #435 to fix the issue. Could you check it?

**Comment by sirbrialliance** [comment]
That works wonderfully! Thank-you!
