### ISSUE TITLE
unpack zone cannot clear?

### ISSUE THREAD

**Issue by leesatoh** [msgpack/msgpack-c#440]
I want to using same zone many time. So I call msgpack::zone::clear() before unpack(msgpack::zone, mybufer, mylength).
But some time , process was core-dumped.
When use zone to unpack, Don't call clear() ?

**Comment by redboltz** [comment]
msgpack::objects are located on a zone. See https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_object

When you call zone::clear(), the msgpack::objects located on the zone become invalid. So you cannot access to the msgpack::objects. But you can reuse the msgpack::zone for the next unpacking.

**Comment by leesatoh** [comment]
Hell ! Thank you for your respose.
But I can't reuse  the msgpack::zone yat.
This is the sample program and data for this issue. 
https://github.com/leesatoh/SampleCode

**Execution**
1. Download "main_msgunpack.cpp" and "msgunpack_err.tail.hex"
2. Comiple this program. (e.g.) g++ -g main_msgunpack.cpp -I/home/tng/vendor/msgpack-c-master/include -o /home/tng/dev/bin/msgunpack_err -lstdc++
3. Execute code with hexdata. (e.g.) msgunpack_err < msgunpack_err.tail.hex
 
 In my environment, this program abort by calling free function in destractor method.
Program terminated with signal 6, Aborted.
```
#0  0x00000037a2a32925 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.132.el6.x86_64 libgcc-4.4.7-4.el6.x86_64 libstdc++-4.4.7-4.el6.x86_64
(gdb) where
#0  0x00000037a2a32925 in raise () from /lib64/libc.so.6
#1  0x00000037a2a34105 in abort () from /lib64/libc.so.6
#2  0x00000037a2a70837 in __libc_message () from /lib64/libc.so.6
#3  0x00000037a2a76166 in malloc_printerr () from /lib64/libc.so.6
#4  0x00000037a2a78c93 in _int_free () from /lib64/libc.so.6
#5  0x0000000000401737 in msgpack::v1::zone::chunk_list::~chunk_list (this=0x60b488, __in_chrg=<value optimized out>)
    at /home/tng/vendor/msgpack-c-master/include/msgpack/v1/detail/cpp03_zone.hpp:103
#6  0x00000000004050a4 in msgpack::v1::zone::~zone (this=0x60b480, __in_chrg=<value optimized out>)
    at /home/tng/vendor/msgpack-c-master/include/msgpack/v1/detail/cpp03_zone.hpp:22
#7  0x0000000000407ce0 in GLOBAL::~GLOBAL (this=0x60b480, __in_chrg=<value optimized out>) at main_msgunpack.cpp:9
#8  0x00000037a2a35e22 in exit () from /lib64/libc.so.6
#9  0x00000037a2a1ed24 in __libc_start_main () from /lib64/libc.so.6
#10 0x0000000000401139 in _start ()

```

**Not clear**
When I didn't call msgpack::zone::clear(), this program  finished normally.
CommentOut this row.And execute by same process.
`G.Zone.clear();
`
`//G.Zone.clear();
`

**About hexdata**
Hex data "msgunpack_err.tail.hex" packed stream hex dump. This  is large.
When you take off commentout,  please be careful because there are many data.

```
//		std::cout << G.Obj;
//		printf("\n");

```

**Comment by redboltz** [comment]
Thank you for the detail report. I can reproduce the problem. It only happens C++03. I will take a look in detail about the problem. BTW, could you compile your code using C++11?

**Comment by leesatoh** [comment]
Thank you for your quick answer. But my compiler version  is gcc 4.4.7 now.
I try to update gcc. And I report a result later.

**Comment by redboltz** [comment]
I just sent the PR to fix the problem. Could you test  #441 ?
