### ISSUE TITLE
use MessagePack in ACE wrapper   error C2027: use of undefined type iovec MSVC2013

### ISSUE THREAD

**Issue by zhaokaixs** [msgpack/msgpack-c#445]
Hi,
  My project is use ACE WRAPPER,bug if i include msgpack.hpp

this is tips:
1>d:\dev\pss.git\trunk\purenessscopeserver\purenessscopeserver\example-module\tcptest\msgpack\include\msgpack/v1/vrefbuffer.hpp(28): error C2011: “iovec”:“struct”类型重定义
1>          D:\dev\ACE_wrappers\ace/os_include/sys/os_uio.h(42) : 参见“iovec”的声明
1>d:\dev\pss.git\trunk\purenessscopeserver\purenessscopeserver\example-module\tcptest\msgpack\include\msgpack/v1/vrefbuffer.hpp(130): error C2027: 使用了未定义类型“iovec”
1>          D:\dev\ACE_wrappers\ace/os_include/sys/os_uio.h(42) : 参见“iovec”的声明
1>d:\dev\pss.git\trunk\purenessscopeserver\purenessscopeserver\example-module\tcptest\msgpack\include\msgpack/v1/vrefbuffer.hpp(130): error C2227: “->iov_base”的左边必须指向类/结构/联合/泛型类型
1>d:\dev\pss.git\trunk\purenessscopeserver\purenessscopeserver\example-module\tcptest\msgpack\include\msgpack/v1/vrefbuffer.hpp(131): error C2027: 使用了未定义类型“iovec”
1>          D:\dev\ACE_wrappers\ace/os_include/sys/os_uio.h(42) : 参见“iovec”的声明
1>d:\dev\pss.git\trunk\purenessscopeserver\purenessscopeserver\example-module\tcptest\msgpack\include\msgpack/v1/vrefbuffer.hpp(131): error C2227: “->iov_len”的左边必须指向类/结构/联合/泛型类型
1>d:\dev\pss.git\trunk\purenessscopeserver\purenessscopeserver\example-module\tcptest\msgpack\include\msgpack/v1/vrefbuffer.hpp(163): error C2027: 使用了未定义类型“iovec”
1>          D:\dev\ACE_wrappers\ace/os_include/sys/os_uio.h(42) : 参见“iovec”的声明
1>d:\dev\pss.git\trunk\purenessscopeserver\purenessscopeserver\example-module\tcptest\msgpack\include\msgpack/v1/vrefbuffer.hpp(163): error C2227: “->iov_base”的左边必须指向类/结构/联合/泛型类型
1>d:\dev\pss.git\trunk\purenessscopeserver\purenessscopeserver\example-module\tcptest\msgpack\include\msgpack/v1/vrefbuffer.hpp(164): error C2027: 使用了未定义类型“iovec”
1>          D:\dev\ACE_wrappers\ace/os_include/sys/os_uio.h(42) : 参见“iovec”的声明
1>d:\dev\pss.git\trunk\purenessscopeserver\purenessscopeserver\example-module\tcptest\msgpack\include\msgpack/v1/vrefbuffer.hpp(164): error C2227: “->iov_len”的左边必须指向类/结构/联合/泛型类型
1>d:\dev\pss.git\trunk\purenessscopeserver\purenessscopeserver\example-module\tcptest\msgpack\include\msgpack/v1/vrefbuffer.hpp(165): error C2027: 使用了未定义类型“iovec”
1>          D:\dev\ACE_wrappers\ace/os_include/sys/os_uio.h(42) : 参见“iovec”的声明
1>d:\dev\pss.git\trunk\purenessscopeserver\purenessscopeserver\example-module\tcptest\msgpack\include\msgpack/v1/vrefbuffer.hpp(165): error C2227: “->iov_len”的左边必须指向类/结构/联合/泛型类型

**Comment by redboltz** [comment]
Your environment seems that Windows.

If defined _WIN32, then msgpack-c defines iovec. 
See https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/vrefbuffer.hpp#L25

However, it seems that iovec is already defined by ACE. 

Could you remove the iovec definition from msgpack-c/include/msgpack/v1/vrefbuffer.hpp as follows?

```C++
#ifndef _WIN32
#include <sys/uio.h>
#else
#if 0
struct iovec {
    void  *iov_base;
    size_t iov_len;
};
#endif
#endif
```

**Comment by zhaokaixs** [comment]
Yes,Thank you ,
I solved it


in msgpack.hpp 
//#include "msgpack/vrefbuffer.hpp"

or 

in vrefbuffer.hpp

namespace msgpack {
struct iovec {
    void  *iov_base;
    size_t iov_len;
};
 @redboltz

**Comment by redboltz** [comment]
Sounds good :)

If msgpack-c can know whether iovec is defined by ACE or not, msgpack-c can control iovec definition.

I've checked ACE's iovec definition. See http://www.aoc.nrao.edu/php/tjuerges/ALMA/ACE-5.5.2/html/ace/os__uio_8h-source.html

Checking the macro ACE_OS_INCLUDE_SYS_OS_UIO_H is a candidate, but it's a include guard. I think that it's not appropriate. So far, I don't find any good macro to check iovec definition.

I think that combining ACE and msgpack-c is not a common case. If there is no appropriate macro in ACE, I'd like to close the issue. What do you think?

**Comment by zhaokaixs** [comment]
@redboltz ok, thank u for your help and your patience

**Comment by redboltz** [comment]
Thank you @zhaokaixs, I close the issue.
