### ISSUE TITLE
Can I convert from json string to C++ class by use msgpack ?

### ISSUE THREAD

**Issue by Astone-Chou** [msgpack/msgpack-c#456]
I want use msgpack as a serialize tools to convert a json string for initialize a C++ class.

I can use msgpack::object 'convert' function to initialize a C++ class.

but, can I use a json string init msgpack::unpacked or msgpack::object ?

thx.

**Comment by jpetso** [comment]
It's doable, as long as you're willing to go through some intermediary objects.

Bonefish converts from JSON to msgpack::object ([see json_serializer::deserialize()](https://github.com/tplgy/bonefish/blob/master/src/bonefish/serialization/json_serializer.cpp)) with the help of RapidJSON and https://github.com/tplgy/json-msgpack to parse the JSON and write the msgpack::object. You could do something similar, and then take the resulting msgpack::object with `convert()` as you already described.

**Comment by Astone-Chou** [comment]
@jpetso 
Thank you very much ! I got it.
