### ISSUE TITLE
msgpack::object's stream output format

### ISSUE THREAD

**Issue by NorioKobota** [msgpack/msgpack-c#457]
Hi, maintainers.

This is related to #273 

<pre>
std::map<std::string, msgpack::type::nil_t> m = {{"key", msgpack::type::nil_t()}};
std::stringstream ss;
msgpack::pack(ss, m);
msgpack::object_handle oh = msgpack::unpack(ss.str().data(), ss.str().size());
std::cout << oh.get() << std::endl;
</pre>

Above result is ```{"key":nil}```.
I know the differences between nil and null, but unfortunately [JSON](https://www.ietf.org/rfc/rfc4627.txt) does not have nil as reserved word.

So I'll be grad if use null instead of nil in operator<< function.

Regards.

**Comment by redboltz** [comment]
@NorioKobota , thank you for reporting the issue. I will replace nil with null for JSON output.

**Comment by redboltz** [comment]
merged.
