### ISSUE TITLE
Compile error when include msgpack/adaptor/define.hpp directly.

### ISSUE THREAD

**Issue by redboltz** [msgpack/msgpack-c#463]
See https://github.com/msgpack/msgpack-c/pull/339#issuecomment-218696935

When a client code includes msgpack/adaptor/define.hpp directly, compile error occurs. msgpack/adaptor/define.hpp doesn't include enough include files.

**Comment by reza-ebrahimi** [comment]
@redboltz problem in ```int.hpp``` fixed but there is compile errors:

	adaptor_base_decl.hpp(49): error C2955: 'msgpack::v1::packer': use of class template requires template argument list
	adaptor_base_decl.hpp(23): note: see declaration of 'msgpack::v1::packer'
	adaptor_base_decl.hpp(49): error C2988: unrecognizable template declaration/definition
	adaptor_base_decl.hpp(49): error C2059: syntax error: '<'

**Comment by reza-ebrahimi** [comment]
@redboltz Please check your commits compatibility with earlier version of ```MSVC``` compiler such as ```VS2012``` and ```VS2010```.

**Comment by redboltz** [comment]
@reza-ebrahimi , I updated my commit. It includes MSVC 2010, 2012, 2013, and 2015. All tests passed. Could you check it?

**Comment by reza-ebrahimi** [comment]
@redboltz Compile errors returns back to our first state (compiled sample project with VS2015), Error snapshot:

![untitled](https://cloud.githubusercontent.com/assets/11276982/15276196/55947c28-1af6-11e6-9d66-aa265c7843d6.png)

**Comment by redboltz** [comment]
@reza-ebrahimi, hmm... the errors are not reproduced on my environment MSVC2015.
I added the similar test in the PR. https://github.com/redboltz/msgpack-c/blob/e6f82cf2bbf36f0a5f491444eb064f0a3d25a83e/test/inc_adaptor_define.cpp

Appveyor doesn't report errors neither.

Could you retry the branch on the clean environment? I mean from `git clone ...`.

**Comment by redboltz** [comment]
@nobu-k, could you check the PR on your environment?

**Comment by reza-ebrahimi** [comment]
@redboltz Oh, sorry for late response, I'll be check it in next 10 hours, Thanks.

**Comment by nobu-k** [comment]
Unfortunately, nobody around me had MSVC...

**Comment by redboltz** [comment]
Thanks, @nobu-k.
@reza-ebrahimi, did you test it? I'm sorry to rush you.

**Comment by reza-ebrahimi** [comment]
@redboltz Sorry for late response, The problem was exists, I have download cloned zip file directly from repository in github, so in order of that I have faced with new problem, the problem is when build INSTALL project, it will copies wrong hierarchy of directories in target location, The previous versions copied a directory as following:

    msgpack/include
    msgpack/lib

so with current version of repository the copied directory was:

    include

Yes, only include folder without its parent ("msgpack" folder) have been copied.

![untitled](https://cloud.githubusercontent.com/assets/11276982/15467749/6c5b6688-20f5-11e6-80fc-69e1d043e623.png)

**Comment by redboltz** [comment]
@reza-ebrahimi , thank you for the reply. 

Which branch did you test? #464 or `master`. If you tested `master`, the problem still exists because I didn't merge #464.

If you testes #464, something wrong...

Here is a command to checkout #464
```
git checkout -b redboltz-fix_463 master
git pull https://github.com/redboltz/msgpack-c.git fix_463
```

I also checked the error message that you attached. It is caused by the lack of include file on `int.hpp`. And I added it on #464 as follows:
https://github.com/msgpack/msgpack-c/pull/464/files#diff-3ae1f69a5ddd808b101c6031e39b5730R14

Could you check `include/msgpack/v1/adaptor/int.hpp` line 14 on your local file?
That should be `#include "msgpack/object.hpp"`

https://github.com/redboltz/msgpack-c/blob/fix_463/include/msgpack/v1/adaptor/int.hpp#L14

**Comment by reza-ebrahimi** [comment]
@redboltz I have checkout master branch, I didn't know that you were not commit changes to master, so I'll check it and get back here to report it, so I think the problem solved.

**Comment by redboltz** [comment]
@reza-ebrahimi , thank you for the checking. I will merge #464 soon.

> Is there any consideration that you doesn't commit changes to master branch?

Let me describe msgpack-c merging policy.

1. An issue is reported (e.g.#463)
2. Someone or I  post a pull request (e.g.#464)
3. Continuous Integration mechanism (travis-ci for Linux and OSX and appveyor for Windows) automatically kicked for the pull request.
4. If all tests are passed, I confirm the reporter that the problem has solved or not. (e.g. reporter is you).
5. The reporter checks the pull request, (NOT master). In this case it is #464.
6. After the checking the problem by the reporter, I merge the pull request to the master.

That's a typical sequence for Open Source Software Project on github.

If I omit the step 4 and 5, the problem might not solved on the reporter's environment. In that scenario, I can't keep the commit log on the master clean. Maybe some try and error is recorded on the commit log on the master. I want avoid it as far as I can do.

If you report the issue in the future, keep in mind the step above.

Anyway, I appreciate your cooperation.
