### ISSUE TITLE
Packing/Unpacking C-Style Arrays

### ISSUE THREAD

**Issue by mowaiskhan** [msgpack/msgpack-c#465]
Hello,

I have downloaded 1.4.1 and searched all the examples, Wiki and on Google as well but couldn't find anything, so turning here.

Is there any way that I can pack/unpack arrays having data type of char, std::string, user defined class?

char data[10];
std::string data2[10];
UserClass data3[20];

I have tried doing it for std::string array but couldn't make it work.

I am porting my code from boost::serialization library to MsgPack. I will appreciate any help.

Thanks & Regards,
Owais.

**Comment by redboltz** [comment]
msgpack-c didn't support C-Style array. It was just a low priority because there was no request.

It's a good time to support it. So I sent the PR #466 . Could you try it?

I think that the following code is adapted naturally:

```C++
std::string data2[10];
UserClass data3[20];
```

However, an array of char requires msgpack::type::make_array_ref.

```C++
char data[10];
```

See
https://github.com/msgpack/msgpack-c/pull/466/files#diff-59299c7e245697c7930e57263aa72421R92

An array of char is NOT mapped to ARRAY but STR.
Consider the following case:
```C++
char data[] = "Hello";
```

Users expect the array of char is mapped to STR. Similally an array of unsigned char (uint8_t) is mapped to BIN.

Those are default behavior. When you want to map them to ARRAY, you can use msgpack::type::array_ref and msgpack::type::make_array_ref.

**Comment by mowaiskhan** [comment]
Hello,

Thanks for prompt response. Though I couldn't comprehend all of what you wrote but I downloaded PR #466 and it worked perfectly for all below cases.

std::string array[10];
UserDefinedClass array[100];
char array[10000];
int array[10000];

I got few more questions, I will appreciate if you can answer.

1) This change will merged to all previous releases or will be available in latest release?

2) Where can i learn more about Msgpack usage and details as Wiki page doesn't carry all the details like we have boost documentation?

3) I got one more case, how to handle serialization/deserialization of template classes? for example I have a map class which is a template class having key,value passed as user objects?

Thanks & Regards,
Owais.

**Comment by redboltz** [comment]
@mowaiskhan , thank you for testing my PR. 

> 1) This change will merged to all previous releases or will be available in latest release?

No, I will merge to master, and then will release as version 2.0.0. The current release is 1.4.1. The merging policy of 1.4.1 is bug fixes only.

> 2) Where can i learn more about Msgpack usage and details as Wiki page doesn't carry all the details like we have boost documentation?

As you mentioned, the wiki page doesn't cover details. API reference documentation can be generated by `make doxygen`. It would take a pretty long time. 

Here is online version but it's not up-to-date http://c.msgpack.org/cpp/structmsgpack_1_1object.html.

The doxygen generated documentation is still incomplete. I will add doxygen comments for documentation. But it takes a long time, pull requests for adding doxygen comments are welcome :)

> 3) I got one more case, how to handle serialization/deserialization of template classes? for example I have a map class which is a template class having key,value passed as user objects?

I'm not sure what do you mean, but msgpack-c can (de)serialize class template as follows:
http://melpon.org/wandbox/permlink/bvPhsAzPwXTlMIHZ

**Comment by mowaiskhan** [comment]
You are welcome.

I am more than willing to contribute as it will help me learning as well, If you can help me, I will learn and contribute starting with writing tutorials, documentation to help beginners like me. 

I skimmed the template example and it seems it can work for my case, I will work on my case and will update you.

Thanks again for helping, appreciated.

Thanks & Regards,
Owais.

**Comment by redboltz** [comment]
merged. Thank you @mowaiskhan. 

> I am more than willing to contribute as it will help me learning as well, If you can help me, I will learn and contribute starting with writing tutorials, documentation to help beginners like me.

Sound good! If you have any questions, feel free to ask me :)
