### ISSUE TITLE
Stop supporting autotools from version 2.0

### ISSUE THREAD

**Issue by redboltz** [msgpack/msgpack-c#469]
We are going to stop supporting autotools from the version 2.0, the next release. Supporting both autotools and cmake is hard. We'd like to spend our resources more creative issues.

I believe that it is not a big issue because we already supports cmake. You can use cmake on Linux, OSX, Windows, and many other environment.

If someone can't use cmake and want to use autotools, please let me know with the reason.

**Comment by aberaud** [comment]
Hi,
Just noticed Autotools and MSVC support was dropped.
We use cmake already on Linux and OSX so dropping Autotools is fine for us,
but MSVC is still useful and needed to build natively on Windows.

It makes sense to drop autotools, but I don't see the point to remove native MSVC support.

**Comment by redboltz** [comment]
@aberaud we don't stop MSVC support. I removed `msgpack_vc8.sln` and `msgpack_vc8.vcproj` and because of that you might think so. Those files existed before we introduced cmake. We could create msvc solution and projects using them, but it was not convenient. That means edit those file directly. I'm not sure microsoft support that approach officially.

After introduced cmake, we can use it to create MSVC solution and project file. Here is the instruction: https://github.com/msgpack/msgpack-c#gui-on-windows
You can do the same thing using CLI version of cmake. https://github.com/msgpack/msgpack-c/blob/master/appveyor.yml is helpful to understand the command.
