### ISSUE TITLE
Difference between object.convert and object.as functions

### ISSUE THREAD

**Issue by mowaiskhan** [msgpack/msgpack-c#480]
Hello,

I am trying to understand source and behavior so kindly bear with me for very basic questions.

I observed something with below functions

        msgpack::unpacked unp;
        msgpack::unpack(unp, ss.str().data(), ss.str().size());
        msgpack::object obj = unp.get();

When I call below chunk of code to get my custom defined object back, my class' constructors are called and new object is constructed and then values are assigned to it.
        g = obj.as<gps_position>();

When I call below chunk of code to get my custom defined object back, my class' constructors are not called, only values I serialized are overwritten in object I passed to .convert function.
        obj.convert(g);

I tried to debug with Eclipse but couldn't reach the bottom of the issue, I will appreciate help.

Thanks & Regards,
Owais.

**Comment by redboltz** [comment]
@mowaiskhan, I don't understand what the question is. `msgpacl::object::as()` creates a new instance of the converted to type. `as()` requires a template argument. Try `obj.as<your_clas>()`.
`msgpack::convert()` overwrites the given argument. The type of argument is deduced.

**Comment by mowaiskhan** [comment]
Thanks.

Why we  have two different approaches to get de-serialize object?

1) msgpack::object::as<your_class>() - needs to create a new user object.

2) Whereas msgpack::object::convert(your_class_object) - overwrites supplied user object provided as argument

Option-2 wasn't enough and efficient as we don't really need to create object from beginning in many cases. This is basically the question :)

**Comment by redboltz** [comment]
@mowaiskhan, thank you for the clarification. I understand your question :)

Those two de-serialize function templates are provided from earlier version of msgpack-c before I became a committer. I think that `as` was provided for convenience at that time.

msgpack-c required the class to default-constructible if you want to convert from msgpack::object. So users needed to write default constructor to adapt msgpack-c.

Since the version 1.2.0, that requirement has been removed.
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#non-default-constructible-class-support-c11-only-since-120

If you use `as`, and provides `as` adaptor, you can convert non-default-constructible class from msgpack::object. In addition, move-semantics and RVO avoids to create temporary objects when you call `as()` in C++11.

**Comment by mowaiskhan** [comment]
Thanks for quick response :)

There is one more thing, I am unable to figure out.

If I use MSGPACK_DEFINE macro for serialization/deserialization I don't see constructors getting called again but if I use the template approach I see constructors getting called when object is deserialized.

Basically, I am trying to split serialize/deserialize as we can do in boost to put some logic there but don't want object's re-construction.

class Vault{
public:
	Vault()
	{
		cout << endl << "Inside Vault Constructor" << endl;
		type = "Store";
	}
	string type;
	`MSGPACK_DEFINE(type);`
};

struct ValutStruct {

 	ValutStruct()
	{
		cout << endl << "Inside ValutStruct constructor" << endl;
		VaultID = 1;
		Code = "XYZ";
		SecretID = 500;
		pSecretID = NULL;
	}

	int VaultID;
	string Code;
	int SecretID;
	int *pSecretID;
	Vault a;

        void display()
        {
                cout << endl << "VaultID<" << VaultID << ">"
                << endl << "Code<" << Code << ">"
                << endl << "SecretID<" << SecretID << ">"
                << endl << "pSecretID<" << *(pSecretID) << ">"
              << endl << "a.type<" << a.type << ">";
        }

MSGPACK_DEFINE(VaultID,Code,SecretID,a);
};


// User defined class template specialization
namespace msgpack {
MSGPACK_API_VERSION_NAMESPACE(MSGPACK_DEFAULT_API_NS) {
namespace adaptor {

template<>
struct convert<ValutStruct> {
    msgpack::object const& operator()(msgpack::object const& o, ValutStruct& v) const {
        if (o.type != msgpack::type::ARRAY) throw msgpack::type_error();
        if (o.via.array.size != 4) throw msgpack::type_error();
        v.VaultID = o.via.array.ptr[0].as<int>();
	v.Code = o.via.array.ptr[1].as<std::string>();
        v.SecretID = o.via.array.ptr[2].as<int>();
	v.a = o.via.array.ptr[3].as<Vault>();
        return o;
    }
};

template<>
struct pack<ValutStruct> {
    template <typename Stream>
    packer<Stream>& operator()(msgpack::packer<Stream>& o, ValutStruct const& v) const {
        // packing member variables as an array.
        o.pack_array(4);
        o.pack(v.VaultID);
        o.pack(v.Code);
        o.pack(v.SecretID);
       o.pack(v.a);
        return o;
    }
};

} // namespace adaptor
} // MSGPACK_API_VERSION_NAMESPACE(MSGPACK_DEFAULT_API_NS)
} // namespace msgpack

**Comment by redboltz** [comment]
@mowaiskhan , could you write minimal complete code? I copy pasted your code to Wandbox, online compiler that supports msgpack-c. http://melpon.org/wandbox/permlink/YcyPMrqLeZsNHoSU

Could you use this? After edit the code, click `Run` and then click `share this code`, then you can get permalink.

**Comment by mowaiskhan** [comment]
Thanks for help.

No, additional constructors are called during deserialization when we follow a intrusive approach.
http://melpon.org/wandbox/permlink/pXRcG4umWr75ByIZ

Additional constructor gets called for contained object(Vault in this case) when you deserialize and followed a non-intrusive approach.
http://melpon.org/wandbox/permlink/qMCtCPGXwqTeFTbm

Basically, I want to split serialization/deserialization like we do in boost's serialization library.I don't want to modify how msgpac serializes/deserializes but I want to make **selective** serialization/deserialization. That's why I want to split it. But, also I don't want object re-creation.

I hope my question is clear now.

I appreciate your help. Many Thanks.

**Comment by redboltz** [comment]
@mowaiskhan,

> I hope my question is clear now.

I understand what the question is :)

You use `as()` inside of the convert class template specialization.

```C++
v.VaultID = o.via.array.ptr[0].as<int>();
v.Code = o.via.array.ptr[1].as<std::string>();
v.SecretID = o.via.array.ptr[2].as<int>();
v.a = o.via.array.ptr[3].as<Vault>();
return o;
```

That calls constructor.

Replace them to operator>>, then copy constructor calls are eliminated.

```C++
o.via.array.ptr[0] >> v.VaultID;
o.via.array.ptr[1] >> v.Code;
o.via.array.ptr[2] >> v.SecretID;
o.via.array.ptr[3] >> v.a;
```
See
http://melpon.org/wandbox/permlink/pmTnWkeQkk16gFTQ

**Comment by mowaiskhan** [comment]
I see, Thanks a lot for clarification :)

I have been roaming in msgpack's source code and doxygen's generated documentation to understand msgpack architecture and working, I will appreciate if you can give some pointers which allows me to better understand it's internals and workings :)

Thanks & Regards,
Owais.

**Comment by redboltz** [comment]
@mowaiskhan, thank you for the comments. I also updated the wiki documantation https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor

> I have been roaming in msgpack's source code and doxygen's generated documentation to understand msgpack architecture and working, I will appreciate if you can give some pointers which allows me to better understand it's internals and workings :)

Here are some documents to describe msgpack-c.
http://www.slideshare.net/taka111/cppnow2015-msgpack-taka
http://www.slideshare.net/taka111/msgpackc

I close the issue.

**Comment by mowaiskhan** [comment]
Thanks a lot, appreciate your help.
