### ISSUE TITLE
The libmsgpack.so is dropped?

### ISSUE THREAD

**Issue by master-q** [msgpack/msgpack-c#483]
I found tag "cpp-1.4.0" doesn't create libmsgpack.so.

```
$ git checkout cpp-1.3.0
$ ./bootstrap
$ ./configure
$ make
$ find . -name "*.so*"
./src/.libs/libmsgpackc.so.2
./src/.libs/libmsgpack.so.4.0.0
./src/.libs/libmsgpackc.so.2.0.0
./src/.libs/libmsgpack.so
./src/.libs/libmsgpack.so.4
./src/.libs/libmsgpackc.so

$ git checkout cpp-1.4.0
$ ./bootstrap
$ ./configure
$ make
$ find . -name "*.so*"
./src/.libs/libmsgpackc.so.2
./src/.libs/libmsgpackc.so.2.0.0
./src/.libs/libmsgpackc.so
```

The libmsgpack.so is dropped?
However https://github.com/jubatus/jubatus-msgpack-rpc.git depends on it...

**Comment by redboltz** [comment]
The C++ part of msgpack-c is a jeader only library. So you don't need to link any library. If you use the C part of msgpack-c, use libmsgackc.

That's why libmsgpack no longer exists.

**Comment by redboltz** [comment]
s/jeader/header/

**Comment by master-q** [comment]
Thanks. I understand the reason.
