### ISSUE TITLE
MSGPACK_EMBED_STACK_SIZE and other parameters?

### ISSUE THREAD

**Issue by mowaiskhan** [msgpack/msgpack-c#484]
Hello,

If you use MSGPACK_DEFINE on 1.4 release to serialize/deserialize objects, do you need to define additional parameters to ensure that it works no matter if data is huge, nested, complex objects?

I will appreciate if we can mention such parameters.

Thanks & Regards,
Owais.

**Comment by mowaiskhan** [comment]
After few deserialize cycles, I got a crash dump and following line seems the error but I can't figure out what is N here?

#11 0x0000000000cbc967 in msgpack::v1::adaptor::convert<char [31], void>::operator() (this=0x7ffd415a9d4f, o=..., v=...)
    at /opt/msgpack-c-416/inst/include/msgpack/v1/adaptor/carray.hpp:51
51                  if (o.via.str.size + 1 > N) { throw msgpack::type_error(); }

**Comment by redboltz** [comment]
@mowaiskhan , here is a list of configuration parameters:

For 1.1 - 1.4
https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_configure

For 2.0
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_configure

If you use the C++ part of msgpack-c, MSGPACK_EMBED_STACK_SIZE is for only performance. It is used as the parameter of `std::vector::reserve()`. You can treat the depth over MSGPACK_EMBED_STACK_SIZE.

**Comment by mowaiskhan** [comment]
Thanks a lot
