### ISSUE TITLE
Details of portability

### ISSUE THREAD

**Issue by mowaiskhan** [msgpack/msgpack-c#490]
Hello,

Where can i find details about portability of msgpack-c.

In my scenario it can be used to serialize/deserialize data in a hybrid cluster comprising of machines like Linux_x64, Solaris_x86, Sparc.

Is there any kind of catch or it will work fine?

Thanks & Regards,
Owais.

**Comment by redboltz** [comment]
@mowaiskhan , do you mean you want to use msgpack-c on Linux_x64, Solaris_x86, Sparc, and so on? And you want to use MessagePack formatted binary data for messaging between platforms that are above target systems?

It will work fine.

MessagePack format is defined as follows:
https://github.com/msgpack/msgpack/blob/master/spec.md

msgpack-c is convert C/C++ structure to the MessagePack formatted binary data and vice versa.

By the way, MessagePack format integer is big-endian. msgpack-c can convert it ether the target platform is a little-endian or big-endian.

**Comment by mowaiskhan** [comment]
@redboltz Yes, you understood it correctly. All my questions are answered.

Thanks a lot for information. closing issue.
