### ISSUE TITLE
Persisting serialized data into Oracle

### ISSUE THREAD

**Issue by mowaiskhan** [msgpack/msgpack-c#493]
Hello,

I am planning to put serialized data of msgpack-c into Oracle, for that I have Oracle's OCCI library.

Since my serialized data is quite big around 18,000 bytes so I will have to large object support in Oracle.

I wanted to ask if someone has done this before and used CLOB datatype or BLOB datatype?

Thanks & Regards,
Owais.

**Comment by redboltz** [comment]
I have never used Oracle.

MessagePack data is a binary format. I think that BLOB is a better choice. If you store MessagePack data as a CLOB, Oracle considers the data are consisted on the character set you set on your environment.

**Comment by mowaiskhan** [comment]
Hello,

Thank you for response.

I have been working on doing it using BLOB datatype and it worked perfectly fine. 

I want to contribute a small working demo for this as I couldn't find any help on this, what will be the best place to place it?

Thanks & Regards,
Owais.

**Comment by redboltz** [comment]
> I want to contribute a small working demo for this as I couldn't find any help on this, what will be the best place to place it?

I have some questions.

* What does the demo mean? 
* What libraries does the demo use? 
* Can the demo be written as one source file?
* I think that the demo requires some descriptions. Can the descriptions be written as a comments in the source code?

**Comment by mowaiskhan** [comment]
> What does the demo mean?

just like examples we have in msgpack-c

> What libraries does the demo use?

It will use Oracle's OCCI library

> Can the demo be written as one source file?

Yes

> I think that the demo requires some descriptions. Can the descriptions be written as a comments in the source code?

Yes

Basically, no working sample was available so I thought I should write one and it might help someone one day.

**Comment by redboltz** [comment]
> Basically, no working sample was available so I thought I should write one and it might help someone one day.

I agree with you. I think that someone that want to use Oracle and BLOB with msgpack-c, they search this repository as follows:
https://github.com/msgpack/msgpack-c/search?utf8=%E2%9C%93&q=Oracle+BLOB

Then, this issue is hit. So I think that here is an appropriate location to place the demo.

```C++
    // This demo describes Oracle ...
    #include <msgpack.hpp>
    /* ... */
```

**Comment by mowaiskhan** [comment]
Alright, I will post it on this issue. Thanks
