### ISSUE TITLE
Build failure on sparc64 with obj.as<bottom>

### ISSUE THREAD

**Issue by jamessan** [msgpack/msgpack-c#494]
I recently updated Debian's packaging to the 1.4.2 release and ran into this build failure on sparc64.  All other architectures [built fine].

```
object_with_zone.cpp: In member function 'virtual void object_with_zone_user_defined_non_virtual_Test::TestBody()':
object_with_zone.cpp:745:32: error: '*((void*)& v +16)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     bottom br = obj.as<bottom>();
                                ^
object_with_zone.cpp:745:32: error: '*((void*)& v +12)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
object_with_zone.cpp:745:32: error: '*((void*)& v +8)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
object_with_zone.cpp:745:32: error: '*((void*)& v +4)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
object_with_zone.cpp:745:32: error: 'v' may be used uninitialized in this function [-Werror=maybe-uninitialized]
```

using this toolchain

```
Kernel: Linux 4.6.0-1-sparc64-smp sparc64 (sparc64)
Toolchain package versions: binutils_2.26-9+sparc64.2 dpkg-dev_1.18.7 g++-6_6.1.1-6 gcc-6_6.1.1-6
```

[built fine]: https://buildd.debian.org/status/logs.php?pkg=msgpack-c&ver=1.4.2-1&suite=experimental

**Comment by redboltz** [comment]
@jamessan , thank you for reporting the issue. I've checked the code. In this case, the warning "maybe-uninitialized" is no problem. 

So

```C++
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
```

should be added like as follows:

https://github.com/msgpack/msgpack-c/blob/3c997edd71a9a004179b36d8c4ee431551c961d9/test/user_class.cpp#L154

**Comment by redboltz** [comment]
I created the PR #495 to suppress the warning. @jamessan , could you test it on your environment?

```C++
Kernel: Linux 4.6.0-1-sparc64-smp sparc64 (sparc64)
Toolchain package versions: binutils_2.26-9+sparc64.2 dpkg-dev_1.18.7 g++-6_6.1.1-6 gcc-6_6.1.1-6
```

I believe that the warning "maybe-uninitialized" is false positive in this case.

**Comment by jamessan** [comment]
:+1: :shipit:

**Comment by redboltz** [comment]
Thank you for checking. I merged #495. 

> I recently updated Debian's packaging to the 1.4.2 release and ran into this build failure on sparc64. All other architectures built fine.

Is the issue the last problem to add msgpack-c to Debian? If it is, I will release the version 1.4.3 soon. If there are other tests, I will wait the result. And then I will release 1.4.3 that includes #495 and other fixes for the problems that might happen in the future.

**Comment by jamessan** [comment]
msgpack-c is in Debian's [experimental] release.  I need to finish trying to get the rest of the packages which depend on libmsgpackc ready for the transition to the post-1.0 version of the library, before uploading it to sid.  You can see the discussion/status in the [transition] tracker.

[experimental]: https://tracker.debian.org/pkg/msgpack-c
[transition]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815036

**Comment by redboltz** [comment]
Thank you for the comment. I understand the situation.

**Comment by jamessan** [comment]
The same change needs to be made to [user_class.cpp].

[user_stream.cpp]: https://github.com/msgpack/msgpack-c/blob/010acda932896be121915249e7b85ca5c4e85fda/test/user_class.cpp#L385

**Comment by redboltz** [comment]
I sent #506 to fix the issue. Could you test it?

**Comment by redboltz** [comment]
merged.

**Comment by redboltz** [comment]
Fixed by #506

**Comment by jamessan** [comment]
Should these fixes be applied to master as well?

**Comment by redboltz** [comment]
Yes it should be. I create the new issue for this. #519 

I will do that as soon as possible.

**Comment by redboltz** [comment]
merged to master.
