### ISSUE TITLE
 msgpack_object_print in buffer

### ISSUE THREAD

**Issue by smititelu** [msgpack/msgpack-c#496]
Hi,

Currently, is there a function that can print the object in a buffer? Something like msgpack_object_print(stdout, obj); but having a buffer instead of file.

Thanks,
Stefan

**Comment by redboltz** [comment]
The c++ part of msgpack-c has the functionality. See http://melpon.org/wandbox/permlink/sFU79DWMWQsV32ey

The C part doesn't.

**Comment by smititelu** [comment]
I've created pull request #500, which adds a new function to print in a allocated buffer.
Please tell me if something needs to be updated.

**Comment by redboltz** [comment]
Fixed by #500
