### ISSUE TITLE
How to decode large messages

### ISSUE THREAD

**Issue by apollo13** [msgpack/msgpack-c#502]
Is there any way to support decoding of large messages (ie above buffer capacity), when using a streaming unpacker? Changing the initial_buffer_size to something large, seems counterproductive.

Also it would be nice if unpacker supported "streaming" objects with a `read` method, similar to what pack does with `write`.

**Comment by redboltz** [comment]
> Is there any way to support decoding of large messages (ie above buffer capacity), when using a streaming unpacker? Changing the initial_buffer_size to something large, seems counterproductive.

I'm not sure I understand your question perfectly, but I answer. 
`initial_buffer_size` is a kind of optimization parameter. If the received data that require continuous memory is bigger than `initial_buffer_size`, the buffer is expanded using `realloc` and `memcpy`.  If the received data that *doesn't* require continuous memory, unpacker manages the memory as follows:
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_unpacker
http://www.slideshare.net/taka111/msgpackc

streaming unpacker's mechanism is also described in http://www.slideshare.net/taka111/msgpackc

streaming unpacker can treat well intermittent data. If received data is contained by multiple msgpack formatted data, you can get each complete `msgpack::object` by calling `msgpack::unpacker::next()`. However, if received data contains one huge msgpack formatted data such as huge ARRAY, `msgpack::unpacker::next()` returns false until all data is received. That means when `msgpack::unpacker::next()` returns true, the created `msgpack::object` contains all data, so it requires huge memory. If you want to avoid such a huge memory consumption, use `msgpack::parser` with visitor interface. See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_visitor . The document is written about visitor interface but not for streaming interface. I will write a document about the visitor interface for streaming interface. 

> Also it would be nice if unpacker supported "streaming" objects with a read method, similar to what pack does with write.

You can call packing APIs and then send the buffer even if not all data is packed, it works well:
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_packer#pack-manually

msgpack-c doesn't provide streaming packing interface but you can use normal packing interface as a streaming packing interface.

**Comment by apollo13** [comment]
> `initial_buffer_size` is a kind of optimization parameter.
> [snip]
> However, if received data contains one huge msgpack formatted data such as huge ARRAY, msgpack::unpacker::next() returns false until all data is received.

Ok, I will double check, it seemed that in my tests it would not unpack at all if my bin field is > MSGPACK_UNPACKER_INIT_BUFFER_SIZE (ie 64*1024).

**Comment by apollo13** [comment]
Okay, found my error -- I was using the wrong read size, either way thanks for the nice explanation, it cleared a few things up.
