### ISSUE TITLE
Strings of length 0

### ISSUE THREAD

**Issue by alexkamp** [msgpack/msgpack-c#503]
I was expecting the following code to print 

    ret = 0

because msgpack_pack_str_body returns 0 on success. However, it prints 

    ret = -1

So, apparently msgpack_pack_str fails on strings of length 0. 

However, I think this is related to how fbuffer_write is implemented. It handles a fwrite return value of 0 as an error, however, the manpage of fwrite guarantees that the return value is equal to the number of bytes written if len == 1. So, maybe fbuffer_write needs additional handling for this case?

    #include <msgpack.h>
    #include <msgpack/fbuffer.h>
    #include <sys/file.h>
    
    int main(int argc, char **argv) {
    	if(2 != argc) {
    		printf("argc: %d\n", argc);
    		return 1;
    	}

	msgpack_packer pk;
	FILE *fp = fopen(argv[1], "w");
	msgpack_packer_init(&pk, fp, msgpack_fbuffer_write);

	msgpack_pack_str(&pk, 0);
	int ret = msgpack_pack_str_body(&pk, "", 0);
	fprintf(stderr, "ret = %d\n", ret);
	fflush(fp);
	fclose(fp);
    }

**Comment by redboltz** [comment]
@alexkamp , thank you for reporting the issue. It seems that fbuffer's return value is wrong.

fbuffer
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/fbuffer.h#L26

sbuffer
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sbuffer.h#L59

vrefbuffer
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/vrefbuffer.h#L114
https://github.com/msgpack/msgpack-c/blob/master/src/vrefbuffer.c#L100
https://github.com/msgpack/msgpack-c/blob/master/src/vrefbuffer.c#L125

zbuffer
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/zbuffer.h#L119

I wrote #504 to fix the issue. Could you test it?

Here is the instruction:

```
git checkout -b redboltz-fix_503 master
git pull https://github.com/redboltz/msgpack-c.git fix_503
```
