### ISSUE TITLE
-Wno-mismatched-tags must not be used with GCC

### ISSUE THREAD

**Issue by obache** [msgpack/msgpack-c#507]
Now, in CMakeLists.txt
SET (GNUCXX_NO_MISMATCHED_TAGS_SUPPORT_VERSION "4.4")

It means that "gcc-4.4 and later" support "-Wno-mismatched-tags" option.

But "mismatched-tags" warning option is  never supported on any GCC version:
[Why GCC does not warn for mismatch between struct and class (-Wmismatched-tags) ?](https://gcc.gnu.org/wiki/FAQ#Why_GCC_does_not_warn_for_mismatch_between_struct_and_class_.28-Wmismatched-tags.29_.3F)
On some situations, unsupported warning option prefixed with "no-" may just ignored, but rise Error on my environment with "-Werror" option.

Please drop "-Wno-mismatched-tags" option addition completely on GCC.

**Comment by redboltz** [comment]
@obache , thank you for reporting the issue. I've double checked the gcc document. Maybe I got confused when I had add the option for g++.
Anyway, I just sent #508 to fix the issue. Could you check it?

Here is the instruction:
```
git checkout -b redboltz-fix_507 master
git pull https://github.com/redboltz/msgpack-c.git fix_507
```

**Comment by obache** [comment]
Yes, it resolve the issue here.

**Comment by obache** [comment]
@redboltz , you might get confused with -Wno-conversion-null option for g++.
Without it, `EXPECT_EQ(false, ...)` rise the wraning

> converting 'false' to pointer type for argument 1 of ...

and it result in build failure with `-Werror`.

**Comment by redboltz** [comment]
@obache , thank you for checking. merged.
