### ISSUE TITLE
Pack / Unpack - OMP / Parallel?

### ISSUE THREAD

**Issue by greendisc777** [msgpack/msgpack-c#510]
Is there parallel packing / unpacking support in msgpack-c? I don't seem to see it in any documentation anywhere.

**Comment by redboltz** [comment]
Unfortunately, there is no parallel packing / unpacking support.

msgpack-c can parallel pack from different object into the different buffer in different threads. But I guess that you don't mean that, you mean parallel packing one object (e.g. `std::vector`) into the same one buffer. Is that right?

I think a little about parallel packing / unpacking way. I found a problem to do that.

MessagePack format is variable length format. e.g. a length of the array, map, and integer types.

See
https://github.com/msgpack/msgpack/blob/master/spec.md#formats-array
https://github.com/msgpack/msgpack/blob/master/spec.md#formats-int

MessagePack format is also a recursive structure like as JSON.  For example `std::map<std::vector<int>,std::vector<int>>`.

So it's difficult to decide the position in the buffer for packing/unpacking.

**Comment by greendisc777** [comment]
I see - bummer. We're making distributed calls to a service from one machine - and sending those fragmented results back to the calling machine. We want to do two things:

1. Is there a way to make these distributed calls and join the results in the form of the binary encoded message? We basically want to pass around bytes to **multiple hosts** and at the end - unpack those bytes into the object and work on that data set.

2. You already answered with the parallel response.

Question #1 is the remaining question on whether we continue using msgpack.

**Comment by redboltz** [comment]
> 1. Is there a way to make these distributed calls and join the results in the form of the binary encoded message? We basically want to pass around bytes to multiple hosts and at the end - unpack those bytes into the object and work on that data set.

I considered the question and got an answer.

Step1.
For sending call, use complete MessagePack formatted message (not a part of ARRAY or MAP) for each hosts. You can use them in parallel. 

Step2.
The hosts receive and unpack the message. And do some  process, and then pack the result message as a complete MessagePack format, and send it back.

Step3
The sender will receive the number of hosts messages. Each message is a complete MessagePack format. You have two options. First one is converting the message into msgpack::object. When you receive all messages, then you have msgpack::objects that are corresponding to the messages. Then pack them as one message pack. See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_packer#pack-manually
 Call pack_array(size) or pack_map(size), and then pack(msgpack::object).
Receiving process can be in parallel, but creating final result process cannot be in parallel.
Second one is omitting unpacking process. Just keeping received MessagePack formatted messages. When all messages are received, create MessagePack format ARRAY or MAP header manually (the length field is variable length), and then copy each received messages step by step.
Receiving process can be in parallel, but creating (by copy) final result process cannot be in parallel.

**Comment by redboltz** [comment]
> use complete MessagePack formatted message (not a part of ARRAY or MAP) 

I realized that even if a part of ARRAY or MAP, it is also a complete MessagePack formatted message. Because MessagePack is composite (recursive) data structure.

In the Step3, if you don't care the order of messages, you don't need to wait all messages receiving. You can append the messages for each receiving.

If you know the number of received messages, you can create the header before receiving. If you don't know the number, you can reserve the length part of the array. See https://github.com/msgpack/msgpack/blob/master/spec.md#formats-int

**Comment by greendisc777** [comment]
Thank you for the response.

I wrote a little sample of what I am trying to achieve. I will be receiving a bunch of different pieces of a std::map and I would only like to decode once into one large map. I took your advice and appended the MessagePack formatted messages then sent that into the msgpack::unpack method. 

I only get the first part of the map out. 

Am I doing something wrong?

#include <iostream>
#include <map>
#include <sstream>
#include <msgpack.hpp>

using std::cout;
using std::endl;

class A {
public:
    A(int one, double two): one_(one), two_(two){};
    A(){};

    int one_;
    double two_;

    MSGPACK_DEFINE(one_, two_);
};

int main() {

    std::map<int, A> first;
    std::map<int, A> second;

    for(int i = 0; i < 5; ++i){
        first[i] = A(i, i * 2.2);
        second[i + 5] = A(i + 5, i * 3.3);
    }

    cout << "size of first: " << first.size() << endl;
    cout << "size of second: " << second.size() << endl;

    std::stringstream first_buf;
    msgpack::pack(first_buf, first);

    std::stringstream second_buf;
    msgpack::pack(second_buf, second);

    cout << "size of first encoded: " << first_buf.str().size() << endl;
    cout << "size of second encoded: " << second_buf.str().size() << endl;

    std::stringstream together_buf;

    together_buf << first_buf.str();
    together_buf << second_buf.str();

    cout << "size of together_buf encoded: " << together_buf.str().size() << endl;

    msgpack::object_handle oh =
            msgpack::unpack(together_buf.str().data(), together_buf.str().size());

    msgpack::object obj = oh.get();

    std::map<int, A> together_map;
    obj.convert(together_map);

    cout << "size of together map: " << together_map.size() << endl;

    for(auto a: together_map){
        cout << "key: " << a.first << "  value: " << a.second.one_ << ", " << a.second.two_ <<endl;
    }

    return 0;
}

**Comment by redboltz** [comment]
I update your code as follows:

```cpp
#include <iostream>
#include <map>
#include <sstream>
#include <msgpack.hpp>

using std::cout;
using std::endl;

class A {
public:
    A(int one, double two): one_(one), two_(two){};
    A(){};

    int one_;
    double two_;

    MSGPACK_DEFINE(one_, two_);
};

int main() {

    std::map<int, A> first;
    std::map<int, A> second;

    for(int i = 0; i < 5; ++i){
        first[i] = A(i, i * 2.2);
        second[i + 5] = A(i + 5, i * 3.3);
    }

    cout << "size of first: " << first.size() << endl;
    cout << "size of second: " << second.size() << endl;

    std::stringstream first_buf;
    msgpack::pack(first_buf, first);

    std::stringstream second_buf;
    msgpack::pack(second_buf, second);

    cout << "size of first encoded: " << first_buf.str().size() << endl;
    cout << "size of second encoded: " << second_buf.str().size() << endl;

    std::stringstream together_buf;

    together_buf << first_buf.str();
    together_buf << second_buf.str();

    cout << "size of together_buf encoded: " << together_buf.str().size() << endl;

    std::size_t off = 0;
    msgpack::object_handle oh1 =
        msgpack::unpack(together_buf.str().data(), together_buf.str().size(), off);
    msgpack::object_handle oh2 =
        msgpack::unpack(together_buf.str().data(), together_buf.str().size(), off);

    std::map<int, A> map1 = oh1.get().as<std::map<int, A> >();
    std::map<int, A> map2 = oh2.get().as<std::map<int, A> >();
    std::map<int, A> together_map = map1;
    together_map.insert(map2.begin(), map2.end());

    cout << "size of together map: " << together_map.size() << endl;

    for(auto a: together_map){
        cout << "key: " << a.first << "  value: " << a.second.one_ << ", " << a.second.two_ <<endl;
    }

    return 0;
}
```

You can see the result on the following online compiler names Wandbox.
http://melpon.org/wandbox/permlink/Z8eDd1gdIhUmlkGA

You just concatenated two msgpack buffers. In that case, msgpack-c can't unpack the buffer all at once. So I use the off set version of `unpack()`. See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_unpacker#client-controls-a-buffer

And then, merge the map using `std::map::insert()`.

I'm not sure it is acceptable solution for you. If you want to create concatenated MessagePack MAP buffer, you need to remove the MAP header from the two maps, and add header to the concatenated MAP. See https://github.com/msgpack/msgpack/blob/master/spec.md#formats-map
