### ISSUE TITLE
Bundling msgpack C++ as a header-only dependency

### ISSUE THREAD

**Issue by bluescarni** [msgpack/msgpack-c#516]
I would like to be able to bundle the header-only C++ version of msgpack-c in a 3rd party project, for ease of installation. However, currently this is rather difficult to do due to the way msgpack-c refers to its own headers.

For instance, ``object.hpp`` contains ``#include "msgpack/v1/object.hpp"``, which works fine as long as msgpack-c has been installed in a standard include path (e.g., ``/usr/include`` on unix). But, if msgpack-c is bundled with a third party project, the location of the msgpack headers will be something like ``/usr/include/my_project/external/msgpack``, which requires the user of ``my_project`` to add ``/usr/include/my_project/external`` to the include paths when compiling.

Is there a way to bundle msgpack-c in a 3rd part application so that the user does not have to do any additional setup in terms of extra compiler flags / include paths?

**Comment by redboltz** [comment]
@bluescarni , unfortunately there is no way to do that. Please add `msgpack-c-installed-location/include` to your include path. 

It is a common way to provide a header only library. For example, some part of Boost C++ Libraries are header only libraries. And they said that as follows:
 http://www.boost.org/more/getting_started/unix-variants.html#build-a-simple-program-using-boost
```
c++ -I path/to/boost_1_61_0 example.cpp -o example
```

**Comment by bluescarni** [comment]
Ok, fair enough.

Some header-only libraries use relative include paths, so that it's possible to just copy them into a 3rd party project as an external dependency without having to add include paths.

Closing this as it's not a bug, thanks for the reply!

**Comment by redboltz** [comment]
FYI #367
