### ISSUE TITLE
Unable to serialize floats as float32s using msgpack::object

### ISSUE THREAD

**Issue by mika-fischer** [msgpack/msgpack-c#521]
Am I missing something or is this just impossible? If so, why?

**Comment by redboltz** [comment]
What is float32? msgpack-c supports standard C++ floating point types. That is float and double.

**Comment by mika-fischer** [comment]
I'm refering to the spec: https://github.com/msgpack/msgpack/blob/master/spec.md#formats-float

**Comment by redboltz** [comment]
Aha, I understand your question. The current `msgpack::object` implementation has only one floating point expression. That is `double f64`. So when you create `msgpack::object` that is created by C++ `float` or unpacked from `float 32`, it is converted to C++ `double`. 

Hence, `msgpack::object` is always serialized as `float 64`.

**Comment by redboltz** [comment]
I came up with some design choice.

|msgpack::object internal type|serialized as|note|
|---|---|---|
|double|float 64|current implementation|
|preserve original|float 32, float 64 based on original|msgpack::type::FLOAT is used for float 64. difficult to keep compatibility and understandability *1 . It is a breaking change.|
|double|float 32(only if no data loss), float 64|use *2 for judge. similar strategy as int. It is a breaking change.|

*1 For example introducing the new types `msgpack::type::FLOAT32` and `msgpack::type::FLOAT64`. And define `msgpack::type::FLOAT` as an alias of `msgpack::type::FLOAT64`.

*2 http://melpon.org/wandbox/permlink/qWxNuYLjRblffiTs 

I think that we need to consider carefully which one is a good choice. A breaking change could be surprise to existing user.

**Comment by mika-fischer** [comment]
I'm also not sure what would be best, but I think it would be very good to make it possible, since msgpack is all about efficiency and the status quo is quite wasteful...

Option 2 is very nice for my use-case and in line with the integer handling. But the problem is that it is unclear whether a float32 or a float64 was deserialized (although one could just use the same check from *2, which is close but not the same).

In general I can see the need for both uses, direct mapping to spec types and automatic handling of types. But since at the moment, the library is leaning heavily towards the latter, option 2 would probably be best for now...
