### ISSUE TITLE
Travis build fails on OSX due to Valgrind incompatibility

### ISSUE THREAD

**Issue by starthal** [msgpack/msgpack-c#525]
Travis now uses OS X 10.11 as the default version. Previously it used OS X 10.9.

https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
Now Valgrind (3.10) is incompatible, and it fails to build.

```
wget http://valgrind.org/downloads/valgrind-3.10.1.tar.bz2 && tar xjf valgrind-3.10.1.tar.bz2 && cd valgrind-3.10.1 && ./configure && make && sudo make install && cd ..
<snip>
checking for a supported OS... ok (darwin15.6.0)
checking for the kernel version... unsupported (15.6.0)
configure: error: Valgrind works on Darwin 10.x, 11.x, 12.x and 13.x (Mac OS X 10.6/7/8/9)
```

**Comment by starthal** [comment]
A solution is either to upgrade Valgrind to 3.11:

http://valgrind.org/downloads/

>3.11.0 is a feature release with many improvements and the usual collection of bug fixes. This release adds full support for X86/Solaris and AMD64/Solaris, improves support for Mac OS X 10.10 (Yosemite), and adds preliminary support for Mac OS X 10.11 (El Capitan) and TileGX/Linux.

Or to force the OS X version back to 10.9 using the specifier `osx_image: beta-xcode6.2`.

**Comment by redboltz** [comment]
When I update valgrind to 3.11.0, some tests are failure. I don't know why.
When I set `osx_image: beta-xcode6.2` on the top level, linux builds are failure.
It seems that the setting affects not only `osx` but also `linux`.

Perhaps the issue https://github.com/travis-ci/travis-ci/issues/5125 could be the reason.

**Comment by redboltz** [comment]
I created #527 for valgrind 3.11.0 issue.
I changed travis-ci matrix strategy to support osx_image: beta-xcode6.2 correctl\y. See #526.
I will close the issue after merging #526.
