### ISSUE TITLE
Msgpack doesn't compile with gtest 1.8.0 and GCC 5.4.1

### ISSUE THREAD

**Issue by heylouiz** [msgpack/msgpack-c#537]
I couldn't compile the project with gtest 1.8.0 and GCC 5.4.1, it gives lots of errors when comparing size_t variables with numbers.
Eg:
```
auto s = "abc".size()
EXPECT_EQ(3, s);
```
I made some changes in the code and will submit a PR.

Thanks for the project!

**Comment by redboltz** [comment]
I close the issue. @heylouiz , I appreciate your efforts.
