### ISSUE TITLE
Can I deserialize the data, which serialized by msgpack-scala, by msgpack-c ?

### ISSUE THREAD

**Issue by xdwangh** [msgpack/msgpack-c#543]
Can I deserialize the data, which serialized by msgpack-scala, by msgpack-c ?

**Comment by starthal** [comment]
Absolutely! MsgPack on the wire is standard, as defined by the [spec](https://github.com/msgpack/msgpack/blob/master/spec.md). The different language implementations all conform to that spec.

**Comment by redboltz** [comment]
As @starthal mentioned, msgpack-c supports up to date MessagePack specification.

There are two versions of MessagePack format that commonly used.
See:

|Spec|name in msgpack-c|URL|
|---|---|---|
|up to date|v5|https://github.com/msgpack/msgpack/blob/master/spec.md|
|old|v4|https://github.com/msgpack/msgpack/blob/master/spec-old.md|

The naming of MessagePack format seems to be a little bit confused https://github.com/msgpack/msgpack/issues/195

I'm not sure which format msgpack-scala is supported.

Anyway, msgpack-c can deserialize both v4 and v5. msgpack-c can serialize as v5 by default.
If you call `pack_v4raw()` and `pack_v4raw_body()` explicitly, then msgpack-c serializes the binary(string) data as v4 format.
See
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/pack.hpp#L522

That means msgpack-c can work well with msgpack-scala.

**Comment by xdwangh** [comment]
hi @redboltz,

Thanks for your reply.
I confused for the serialized result. 
The serialized result of msgpack-c is an instance of msgpack::sbuffer. However, the corresponding result of msgpack-scala is Array[Byte]. I don't know how to deserialize the msgpack-scala result by msgpack-c. Could you give me more details about this?

cpp code:
`class newclass {
    public:
        std::string name;
        std::string age;
        MSGPACK_DEFINE(name, age);
};

int main() {
    newclass test;
    test.name = "Hao";
    test.age = "111";
    msgpack::sbuffer sbuf;
    msgpack::pack(sbuf, test);
    std::cout << sbuf.data() << std::endl;
    std::cout << sbuf.size() << std::endl;

    msgpack::object_handle oh = msgpack::unpack(sbuf.data(), sbuf.size());
    msgpack::object obj = oh.get();

    newclass robj;
    obj.convert(robj);
    std::cout << robj.name << " " << robj.age << std::endl;
}
`
result:
`<92>£Hao£111
9
Hao 111`

scala code:
`@Message // Don't forget to add Message annotation.
class YourClass{
      var name : String = ""
      var age : String = ""
}

object MainTest extends App {
  val obj = new YourClass()
  obj.name = "Hao"
  obj.age = "111"
  val serialized: Array[Byte] = ScalaMessagePack.write(obj)
  printf(serialized.toString + "\n")
  val deserialized: YourClass = ScalaMessagePack.read[YourClass](serialized)
  printf(deserialized.name + "\n")
  printf(deserialized.age + "\n")
}`
result:
`[B@23387253
Hao
111`

**Comment by redboltz** [comment]
@xdwangh , 
I'm not sure msgpack-scala's class field mapping policy. But I guess that msgpack-scala uses MAP for class field mapping.

msgpack-c maps class member variables to ARRAY by default, but you can customize the behavior.
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#intrusive-approach

In your C++ code, replace `MSGPACK_DEFINE` with `MSGPACK_DEFINE_MAP`, or add preprocessor definition `MSGPACK_USE_DEFINE_MAP` to the compiler like `-DMSGPACK_USE_DEFINE_MAP`.

**Comment by redboltz** [comment]
I close the issue because no further comments after my comment.
Feel free to re-open if you have more questions.
