### ISSUE TITLE
Compile error with gcc 4.4.7

### ISSUE THREAD

**Issue by tueda** [msgpack/msgpack-c#544]
msgpack-c fails to build with gcc 4.4.7 when compiled without C++11:
```
[ 54%] Building CXX object example/cpp03/CMakeFiles/simple.dir/simple.cpp.o
cc1plus: error: unrecognized command line option "-std=c++03"
```
Actually I can't find `-std=c++03` in the document of gcc 4.4.7: https://gcc.gnu.org/onlinedocs/gcc-4.4.7/gcc/C-Dialect-Options.html#C-Dialect-Options, although a backport for that flag may be provided in some systems.

**Comment by redboltz** [comment]
@tueda , thank you for reporting the issue.
I think that `-std=c++03` should be replaced with `-std=c++98`.
I will fix it.

**Comment by redboltz** [comment]
@tueda , could you check #545 ?

**Comment by tueda** [comment]
@redboltz the fix works to me. Thank you.
