### ISSUE TITLE
recommended replacement for deprecated "msgpack::pack"

### ISSUE THREAD

**Issue by murias** [msgpack/msgpack-c#546]
In object.hpp:
`inline void pack(msgpack::packer<Stream>& o, const T& v)`
is marked `// obsolete`.
What is the recommended replacement?

Thank you

**Comment by murias** [comment]
Thank you for your help. 
When I used the "follow Symbol under Cursor" shortcut in my IDE, it always pointed me to the `pack(packer<Stream>..)` wrapper.  It could be helpful to annotate the obsolenscence message with a pointer to the `pack(Stream& .. )` function.

Is there a plan to remove obsolete functions? It could prevent a lot of confusion, especially since they are both called `pack`.

**Comment by redboltz** [comment]
> Is there a plan to remove obsolete functions?
Yes. The first step is marking obsolete features to deprecated. See #534 
And release it.
Then, remove the features the next release.
