### ISSUE TITLE
C lib -> C++: error: template with C linkage

### ISSUE THREAD

**Issue by edsiper** [msgpack/msgpack-c#551]
My C library uses msgpack-C library, and some exported structures use the msgpack-c data types. When a C++ program uses my lib, I get the error "template with C linkage"

```
In file included from /usr/include/c++/6/bits/nested_exception.h:40:0,
                 from /usr/include/c++/6/exception:171,
                 from test/msgpack-template-problem/msgpack-c/include/msgpack/predef/detail/_exception.h:12,
                 from test/msgpack-template-problem/msgpack-c/include/msgpack/predef/library/std/_prefix.h:21,
                 from test/msgpack-template-problem/msgpack-c/include/msgpack/predef/library/std.h:12,
                 from test/msgpack-template-problem/msgpack-c/include/msgpack/predef/library.h:14,
                 from test/msgpack-template-problem/msgpack-c/include/msgpack/predef.h:16,
                 from test/msgpack-template-problem/msgpack-c/include/msgpack/sysdep.h:13,
                 from test/msgpack-template-problem/msgpack-c/include/msgpack/zone.h:13,
                 from test/msgpack-template-problem/msgpack-c/include/msgpack/object.h:13,
                 from test/msgpack-template-problem/msgpack-c/include/msgpack.h:17,
                 from test/msgpack-template-problem/mylib/mylib.h:10,
                 from test/msgpack-template-problem/test/main.cc:3:
/usr/include/c++/6/bits/move.h:45:3: error: template with C linkage
   template<typename _Tp>
```

This problem only happen with msgpack-c GIT master __after__ the following commit:

756d02f8c0edefe99b67df68c4206f5cf6e928af Added Boost.Predef to check environment such as endian.

before that commit the problem don't exists, so I can embedded it properly.

I have created a test case for the issue in question, it can be found in the following repo:

https://github.com/edsiper/msgpack-problem

My expectation is that no matters from where msgpack.h is included/exported, it should be safe inside an extern "C":

https://github.com/edsiper/msgpack-problem/blob/master/mylib/mylib.h#L6

**Comment by redboltz** [comment]
@edsiper , thank you for reporting the issue.

> My expectation is that no matters from where msgpack.h is included/exported, it should be safe inside an extern "C":
>
> https://github.com/edsiper/msgpack-problem/blob/master/mylib/mylib.h#L6

I don't think so.

The error is caused by the following line:
https://github.com/boostorg/predef/blob/develop/include/boost/predef/detail/_exception.h#L12

The C part of msgpack-c has already been encapsulated by `extern "C"` as follows:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/pack.h#L18

So you can move `msgpack.h` to out of `extern "C"`.

before:

```cpp
#ifdef __cplusplus
extern "C" {
#endif

#include <msgpack.h>
```

after:

```cpp
#ifdef __cplusplus
#include <msgpack.h>
extern "C" {
#endif

```

By the way, I personally recommend that when you use C++, use C++ version of msgpack-c by `#include <msgpack.hpp>`. Of course, I don't know about your project situation, it is just a recommendation :)

**Comment by edsiper** [comment]
thanks for the suggestion. Moving msgpack.h outside of _extern "C"_ did the trick :)
