### ISSUE TITLE
How can I tell if unpacker's buffer only contains "finished" msgpacks?

### ISSUE THREAD

**Issue by sztomi** [msgpack/msgpack-c#560]
I'm reading chunks of data from a socket, into the buffer of an `unpacker`. I've implemented the while loop similarly to how it is shown in the examples:

```cpp
    void do_read() {
        writer_->socket_.async_read_some(
            asio::buffer(pac_.buffer(), default_buffer_size),
            [this](std::error_code ec, std::size_t length) {
                if (!ec) {
                    pac_.buffer_consumed(length);

                    msgpack::unpacked result;
                    while (pac_.next(&result)) {
                        // ...
                    }
                    // (1) 
                    do_read();
                }
            });
    }
```

At (1) I would like to clear the buffer if there is no unprocessed data in it (i.e. no unfinished chunk of a larger msgpack was received). I can't assume that I always get the same sizes of data chunks. Is there a way to know this?

**Comment by redboltz** [comment]
@sztomi , use 

```cpp
pac_.message_size();
```

It returns the value that `the size of consumed and partially parsed` + `the size of consumed but not parsed yet`. So if `message_size()` is zero, that means all data are processed.

See also https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_unpacker#msgpack-controls-a-buffer
and http://www.slideshare.net/taka111/msgpackc

unpackers memory is managed by unpacker. If there is no reference from unpacked msgpack::object, and there is no unprocessed data in the chunk, unpacker automatically delete the chunk. You don't need to care about chunk memory management.

**Comment by sztomi** [comment]
Thanks, your comment helped me find some bugs in my own code. I thought I was segfaulting because the unpacker buffer needed to be cleared, but in reality an `object` referenced its memory.
