### ISSUE TITLE
'int8_t' redefinition, different basic types in stdInt.h

### ISSUE THREAD

**Issue by shilpigithub** [msgpack/msgpack-c#564]
Hi,

I am getting 'int8_t' redefinition, different basic types in stdInt.h  what to do to resolve this . I am building on Microsoft Visual Stdio 2013. Please let me know what i am missing

**Comment by redboltz** [comment]
Here is the build result of VS 2013.
https://ci.appveyor.com/project/redboltz/msgpack-c/branch/master/job/qy368d2pu3804wa4

It's successfully finished.

msgpack-c defines int8_t conditionally as follows:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h#L22

**Comment by redboltz** [comment]
I close the issue because no further comments after my comment.
Feel free to re-open if you have more questions.
