### ISSUE TITLE
Check type?

### ISSUE THREAD

**Issue by Ironholds** [msgpack/msgpack-c#566]
I'm afraid I can't find this in the documentation - in the event that I have a serialised messagepack object I wish to unpack and do not know the type in advance, how do I go about determining the type most easily?

**Comment by redboltz** [comment]
@Ironholds , let me clarify your question.

I think that you have already had an unpacked `msgpack::object`. But you don't know its type, so you cannot *convert* to a C++ object from `msgpack::object`.
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_object#conversion

You can get the type of `msgpack::object` using `type` member variable.
See http://melpon.org/wandbox/permlink/mNrG0bg487h8MpyM

It was not well documented, so I updated the wiki.
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_object

**Comment by Ironholds** [comment]
Great; thanks!

**Comment by redboltz** [comment]
I close the issue. You you have more questions or comments about the issue, feel free to reopen it.
