### ISSUE TITLE
Better support for str/bin discrepancy

### ISSUE THREAD

**Issue by drewcrawford** [msgpack/msgpack-c#57]
The new [spec](https://github.com/msgpack/msgpack/blob/master/spec.md) introduces some new types for str/bin.  Support for these types can be improved.

* There should be some way from the C API to deliberately emit a str vs a bin type.  Currently the only pack function in userspace is msg_pack_raw, which as best as I can tell always emits str.
* There should be some way to detect whether a `msgpack_object` was decoded from a str or a bin type.  Currently both str and bin formats get decoded to an object with `object.type==MSGPACK_OBJECT_RAW`.

The first problem is simple enough.  As to the second problem, the decode logic seems be buried in macro hell, and I'm not really confident enough that I understand the existing flow to make an attempt.

This bug is important enough that in the absence of a simple solution I will end up writing a new library in the target language.

**Comment by GatorMao** [comment]
If I want to take out the C version source code from message pack library, and only leave C++ version. What should I do ?

**Comment by redboltz** [comment]
Unfortunately, there is no direct way to do that.

msgpack of the C++  is header only library. C++ headers have extension typically '.hpp'.
So, I can list hpp files up as follows:

```
cd msgpack-c
find . -name "*.hpp"
```

However, some header files that have extension '.h' is included from '.hpp' files. To find that files, do as follows:

```
g++ -MM -std=c++11 -Ipath_to_msgpakc-c find.cpp
```

find.cpp includes the headers that are found by find command above.

As the result of that, I got the following list:

./include/msgpack/vrefbuffer.hpp
./include/msgpack/object_fwd.hpp
./include/msgpack/detail/cpp03_zone.hpp
./include/msgpack/detail/cpp11_zone.hpp
./include/msgpack/fbuffer.hpp
./include/msgpack/unpack.hpp
./include/msgpack/pack.hpp
./include/msgpack/adaptor/set.hpp
./include/msgpack/adaptor/raw.hpp
./include/msgpack/adaptor/detail/cpp03_msgpack_tuple_fwd.hpp
./include/msgpack/adaptor/detail/cpp11_msgpack_tuple.hpp
./include/msgpack/adaptor/detail/cpp11_msgpack_tuple_fwd.hpp
./include/msgpack/adaptor/detail/cpp11_define.hpp
./include/msgpack/adaptor/detail/cpp03_define.hpp
./include/msgpack/adaptor/detail/cpp03_msgpack_tuple.hpp
./include/msgpack/adaptor/fixint.hpp
./include/msgpack/adaptor/string.hpp
./include/msgpack/adaptor/set_fwd.hpp
./include/msgpack/adaptor/vector_bool.hpp
./include/msgpack/adaptor/define.hpp
./include/msgpack/adaptor/vector.hpp
./include/msgpack/adaptor/bool_fwd.hpp
./include/msgpack/adaptor/cpp11/tuple.hpp
./include/msgpack/adaptor/cpp11/array_fwd.hpp
./include/msgpack/adaptor/cpp11/forward_list_fwd.hpp
./include/msgpack/adaptor/cpp11/array_char.hpp
./include/msgpack/adaptor/cpp11/unordered_map.hpp
./include/msgpack/adaptor/cpp11/forward_list.hpp
./include/msgpack/adaptor/cpp11/unordered_set_fwd.hpp
./include/msgpack/adaptor/cpp11/tuple_fwd.hpp
./include/msgpack/adaptor/cpp11/array.hpp
./include/msgpack/adaptor/cpp11/unordered_map_fwd.hpp
./include/msgpack/adaptor/cpp11/unordered_set.hpp
./include/msgpack/adaptor/cpp11/array_char_fwd.hpp
./include/msgpack/adaptor/vector_char.hpp
./include/msgpack/adaptor/vector_fwd.hpp
./include/msgpack/adaptor/msgpack_tuple_fwd.hpp
./include/msgpack/adaptor/deque_fwd.hpp
./include/msgpack/adaptor/string_fwd.hpp
./include/msgpack/adaptor/list.hpp
./include/msgpack/adaptor/float.hpp
./include/msgpack/adaptor/pair_fwd.hpp
./include/msgpack/adaptor/float_fwd.hpp
./include/msgpack/adaptor/int.hpp
./include/msgpack/adaptor/deque.hpp
./include/msgpack/adaptor/vector_char_fwd.hpp
./include/msgpack/adaptor/int_fwd.hpp
./include/msgpack/adaptor/fixint_fwd.hpp
./include/msgpack/adaptor/map.hpp
./include/msgpack/adaptor/nil_fwd.hpp
./include/msgpack/adaptor/char_ptr_fwd.hpp
./include/msgpack/adaptor/list_fwd.hpp
./include/msgpack/adaptor/map_fwd.hpp
./include/msgpack/adaptor/pair.hpp
./include/msgpack/adaptor/msgpack_tuple.hpp
./include/msgpack/adaptor/bool.hpp
./include/msgpack/adaptor/nil.hpp
./include/msgpack/adaptor/char_ptr.hpp
./include/msgpack/adaptor/tr1/unordered_map.hpp
./include/msgpack/adaptor/tr1/unordered_set_fwd.hpp
./include/msgpack/adaptor/tr1/unordered_map_fwd.hpp
./include/msgpack/adaptor/tr1/unordered_set.hpp
./include/msgpack/adaptor/vector_bool_fwd.hpp
./include/msgpack/adaptor/raw_fwd.hpp
./include/msgpack/sbuffer.hpp
./include/msgpack/type.hpp
./include/msgpack/zone.hpp
./include/msgpack/versioning.hpp
./include/msgpack/zbuffer.hpp
./include/msgpack/cpp_config.hpp
./include/msgpack/object.hpp
./include/msgpack/version.hpp
./include/msgpack.hpp
./include/msgpack_fwd.hpp
./src/gcc_atomic.hpp

include/msgpack/detail/cpp11_zone.hpp include/msgpack/object.h \
include/msgpack/zone.h include/msgpack/sysdep.h \
include/msgpack/unpack_define.h include/msgpack/sysdep.h \
include/msgpack/version.hpp include/msgpack/version_master.h \

I'm not sure about ./src/gcc_atomic.hpp. According to that comment in the file, it is a workaround for  old gcc.

I believe that the files all you need to copy are the list above.

**Comment by GatorMao** [comment]
Hi, I am testing with 65536 bytes of data, which should be the new bin32 data type. The write side is ok. But when I read them back from database, I always get "msgpack::v1::insufficient_bytes" error from message pack library. Anyone has any idea about this problem ? I debug the back end service, there is no error come from there. I believe it is just message pack library's error message.

**Comment by nobu-k** [comment]
The new version will finally be released soon.
