### ISSUE TITLE
Error decoding msgpack file

### ISSUE THREAD

**Issue by edsiper** [msgpack/msgpack-c#571]
I have a msgpack file that when decoded with msgpack-c it get some weird decoded data.

- msgpack file [download](http://edsiper.linuxchile.cl/forward.dat)

When decoding I get this output:

```
["docker.61aef28b876e", 1488601623, {"container_id"=>"61aef28b876e6d022419335ac2eee260de90523bcc64b44264a61e2feacaca4d", "container_name"=>"/prickly_sammet", "source"=>"stdout", "lo"}, nil]t
```

expectation is:

```
["docker.61aef28b876e", 1488601623, {"container_id"=>"61aef28b876e6d022419335ac2eee260de90523bcc64b44264a61e2feacaca4d", "container_name"=>"/prickly_sammet", "source"=>"stdout", "log": "test\n"}, nil]
```

Decoding with other tools I get the data successfully. Any hints are appreciated.

**Comment by redboltz** [comment]
Could you post the code that reproduces the bad output?

**Comment by edsiper** [comment]
the problem is that code is generated by Docker logging driver. Despite the msgpack data have some weird schema [int, map, nil], int, nil, int, is totally valid.

**Comment by redboltz** [comment]
So what?

Where is the code that reads `forward.dat` and creates the outputs `["docker.61aef28b876e", 1488601623, {"container_id"=>"61aef28b876e6d022419335ac2eee260de90523bcc64b44264a61e2feacaca4d", "container_name"=>"/prickly_sammet", "source"=>"stdout", "lo"}, nil]t
` ?

**Comment by edsiper** [comment]
here is the code snippet, it's a modified version of lib_buffer_unpack.c:

```C
#include <msgpack.h>
#include <stdio.h>
#include <assert.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

typedef struct receiver {
    msgpack_sbuffer sbuf;
    size_t rest;
} receiver;

void receiver_init(receiver *r) {
  int fd;
  int ret;
  msgpack_packer pk;
  struct stat st;
  char *buf;

    msgpack_sbuffer_init(&r->sbuf);
    msgpack_packer_init(&pk, &r->sbuf, msgpack_sbuffer_write);

    fd = open("./forward.dat", O_RDONLY);
    fstat(fd, &st);

    buf = malloc(1024);
    ret = read(fd, buf, st.st_size);
    if (ret == -1) {
      exit(1);
    }


    r->sbuf.data = buf;
    r->sbuf.size = st.st_size;
    r->rest = st.st_size;
}

size_t receiver_recv(receiver *r, char* buf, size_t try_size) {
    size_t off = r->sbuf.size - r->rest;

    size_t actual_size = try_size;
    if (actual_size > r->rest) actual_size = r->rest;

    memcpy(buf, r->sbuf.data + off, actual_size);
    r->rest -= actual_size;

    return actual_size;
}

size_t receiver_to_unpacker(receiver* r, size_t request_size,
        msgpack_unpacker *unpacker)
{
    size_t recv_len;
    // make sure there's enough room, or expand the unpacker accordingly
    if (msgpack_unpacker_buffer_capacity(unpacker) < request_size) {
        msgpack_unpacker_reserve_buffer(unpacker, request_size);
        assert(msgpack_unpacker_buffer_capacity(unpacker) >= request_size);
    }
    recv_len = receiver_recv(r, msgpack_unpacker_buffer(unpacker),
                             request_size);
    msgpack_unpacker_buffer_consumed(unpacker, recv_len);
    return recv_len;
}

#define EACH_RECV_SIZE 4

void unpack(receiver* r) {
    /* buf is allocated by unpacker. */
    msgpack_unpacker* unp = msgpack_unpacker_new(100);
    msgpack_unpacked result;
    msgpack_unpack_return ret;
    size_t recv_len;
    int recv_count = 0;
    int i = 0;

    msgpack_unpacked_init(&result);
    while (true) {
        recv_len = receiver_to_unpacker(r, EACH_RECV_SIZE, unp);
        if (recv_len == 0) break; // (reached end of input)
#if defined(_MSC_VER) || defined(__MINGW32__)
        printf("receive count: %d %Id bytes received.\n", recv_count++, recv_len);
#else // defined(_MSC_VER) || defined(__MINGW32__)
        printf("receive count: %d %zd bytes received.\n", recv_count++, recv_len);
#endif // defined(_MSC_VER) || defined(__MINGW32__)
        ret = msgpack_unpacker_next(unp, &result);
        while (ret == MSGPACK_UNPACK_SUCCESS) {
            msgpack_object obj = result.data;

            /* Use obj. */
            printf("Object no %d:\n", ++i);
            msgpack_object_print(stdout, obj);
            printf("\n");
            /* If you want to allocate something on the zone, you can use zone. */
            /* msgpack_zone* zone = result.zone; */
            /* The lifetime of the obj and the zone,  */

            ret = msgpack_unpacker_next(unp, &result);
        }
        if (ret == MSGPACK_UNPACK_PARSE_ERROR) {
            printf("The data in the buf is invalid format.\n");
            msgpack_unpacked_destroy(&result);
            return;
        }
    }
    msgpack_unpacked_destroy(&result);
    msgpack_unpacker_free(unp);
}

int main(void) {
    receiver r;
    receiver_init(&r);

    unpack(&r);

    return 0;
}
```

**Comment by redboltz** [comment]
I compiled and executed the code you post.
Then I got the object print result on the last line:

`"}, nil].61aef28b876e", 1488601623, {"container_id"=>"61aef28b876e6d022419335ac2eee260de90523bcc64b44264a61e2feacaca4d", "container_name"=>"/prickly_sammet", "source"=>"stdout", "log"=>"test`

It's slightly different from you mentiond bofore as follows:
`["docker.61aef28b876e", 1488601623, {"container_id"=>"61aef28b876e6d022419335ac2eee260de90523bcc64b44264a61e2feacaca4d", "container_name"=>"/prickly_sammet", "source"=>"stdout", "lo"}, nil]t
`

Which is the correct behavior you observed?

By the way, please wrote *minimal and complete* code when you report the issue.

For example, in this case:

```c
#include <msgpack.h>
#include <stdio.h>

/* pass a filename as the argument */
int main(int argc, char** argv)
{
    if (argc != 2) return -1;
    {
        msgpack_zone mempool;
        msgpack_object deserialized;
        size_t size;
        char* fcontent;
        FILE* fp = fopen(argv[1], "rb");
        if (!fp) return -1;
        fseek(fp, 0, SEEK_END);
        size = ftell(fp);
        fseek(fp, 0, SEEK_SET);
        fcontent = malloc(size);
        if (!fcontent) return -1;
        fread(fcontent, 1, size, fp);

        msgpack_zone_init(&mempool, 2048);

        msgpack_unpack(fcontent, size, NULL, &mempool, &deserialized);

        /* print the deserialized object. */
        msgpack_object_print(stdout, deserialized);
        puts("");

        msgpack_zone_destroy(&mempool);
        free(fcontent);
    }
    return 0;
}
```

I got the same result I observed.

**Comment by edsiper** [comment]
thanks for the update.

I placed a fresh msgpack-c in opt and compiled your test case and I still can reproduce the problem:

```
$ ./test ./forward.dat 
["docker.61aef28b876e", 1488601623, {"container_id"=>"61aef28b876e6d022419335ac2eee260de90523bcc64b44264a61e2feacaca4d", "container_name"=>"/prickly_sammet", "source"=>"stdout", "lo"}, nil]t
```

I am running in Linux here, is there any extra information I can provide to help you to reproduce ?, definitely I cannot get what can be causing the problem

**Comment by redboltz** [comment]
@edsiper, I can't reproduce your situation. But I understand that why my output happens by my code.

My out put is here:

`"}, nil].61aef28b876e", 1488601623, {"container_id"=>"61aef28b876e6d022419335ac2eee260de90523bcc64b44264a61e2feacaca4d", "container_name"=>"/prickly_sammet", "source"=>"stdout", "log"=>"test`

forward.dat contains `\r` escape code. msgpack-c's `msgpack_object_print` invokes the `\r`. So, cursor position is returned from the beginning of the line. As the result of that, `"}, nil]` overwrites the beginning of the line.

It's worth trying that removing escape code like `\r` from forward.dat.
You can also check msgpack_object using debugger, not depends on `msgpack_object_print`.

By the way, the C++ part of msgpack-c's stream output operator '<<' creates JSON object. `\r` is escaped instead of invoked. It is different from `msgpack_object_print`.

**Comment by edsiper** [comment]
Sorry for the noise on this, I cannot believe I did not looked that the \r that was messing my stdout. 

thanks for catching that and my apologizes again.
