### ISSUE TITLE
Questions on msgpack::sbuffer (memory management)?

### ISSUE THREAD

**Issue by Code-ReaQtor** [msgpack/msgpack-c#576]
Hi,

Just a few questions about msgpack::packer usage.

- Does msgpack::sbuffer's memory is automatically cleared when it goes out of scope? or .clear() call required since it uses [malloc, free and realloc internally](https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_packer#sbuffer)? (
```c++
void process() {
    msgpack::sbuffer buffer;
    msgpack::packer<msgpack::sbuffer> packer(&buffer);
    // packing and writing here
    buffer.clear();  // <---- required? not included in the basic examples
}
```

- Is it better to reuse msgpack::sbuffer (global) instead of declaring a new one?
- Are there faster alternatives to msgpack::sbuffer?

**Comment by redboltz** [comment]
> Does msgpack::sbuffer's memory is automatically cleared when it goes out of scope? 

Yes. Here is the implementation:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/sbuffer.hpp#L38

> Is it better to reuse msgpack::sbuffer (global) instead of declaring a new one?

msgpack::sbuffer::clear() is just move the internal writing pointer to the beginning of the internal buffer.
See
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/sbuffer.hpp#L102

It depends on situation. 
 * If you create/destroy msgpack::sbuffer, malloc and free are called. Memory usage is efficient but speed is slow.
 * If you use global msgpack::sbuffer in multi-threading environment, you need to lock it.

> Are there faster alternatives to msgpack::sbuffer?

msgpack::vrefbuffer could minimize copy operation.
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_packer#vrefbuffer

msgpack::zbuffer can compress using zlib. It requires computing power but data size could be small. You need to decompress when you receive it.

msgpack's buffer concept is quite simple. See
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_packer#buffer

You can define your own buffer.

**Comment by Code-ReaQtor** [comment]
Thanks a lot for the answers.

Cheers!
