### ISSUE TITLE
Incorrect visitor parsing

### ISSUE THREAD

**Issue by alex3d** [msgpack/msgpack-c#584]
It seems that `parser` interface broken when stream contains more than one object and contains strings.
Strange behavior can be verified with slightly modified `example/cpp11/socket_stream_example.cpp`:
```
    std::string vvi1 = "a";
    std::string vvi2 = "bcdef";
    //std::map<std::string,std::string> vvi1 { {"a","b"}  };
    //std::map<std::string,std::string> vvi2 { {"c","d"}  };
``

Expected output:
"a"
"bcdef"

Output:
"a"
"�"
"b"
"c"
"d"
"e"
"f"

**Comment by redboltz** [comment]
@alex3d , thank you for reporting the issue. I sent the PR to fix the issue as #585.
Could you try this?

**Comment by alex3d** [comment]
I can confirm that issue fixed.

**Comment by redboltz** [comment]
Thank you for the confirmation. I merged the PR.
