### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jamessan** [msgpack/msgpack-c#594]
Now that GCC 7 has been released, more people are starting to run into build problems that have been fixed<sup>[1], [2], [3]</sup> due to the extra warnings GCC 7 emits.

Is there anything remaining that needs to be addressed before a new release?

[1]: https://github.com/msgpack/msgpack-c/commit/304ff96d04599401172568d042723ff507e78cc3
[2]: https://github.com/msgpack/msgpack-c/commit/15d8bb6792c9639d85a9ffe2ac81431f1b986c21
[3]: https://github.com/msgpack/msgpack-c/commit/e90231c865d2ba473b2cf75a1a15e3552141195c

**Comment by redboltz** [comment]
@jamessan , thank you for the comment. 

> Is there anything remaining that needs to be addressed before a new release?

#589 is still working. But it doesn't prevent the next release, so I start preparing the next release.

**Comment by redboltz** [comment]
I released 2.1.2. However, #598 is reported after the release. The issue is also gcc7 warnings.
I will release 2.1.3 including the fix for #598.

**Comment by pjrt** [comment]
So has this been solved now?

**Comment by redboltz** [comment]
I think that gcc 7.1 warning problems are all fixed, but only #600 is not confirmed.
The warning doesn't happen on my environment. I've tested on the following environment.

```
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 7.1.1 20170528 (GCC)
```

**Comment by redboltz** [comment]
Thanks to @zorun cooperation, all gcc warnings are fixed and confirmed.
I will release 2.1.3 soon.

**Comment by redboltz** [comment]
2.1.3 has been released.

**Comment by jamessan** [comment]
Thanks!

**Comment by wdcurry** [comment]
circular: fastlane install fails via gem due to permissions, and while it installs via brew, the init fails due to hardcoded: "clang: warning: no such sysroot directory: '/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'" path to old xcode app.
