### ISSUE TITLE
2.1.2 release tarball doesn't build

### ISSUE THREAD

**Issue by ilovezfs** [msgpack/msgpack-c#596]
The build fails with https://github.com/msgpack/msgpack-c/releases/download/cpp-2.1.2/msgpack-2.1.2.tar.gz

```
CMake Error: File /tmp/msgpack-20170606-77729-6jc5e1/msgpack-2.1.2/msgpack-config.cmake.in does not exist.
CMake Error at /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/CMakePackageConfigHelpers.cmake:312 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:350 (CONFIGURE_PACKAGE_CONFIG_FILE)
```
Building directly from the tag does work, though.

See https://github.com/Homebrew/homebrew-core/pull/14329

**Comment by redboltz** [comment]
@ilovezfs , thank you for reporting the issue.
msgpack-config.cmake.in should be included in the tar ball.
I will update tar ball soon.

**Comment by ilovezfs** [comment]
@redboltz thanks!

**Comment by redboltz** [comment]
I just updated the tar ball, could you double check it?

**Comment by ilovezfs** [comment]
@redboltz looks good now: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2613/
