### ISSUE TITLE
msgpack::object.type is different before and after pack/unpack for float32.

### ISSUE THREAD

**Issue by NorioKobota** [msgpack/msgpack-c#612]
It is related to https://github.com/msgpack/msgpack-c/issues/521 , msgpack::object.type indicates different value before and after pack/unpack.

sample code: https://wandbox.org/permlink/8GpoccaSxMvNBmeB

Is this spec.?

**Comment by redboltz** [comment]
@NorioKobota , thank you for reporting the issue. It seems to be a bug. I sent #613 to fix the issue. Could you check it?

**Comment by NorioKobota** [comment]
Thanks, but could you support implicit type conversion like below?

>  msgpack::object actual = oh.get(); // float32
>  double d = actual;

**Comment by redboltz** [comment]
msgpack-c doesn't support implicit conversion from msgpack::object.
You can use `msgpack::object::as<T>` member function as follows:

```cpp
msgpack::object actual = oh.get(); // float32
double d = actual.as<double>();
auto d2 = actual.as<double>();
```

**Comment by NorioKobota** [comment]
Ah, that's right. I remember it.
Thanks.

**Comment by redboltz** [comment]
Merged. Thanks.
