### ISSUE TITLE
Deserialize a msgpack object from binary file fail

### ISSUE THREAD

**Issue by thanhtam92** [msgpack/msgpack-c#614]
I have a class in C++, then unpack to msgpack::object and save this object to a binary file use std::ofstream::write (fo)

Problem is why then i read file in binary mode, use std::ifstream::read and cast to msgpack::object, succes if at the same time call write then read in a main, otherwise, fail if only read exist file, alway is segment falt error when try print msgpack::object

How can I fix this ?

    class old_class {
    public:
         old_class() : value("default old class"), exist(true) { }

         std::string value;
         bool exist;

        MSGPACK_DEFINE_MAP(value, exist);
    };

    int main(void)
    {
         old_class oc;

        std::stringstream sbuf;
        msgpack::pack(sbuf, oc);

        msgpack::unpacked result;
        msgpack::unpack(result, sbuf.str().data(), sbuf.str().size());
        msgpack::object obj = result.get();

        std::cout << obj << std::endl;

       #if 1  // only once run to create ./file.bin, then set 0
        ofstream fo("./file.bin", ios::binary | ios::out);
        fo.write((char*)&obj, sizeof(obj));
        fo.close();
      #endif
       cout<<"read:...."<<endl;

       msgpack::object reobj;
       ifstream fi("./file.bin", ios::binary | ios::in);
       if(!if.is_open()) return 0;

       fi.read((char*)&reobj, sizeof(msgpack::object));
       fi.close();

       if(reobj.is_nil()){
            cout<<"=========object is nill()"<<endl;
        }
        std::cout << reobj << std::endl; // <== err segment falt when run time
     }

**Comment by redboltz** [comment]
`msgpack::object` is not mapped as continuous memory. So the code doesn't work. See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_object
I think that the case the code works as you expected by accident. 

If you want to write/read msgpack object to/from a file, do as follows:

```cpp
#include <msgpack.hpp>
#include <sstream>
#include <iostream>
#include <fstream>

class old_class {
public:
     old_class() : value("default old class"), exist(true) { }

     std::string value;
     bool exist;

    MSGPACK_DEFINE_MAP(value, exist);
};

int main(void)
{
    old_class oc;

    std::ofstream fo("./file.bin", std::ios::binary | std::ios::out);
    msgpack::pack(fo, oc);
    fo.close();

    std::cout << "read:...." << std::endl;

    std::ifstream fi("./file.bin", std::ios::binary | std::ios::in);
    if (!fi.is_open()) return 0;

    std::string content( (std::istreambuf_iterator<char>(fi) ),
                         (std::istreambuf_iterator<char>()   ) );
    fi.close();

    msgpack::object_handle oh = msgpack::unpack(content.data(), content.size());
    msgpack::object reobj = oh.get();
    if (reobj.is_nil()){
        std::cout<<"=========object is nill()"<<std::endl;
    }
    std::cout << reobj << std::endl; // <== err segment falt when run time
}
```

https://wandbox.org/permlink/KL71nLDkudfDjqzA

**Comment by thanhtam92** [comment]
Thanks, your sample is easy to understand, and resolved my problem in a few day ago.

> I think that the case the code works as you expected by accident.

I try to change a few internal member in class structure, it seem always works by this accidental. The interesting accidental ! I think need research more to feedback to you again.

**Comment by redboltz** [comment]
> I try to change a few internal member in class structure, it seem always works by this accidental. The interesting accidental ! I think need research more to feedback to you again.

```cpp
#include <msgpack.hpp>
#include <iostream>
#include <fstream>
#include <sstream>

using namespace std;

class old_class {
public:
     old_class() : value("default old class"), exist(true) { }

     std::string value;
     bool exist;

    MSGPACK_DEFINE_MAP(value, exist);
};

int main(void)
{
     old_class oc;

    std::stringstream sbuf;
    msgpack::pack(sbuf, oc);

    msgpack::unpacked result;
    msgpack::unpack(result, sbuf.str().data(), sbuf.str().size());
    msgpack::object obj = result.get();

    std::cout << obj << std::endl;
    
    std::cout << "address of obj " << &obj << std::endl;
    std::cout << "address of obj.via.map.ptr " << obj.via.map.ptr << std::endl;

    
   #if 1  // only once run to create ./file.bin, then set 0
    ofstream fo("./file.bin", ios::binary | ios::out);
    fo.write((char*)&obj, sizeof(obj));
    fo.close();
  #endif
   cout<<"read:...."<<endl;

   // Overwrite the length of string. "default old class" => "def"
   obj.via.map.ptr[0].val.via.str.size = 3;
    
   msgpack::object reobj;
    
    
   ifstream fi("./file.bin", ios::binary | ios::in);
   if(!fi.is_open()) return 0;

   fi.read((char*)&reobj, sizeof(msgpack::object));
   fi.close();

   if(reobj.is_nil()){
        cout<<"=========object is nill()"<<endl;
    }
    std::cout << reobj << std::endl; // <== err segment falt when run time
    std::cout << "address of reobj " << &reobj << std::endl;
    std::cout << "address of reobj.via.map.ptr " << reobj.via.map.ptr << std::endl;
 }
```

https://wandbox.org/permlink/kKA37DLFLPKWed71

I added the following lines to analyze the behavior:

```cpp
   // Overwrite the length of string. "default old class" => "def"
   obj.via.map.ptr[0].val.via.str.size = 3;
```

In addition, I added the debug print for msgpack::object internal addresses.

Then I got the following result:

```
{"value":"default old class", "exist":true}
address of obj 0x7ffe3cd01f20
address of obj.via.map.ptr 0x1322ae8
read:....
{"value":"def", "exist":true}
address of reobj 0x7ffe3cd01dc0
address of reobj.via.map.ptr 0x1322ae8
```

"default old class" is changed to "def" because of the size is updated to 3.

The following two addresses are the same.

address of obj.via.map.ptr 0x1322ae8
address of reobj.via.map.ptr 0x1322ae8

The first address could change on every allocation. And the address is stored to the file. Then the same address is read from the file. If you omit storing process, reobj.via.map.ptr points to the address created by the previous execution. That's the reason of the behavior.
