### ISSUE TITLE
msgpack 2.1.4 checksum mismatch

### ISSUE THREAD

**Issue by ilovezfs** [msgpack/msgpack-c#623]
URL:
https://github.com/msgpack/msgpack-c/releases/download/2.1.4/msgpack-2.1.4.tar.gz

Expected SHA-256: ed94b4eaaa5aaed13e939b775eaddc1cd40937abfbd0de40bad8641e2e95b3da

Actual SHA-256:
1d9d9ec4769cbdee2708151e0784165caec4610068f6c85208ba0491ce308a90

The expected checksum is what what we had in Homebrew for the SHA-256 when the formula was upgraded to version 2.1.4 on Thu Aug 3 11:00:35 2017 -0700. See https://github.com/Homebrew/homebrew-core/pull/16371.

But currently downloading the file gives a different checksum.

I wanted to make sure you weren't hacked, and ask what the reason(s) for the changes were.

**Comment by herrbischoff** [comment]
Same here:

```
==> Upgrading 1 outdated package, with result:
msgpack 2.1.4
==> Upgrading msgpack
==> Using the sandbox
==> Downloading https://github.com/msgpack/msgpack-c/releases/download/2.1.4/msgpack-2.1.4.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/4879511/5b2b6612-78e5-11e7-9bb9-5f3ea218954b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credenti
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: ed94b4eaaa5aaed13e939b775eaddc1cd40937abfbd0de40bad8641e2e95b3da
Actual: 1d9d9ec4769cbdee2708151e0784165caec4610068f6c85208ba0491ce308a90
Archive: /Users/mbischoff/Library/Caches/Homebrew/msgpack-2.1.4.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by redboltz** [comment]
@ilovezfs , thank you for reporting the issue.

Sorry for the mix up.

There are some mistakes.

1. I use https://github.com/msgpack/msgpack-c/blob/master/makedist.sh to create tarball, the script expects in clean directory (e.g. just after git -xdf), but I use it in not clean directory.
2. I forgot cheking the checkbox 'this is a pre release' when I release first. And then, I noticed that I forgot updating https://github.com/msgpack/msgpack-c/commit/7c671093965d0182617b36485782db4a88f634cb and I delete tag cpp-2.1.4 and add cpp-2.1.4 with the commit and push it with `--force` option.
3. I updated tarball.

The tarball is not hacked but still incomplete. I don't know much about brew mechanism. I will fix it.
I think that I shouldn't update tarball as 2.1.4 release, it will increase the confusion.
So, I will release 2.1.5 with the appropriate tarball and remove 2.1.4 release.

What do you think?

**Comment by ilovezfs** [comment]
@herrbischoff thanks for the quick response. Yes, a new tag is always preferable to rewriting public history, so 2.1.5 would be perfect.

**Comment by redboltz** [comment]
I removed release 2.1.4 and drafted release 2.1.5.
See https://github.com/msgpack/msgpack-c/releases

**Comment by ilovezfs** [comment]
@redboltz thanks! https://github.com/Homebrew/homebrew-core/pull/16410

**Comment by ilovezfs** [comment]
I've merged https://github.com/Homebrew/homebrew-core/pull/16410 so this should no longer be an issue.

Thanks @redboltz

**Comment by herrbischoff** [comment]
Thanks. However, I now get the following error:

```
==> Upgrading msgpack
==> Using the sandbox
==> Downloading https://github.com/msgpack/msgpack-c/releases/download/cpp-2.1.5/msgpack-2.1.5.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/4879511/03fd264a-7977-11e7-8324-3597719ba6fc?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credenti
######################################################################## 100.0%
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/Users/mbischoff/homebrew/Cellar/msgpack/2.1.5 -DCMAKE_BUILD_TYPE=Release
==> make install
Last 15 lines from /Users/mbischoff/Library/Logs/Homebrew/msgpack/02.make:
[ 54%] Built target simple
[ 54%] Built target reuse_zone
[ 57%] Linking CXX executable protocol_new
cd /tmp/msgpack-20170804-54549-cvj8l9/msgpack-2.1.5/example/cpp03 && /Users/mbischoff/homebrew/Cellar/cmake/3.9.0/bin/cmake -E cmake_link_script CMakeFiles/protocol_new.dir/link.txt --verbose=1
/Users/mbischoff/homebrew/Library/Homebrew/shims/super/clang++  -DMSGPACK_DEFAULT_API_VERSION=2 -std=c++98  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/protocol_new.dir/protocol_new.cpp.o  -o protocol_new
[ 57%] Built target protocol_new
[ 59%] Linking CXX executable map_based_versionup
cd /tmp/msgpack-20170804-54549-cvj8l9/msgpack-2.1.5/example/cpp03 && /Users/mbischoff/homebrew/Cellar/cmake/3.9.0/bin/cmake -E cmake_link_script CMakeFiles/map_based_versionup.dir/link.txt --verbose=1
/Users/mbischoff/homebrew/Library/Homebrew/shims/super/clang++  -DMSGPACK_DEFAULT_API_VERSION=2 -std=c++98  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/map_based_versionup.dir/map_based_versionup.cpp.o  -o map_based_versionup
[ 59%] Built target map_based_versionup
[ 61%] Linking CXX executable class_intrusive
cd /tmp/msgpack-20170804-54549-cvj8l9/msgpack-2.1.5/example/cpp03 && /Users/mbischoff/homebrew/Cellar/cmake/3.9.0/bin/cmake -E cmake_link_script CMakeFiles/class_intrusive.dir/link.txt --verbose=1
/Users/mbischoff/homebrew/Library/Homebrew/shims/super/clang++  -DMSGPACK_DEFAULT_API_VERSION=2 -std=c++98  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/class_intrusive.dir/class_intrusive.cpp.o  -o class_intrusive
[ 61%] Built target class_intrusive
make: *** [all] Error 2
```

**Comment by ilovezfs** [comment]
@herrbischoff why aren't you using the bottle?

**Comment by herrbischoff** [comment]
I'm averse to letting Homebrew take over `/usr/local`, which is just bad. But that's not the issue here. Shouldn't the build work anyway? It did before. If the formula was implemented correctly, there should be no need for using pre-compiled binaries.

**Comment by ilovezfs** [comment]
```
==> Summary
🍺  /Users/joe/brew/Cellar/msgpack/2.1.5: 670 files, 5.1MB, built in 12 seconds
iMac-TMP:brew joe$ brew test msgpack
Testing msgpack
==> Using the sandbox
==> /usr/bin/clang -o test test.c -L/Users/joe/brew/Cellar/msgpack/2.1.5/lib -lmsgpackc
iMac-TMP:brew joe$ 
```

So I guess the formula is implemented correctly ;)
