### ISSUE TITLE
Using msgpack::type::variant issues

### ISSUE THREAD

**Issue by traversc** [msgpack/msgpack-c#627]
Hi, I am reading this page here: https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_variant

When I try to initlialize a variant type, e.g.:

`std::multimap<msgpack::type::variant, msgpack::type::variant> omap;`

I get the following error:

> temp.cpp:23:17: error: ‘variant’ is not a member of ‘msgpack::v2::type’
>      std::vector<msgpack::type::variant omap;

I am trying to process a map that has unknown key types?

Thank you in advance.

**Comment by redboltz** [comment]
@traversc , you need to define `DMSGPACK_USE_BOOST` macro.
Here is an example: https://wandbox.org/permlink/J4EsG0DLlEs4ajWQ
In the example, the macro provides using compiler option. See the left text box.

I will update wiki document.

**Comment by traversc** [comment]
Thanks for your help.  

I put together a package for converting to and from R using the C++ API: https://github.com/traversc/msgpack2R

This has been really useful for one of my projects, thanks!

**Comment by redboltz** [comment]
You are welcome!
