### ISSUE TITLE
Parsed bytes offset not updated when visitor returns `false`

### ISSUE THREAD

**Issue by rcjmurillo** [msgpack/msgpack-c#637]
Hi, is there any particular reason of why the parsed bytes offset is not updated when the returned code is not `PARSE_SUCCESS` or `PARSE_CONTINUE`? That's the case when the visitor returns `false` from any of it's methods, I'm needing this for a particular case but I think it could also be pretty useful to know the offset if the visitor stops the parse process.

https://github.com/msgpack/msgpack-c/blob/b02c6beb4dfc28b9651ac78e583d2273aef679a7/include/msgpack/v2/parse.hpp#L1023-L1049

**Comment by redboltz** [comment]
Hi @rcjmurillo ,

> Hi, is there any particular reason of why the parsed bytes offset is not updated when the returned code is not PARSE_SUCCESS or PARSE_CONTINUE? 

It's simply "if an error happens, do not update" policy. 

> That's the case when the visitor returns false from any of it's methods, I'm needing this for a particular case but I think it could also be pretty useful to know the offset if the visitor stops the parse process.

Do you mean user can get the information where the error is occurred ?
I think so too.

Let me consider the original behavior.

If offset is NOT updated, and if the user get an error, the user doesn't have much options. At most one byte advance and retry :<
If the user don't want to update the offset, the user can make a copy of the offset before calling parse.

Hence, I think that always updating the offset is acceptable breaking change.

**Comment by redboltz** [comment]
@rcjmurillo , I've just implemented the feature.
Could you try #639?

Here is the test cases corresponding to visitor returns false:
https://github.com/msgpack/msgpack-c/pull/639/files#diff-9d56f20379e66ee4d732ea417b491431R143

**Comment by redboltz** [comment]
@rcjmurillo , does #639 work as you expected?

**Comment by redboltz** [comment]
merged.

**Comment by Asmod4n** [comment]
@redboltz This is a breaking change, please update the major version number.
These assumptions no longer work and are breaking chunked decoding.

https://github.com/Asmod4n/mruby-simplemsgpack/blob/a0c7b3fa7ef079e78a42d64627d95f0fbab0fc6e/test/msgpack.rb#L77
