### ISSUE TITLE
Xcode 9 "Possible misuse of comma operator" warnings. 

### ISSUE THREAD

**Issue by kennycarruthers** [msgpack/msgpack-c#640]
Xcode enabled the '-Wcomma' warning when doing builds and as a result numerous warnings are generated for msgpack-c when building within an Xcode 9 project. These are just warnings but I'm curious if there's any desire to address these as the fixes appear pretty straight forward. 

It looks to me that the warnings are really just a by-product of different coding styles used in different areas. In some cases, a single line is used with a comma whereas in other areas two lines are used. 

For example, this line causes a warning because of the use of a single line: [int.hpp@L85](https://github.com/msgpack/msgpack-c/blob/9513734040d9b7703e77a515a728625aa17c50d0/include/msgpack/v1/adaptor/int.hpp#L85)

But the function just above it uses two lines and doesn't cause a warning: [int.hpp@L70](https://github.com/msgpack/msgpack-c/blob/9513734040d9b7703e77a515a728625aa17c50d0/include/msgpack/v1/adaptor/int.hpp#L70)

It's not a high-priority issue, but it's also nice to minimize warnings if possible.

**Comment by redboltz** [comment]
Thank you for reporting the issue.
I fixed it.

**Comment by kennycarruthers** [comment]
Awesome. Thanks for the quick response and fix. Much appreciated.
