### ISSUE TITLE
Xcode 9 "Documentation" Warnings

### ISSUE THREAD

**Issue by kennycarruthers** [msgpack/msgpack-c#642]
Similar to issue #640... 

Xcode 9 has enabled the `-Wdocumentation` warning when doing static analysis. There are several areas in the msgpack-c code where the comments before a function appear to reference outdated function parameters. 

Warning: "Parameter 'referenced' not found in the function declaration"
Example: [unpack.hpp@L851](https://github.com/msgpack/msgpack-c/blob/db6d4f20030b00d71b904c70783ea2770b685e80/include/msgpack/v1/unpack.hpp#L851)

Warning: "Parameter 'f' not found in the function declaration"
Example: [parse.hpp@L625](https://github.com/msgpack/msgpack-c/blob/db6d4f20030b00d71b904c70783ea2770b685e80/include/msgpack/v2/parse.hpp#L625)

These are only warnings and don't affect the code at all, but they do show up as Issues when building with Xcode 9.

**Comment by redboltz** [comment]
Fixed.
