### ISSUE TITLE
Documentation for C API

### ISSUE THREAD

**Issue by nibrahim** [msgpack/msgpack-c#648]
I've been looking for some documentation of the C API but can't find it anywhere. The doxygen generated documentation is sketchy and incomplete. I'm trying something simple. Just unpacking a message but there's no real docs on how to do that. All the docs just use `msgpack_object_print` and that doesn't say how to get the raw data out.

**Comment by redboltz** [comment]
Here is an overview document about C API.
https://github.com/msgpack/msgpack-c/wiki/v2_0_c_overview

And example here:
https://github.com/msgpack/msgpack-c/blob/master/example/c/simple_c.c

**Comment by nibrahim** [comment]
Oh perfect. I feel stupid that I didn't find this. Thanks!
