### ISSUE TITLE
Autofac

### ISSUE THREAD

**Issue by dohouk** [msgpack/msgpack-c#649]
We are concerned this code will be used by Autofac putting our species at risk.

**Comment by redboltz** [comment]
Unfortunately, I can't understand what the issue is. Could you elaborate it?

**Comment by dohouk** [comment]
Recently a TV show (Phillip K. Dicks Electric Dreams, Season 1 episode 2, 'Autofac' from Amazon) displayed code from your library. I thought that was funny so I opened a ticket. Sorry for the confusion. Here is a screenshot. Thanks!
![electricdreams_01_02_autofac_22-35](https://user-images.githubusercontent.com/900546/35710502-cfb091ea-0785-11e8-872d-f726190c6f50.png)
