### ISSUE TITLE
Windows build is broken

### ISSUE THREAD

**Issue by jameswm** [msgpack/msgpack-c#65]
It is not possible to build this project as described according to the instructions below, which are found in the downloaded README as well as other msgpack-c sites:

"On Windows, open msgpack_vc8.vcproj or msgpack_vc2008 file and build it using batch build. DLLs are built on lib folder,
and the headers are built on include folder."

The build failure errors are to do with the fact that  1) the project does not have the correct include file path configured to find msgpack\sysdep.h or any other header file in that directory (easily fixed), and 2) many header files cannot be found because they are only available as ruby template files, with a .erb extension:

zone.hpp.erb
define.hpp.erb
tuple.hpp.erb

...these and other header files can apparently only be produced by running some preprocessing tool which is apparently not provided in the download.  These build errors cannot be resolved without a functional pre-processing tool.

In the absence of this tool, is it possible to generate the missing .hpp files and make them available for download?  Any other workaround?

This problem can be found in both the current snapshot of the source code, as well as 0.5.4, the version that is recommended to build the source from on Windows.

**Comment by nobu-k** [comment]
erb isn't required in the latest version :) Thank you.
