### ISSUE TITLE
Packing char with zone treated as int?

### ISSUE THREAD

**Issue by danpf** [msgpack/msgpack-c#652]
Hello,

I have a complex class that I'm trying to pack in a non-intrusive way, using a map, so it can be cross compatible with a python implementation that uses a dictionary.

packing code looks like:
```
// User defined class template specialization
namespace msgpack {
MSGPACK_API_VERSION_NAMESPACE(MSGPACK_DEFAULT_API_NS) {
namespace adaptor {

template <>
struct object_with_zone<MT> {
    void operator()(msgpack::object::with_zone& o, MT const& v) const {
        o.type = type::MAP;
        o.via.map.size = 2;
        o.via.map.ptr = static_cast<msgpack::object_kv*>(o.zone.allocate_align(sizeof(msgpack::object_kv)*8, MSGPACK_ZONE_ALIGNOF(msgpack::object_kv)));
        o.via.map.ptr[0].key = msgpack::object("name", o.zone);
        o.via.map.ptr[0].val = msgpack::object(v.name, o.zone);
        o.via.map.ptr[1].key = msgpack::object("somechar", o.zone);
        o.via.map.ptr[1].val = msgpack::object(v.somechar, o.zone);
}
}
}
```
I'm packing it with
```
    std::map<std::string,msgpack::object>dm;
    dm["x1"] = msgpack::object(mystruct, m_zone);
    msgpack::pack(ofs, data_map);
```
and when I iterate over my map after I write to file, and then read it back in
I'm getting a bad_cast error.

When I iterate over the map before I actually decode the inner objects I can print out the name and type and I see something like this 
```
iterate over map {
  std::cout << "k: " << key << " t: " << it->second->type <<  std::endl;
}
OUTPUT
k: "name" t: 5
k: "somechar" t: 2
```

So I checked my binaries and it looks like I'm packing things without a header byte somehow?
```
736f 6d65 6368 6172 47
somecharG
```
When I think I should be having 
```
736f 6d65 6368 6172 a147
somechar.G
```

Is there a step that I'm missing when I'm packing my objects with the zone?
So, I'm not against just packing my structs as std::maps with a wrapper function, but I'd rather do it this way.

**Comment by redboltz** [comment]
I'm not sure what is the point of the issue.
Could you post *complete and minimal* code that reproduces the issue?

**Comment by danpf** [comment]
How about this?
https://wandbox.org/permlink/XNVUKjnvxszQuqqb

I know a char is just an unsigned int, but the spec says:

https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor

that a char should be of msgpack::object::type::STR
the problem is that before a string there is the header bits:
`10100010` or `101XXXXX`
but since the char is not treated as a string, it doesn't have a header set of bits, and is packed directly after the dictionary name. 
 
```
00000000: 10000001 10100111 01101101 01111001 01100101 01101110  ..myen
00000006: 01110100 01110010 01111001 10000011 10100110 01101101  try..m
0000000c: 01111001 01101110 01100001 01101101 01100101 10100010  yname.
00000012: 01001010 01101111 10100101 01100010 01110101 01100010  Jo.bub
00000018: 01100010 01100001 11001010 01000010 11110110 10100100  ba.B..
0000001e: 11011101 10100100 01110000 01110010 01101111 01100010  ..prob
00000024: 01000011 00001010                                      C.
```

Does that make more sense?

**Comment by danpf** [comment]
Okay I just realized I'm dumb as was reading the spec completely wrong.

BUT I guess my question still stands... since python stores chars as strings how can I make my packed object treat chars as strings?  The problem here is the cross compatibility...

**Comment by danpf** [comment]
Ok I'm a goon.
I think the best way to solve this is just
`o.via.map.ptr[2].val = msgpack::object(std::string(v.prob, 1), o.zone);`
Does that sound right?

**Comment by redboltz** [comment]
Yes, it seems to work as you expected. It creates temporary `std::string` object. If you want to avoid it, and you are using C++17 or later, you can use `std::string_view` as follows:

```cpp
        o.via.map.ptr[2].val = msgpack::object(std::string_view(&v.prob, 1), o.zone);
```
https://wandbox.org/permlink/Zhdo2sLfLxYad3Lb


Or, you can replace `prob` type with aggregate type as follows:

```cpp
struct MyType {
  std::string myname;
  float bubba;
  char prob[1];
  signed int myint;
};
```

```cpp
    bud.prob[0] = 'C';
```

Updated whole code:
https://wandbox.org/permlink/dMJ3Rfj7mEBrW3rX

The key point is aggregate types of chars are mapped to STR, but char type is mapped to positive/negative integer.

**Comment by danpf** [comment]
Great, Thanks for your help!
