### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by HonglingM** [msgpack/msgpack-c#653]
Hello, I followed the steps for linux:
$ git clone https://github.com/msgpack/msgpack-c.git
$ cd msgpack-c
$ cmake .
$ make
$ sudo make install

My gcc version is 4.8.

but when I do:
$ gcc main.c -o main -lmsgpack
/usr/bin/ld : ne peut trouver -lmsgpack
collect2: error: ld returned 1 exit status

I'm sorry with the french language. It says that it can not find -lmsgpack.

**Comment by redboltz** [comment]
https://github.com/msgpack/msgpack-c/wiki/v2_0_c_overview

Could you try this?

```
 gcc main.c -o main -lmsgpackc
```

The library name is `msgpackc`.

**Comment by HonglingM** [comment]
I tried it, it works. 👍 
But when I tried: 
$ ./main 
./main: error while loading shared libraries: libmsgpackc.so.2: cannot open shared object file: No such file or directory

**Comment by redboltz** [comment]
Where is   `libmsgpackc.so.2` ?
You need to set LD_LIBRARY_PATH to the path.

**Comment by HonglingM** [comment]
Thanks a lot, it works now.

**Comment by redboltz** [comment]
You are welcome!
