### ISSUE TITLE
Outdated document

### ISSUE THREAD

**Issue by mango009** [msgpack/msgpack-c#654]
The following code is documented in the main page for the c++ exanple:
msgpack::object_handle oh = msgpack::unpack(str.data(), str.size());

However, this code does not compiled with the latest version 2.1.5 since msgpack::object_handle is not really there?

**Comment by redboltz** [comment]
It works for me on version 2.1.5.

```cpp
#include <msgpack.hpp>
#include <iostream>

int main() {
    std::string str { 0x01 };
    std::cout << MSGPACK_VERSION << std::endl;
    msgpack::object_handle oh = msgpack::unpack(str.data(), str.size());
    std::cout << oh.get() << std::endl;
}
```

Running Demo (latest master)
https://wandbox.org/permlink/pUzn5JIQU36l3QlS

Could you check include path order?

**Comment by mango009** [comment]
Apparently this problem is due to I was using apt-get install libmsgpack-dev on Ubuntu. And it installed a very stale version 0.5.7/.
