### ISSUE TITLE
Add examples on working with associative arrays

### ISSUE THREAD

**Issue by konsolebox** [msgpack/msgpack-c#665]
Hi,

Please consider adding examples on how to use it with key-value pair objects. I only see tuples and arrays. The header files associate with so many data types which are coming from different sources and it's not easy for everyone to have an idea of how to use them quickly.

**Comment by konsolebox** [comment]
I see a few examples in example/ that that uses map objects, but none shows a method generic enough that it can be used with storing and traversing objects which are officially compatible with JSON.  The website shows a direct conversion from `{"compact": true, "shema":0}` to `[82][A7]compact[C3][A6]schema[00]`, but I see nothing in the examples that explicitly does this kind of conversion. I only see use of different types of maps. Maybe it's done in C?

Browsing through the header files I saw `assoc_vector`. I thought it's the one I need since I write pre-C++11 compatible code. Yet now I still have to know how it can be detected during unpack.

I also thought `assoc_vector` is just yet another object, and may not directly store `{"compact": true, "shema":0}` as `[82][A7]compact[C3][A6]schema[00]`.

**Comment by redboltz** [comment]
@konsolebox , I don't understand what you want.

Here is class to MAP adaptor documents:
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#defining-custom-adaptors

And here is an example:
https://github.com/msgpack/msgpack-c/blob/master/example/cpp03/class_intrusive_map.cpp#L37

Or do you need something like https://wandbox.org/permlink/29EfJIKCCWnw4M7Q ?

**Comment by konsolebox** [comment]
@redboltz 

> Or do you need something like https://wandbox.org/permlink/29EfJIKCCWnw4M7Q ?

Thanks. That simple example is exactly what I needed. I hope you consider adding it in README.md so future viewers would have a quick basic idea on how maps are packed with msgpack. The examples in example/ show many ways on how it is done. Some use std::map with std::vector's as values, some use std::unordered_map. It can be confusing to beginners since they would think that both map classes may be serialized differently. They would have to understand how adaptors work first.

>  https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#defining-custom-adaptors

After reading that page and some other pages linked to it, I think I'm now getting a clearer picture on how msgpack serializes and stores data in a consistent manner that's convertible to JSON. I just need to examine a few more things including the adaptors.

Thanks a lot for the help.

**Comment by redboltz** [comment]
@konsolebox , now I understand what you want. So I started writing the tutorial https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_tutorial

Then I will add the link to tutorial on the top page (README.md).

**Comment by konsolebox** [comment]
Very nice!

**Comment by redboltz** [comment]
Tutorial is under construction but I think that this issue has been fixed. So I close it.
Feel free to reopen it.

**Comment by konsolebox** [comment]
Yes I'm good now, thanks again.
