### ISSUE TITLE
File not found : "msgpack/v3/cpp_config_decl.hpp"

### ISSUE THREAD

**Issue by pikxel** [msgpack/msgpack-c#667]
I downloaded and compiled the newest version, but when using it I get this error : 

/usr/local/include/msgpack/cpp_config_decl.hpp:15:42: fatal error: msgpack/v3/cpp_config_decl.hpp: file not found
 #include "msgpack/v3/cpp_config_decl.hpp"
                                          ^
compilation terminated.

**Comment by redboltz** [comment]
@pikxel , thank you for reporting the issue.
The file exists but seems not installed.
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v3/cpp_config_decl.hpp

I've also checked the problem on travis-ci log https://travis-ci.org/redboltz/msgpack-c/jobs/364170035#L2487

I start investigating.

**Comment by redboltz** [comment]
Should be fixed by #668 .
I added installed file checking script to .travis.yml to avoid the same problem in the future.

**Comment by redboltz** [comment]
merged. If you still have the problem, please reopen the issue.

**Comment by pikxel** [comment]
Thank you
