### ISSUE TITLE
OSS-Fuzz integration

### ISSUE THREAD

**Issue by derwolfe** [msgpack/msgpack-c#669]
Hi @redboltz!

I've been working on integrating msgpack-c with Google's [OSS-Fuzz](https://github.com/google/oss-fuzz). OSS-Fuzz is able to run any fuzzers we define, file bug reports with stacktraces, generate reproducing inputs, and provide coverage statistics. 

Does this sound interesting you? If so, I'd just need to have an email address of yours that satisfies the requirements detailed in https://github.com/google/oss-fuzz#accepting-new-projects.

Thanks for msgpack-c!
Chris

**Comment by derwolfe** [comment]
Awesome! I'll push up a PR to the OSS-Fuzz repo using that. Thanks :)

**Comment by redboltz** [comment]
@derwolfe , thank you for adding my account.
I successfully accessed OSS-Fuzz and got 2 reports, so far.

By the way, I'd like to add another msgpack-c committer nobu.k.jp@gmail.com to OSS-Fuzz.
I'm new to OSS-Fuzz, I couldn't find the way to add him by myself.
Could you help me?

**Comment by derwolfe** [comment]
Hi @redboltz :) No problem! I can add him to https://github.com/google/oss-fuzz/blob/master/projects/msgpack-c/project.yaml using a PR. He should the be able to access all bug reports/comment on bugs, et cetera. I'll make sure to CC both of you on the PR as well.
