### ISSUE TITLE
make build failure on c++11

### ISSUE THREAD

**Issue by ashishsb95** [msgpack/msgpack-c#679]
-DMSGPACK_CXX11=ON initiates the -std=c++14 fag causing ambiguous function calls in functions such as isinf(double&), isnan(double&) .
Explicitly using the namespace to be either ::isnan or std::isnan solves the issue

**Comment by redboltz** [comment]
@ashishsb95 , I've checked on the following compilers.
I don't get any compile errors. I've tested `-std=c++11`, `-std=c++14`, and `-std=c++17`.

Could you build on the brand-new (start from git clone) environment?
And could you check actual compiler flags using `make VERBOSE=1`?

clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

gcc (GCC) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
