### ISSUE TITLE
with msgpack-c, how can I serialize a group of objects which are aggregated to one object together?

### ISSUE THREAD

**Issue by viter-oliver** [msgpack/msgpack-c#691]
hello @redboltz 
I am working on an application, which requests serialization of a component, which contains other objects. all objects are an instance of  base_ui_component, here is the definition of base_ui_component:
class base_ui_component
{
	friend base_ui_component* find_a_uc_from_uc(base_ui_component& tar_ui, const char* uname);
protected:
	struct internal_property
	{
		char _name[name_len];
		struct{float x,y,z;} _pos;
		bool _visible;
		internal_property() :_visible(true){ memset(_name, 0, name_len); }
    };
	internal_property _in_p;
	vector<base_ui_component*> _vchilds;
	base_ui_component* _parent;
public:
	
	
	base_ui_component()
		:_in_p()
		, _parent(NULL)
	{

	}
	
	~base_ui_component()
	{
		for (auto& it:_vchilds)
		{
			delete it;
		}
	}
	void add_child(base_ui_component* pchild){ pchild->_parent = this; _vchilds.push_back(pchild); }
	void remove_child(base_ui_component* pchild)
	{
		auto it = find(_vchilds.begin(), _vchilds.end(), pchild);
		if (it!=_vchilds.end())
		{
			_vchilds.erase(it);
			delete pchild;
		}
	}
	base_ui_component* get_child(int index)
	{
		return _vchilds[index];
	}
};
I have studied all of the test cases of msgpack-c, and find that all object which can be serialized must be predefined, but in some circumstances, we can't precisely tell the struct of the object, so with msgpac-c, how can I serialize the object which is recursively aggregated by other objects?

**Comment by redboltz** [comment]
@viter-oliver , it seems that the format is broken. Could you update your post?
And could you prepare minimal and complete example that demonstrates the point of the issue?

**Comment by viter-oliver** [comment]
thanks for your prompt response.
sorry, a little error, all objects are an instance of the subclass of base_ui_component, below is the example:
class base_ui_component
{
protected:
struct internal_property
{
char _name[name_len];
struct{float x,y,z;} _pos;
bool _visible;
internal_property() :_visible(true){ memset(_name, 0, name_len); }
};
internal_property _in_p;
vector<base_ui_component*> _vchilds;
base_ui_component* _parent;
public:
base_ui_component()
	:_in_p()
	, _parent(NULL)
{
}
~base_ui_component()
{
	for (auto& it:_vchilds)
	{
		delete it;
	}
}
void add_child(base_ui_component* pchild){ pchild->_parent = this; _vchilds.push_back(pchild); }
base_ui_component* get_child(int index){return _vchilds[index];	}
};
calss ui_component1:public base_ui_component
{
  protected:
struct itl_pt
{
int p0,p1;
itl_pt() ){ }
};
itl_pt  _itl_pt;
}
calss ui_component2:public ui_component1
{
  protected:
struct itl_pt2
{
int p0,p1;
itl_pt2() ){ }
};
itl_pt2 _itl_pt2;
}

calss ui_component3:public base_ui_component
{
  protected:
struct itl_pt3
{
int p0,p1;
itl_pt3() ){ }
};
itl_pt3 _itl_pt3;
}

int main()
{
base_ui_component root;
root.add_child(new ui_component2());
root.add_child(new ui_component3());
root.add_child(new ui_component2());
base_ui_component* pchild1=root.get_child(1);
pchild1->add_child(new ui_component3() );

//so how can I serialize root with msgpack-c?
return 0;
}

**Comment by redboltz** [comment]
Could you update your comment using code decoration? 
triple back quotes ``` and language code `cpp`.
See
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by viter-oliver** [comment]
``` cpp
#include<vector>
using namespace std;
class base_ui_component
{
protected:
struct internal_property
{
char _name[name_len];
struct{float x,y,z;} _pos;
bool _visible;
internal_property() :_visible(true){ memset(_name, 0, name_len); }
};
internal_property _in_p;
vector<base_ui_component*> _vchilds;
base_ui_component* _parent;
public:
base_ui_component()
:_in_p()
, _parent(NULL)
{
}
~base_ui_component()
{
for (auto& it:_vchilds)
{
delete it;
}
}
void add_child(base_ui_component* pchild){ pchild->_parent = this; _vchilds.push_back(pchild); }
base_ui_component* get_child(int index){return _vchilds[index];	}
};
calss ui_component1:public base_ui_component
{
protected:
struct itl_pt
{
int p0,p1;
itl_pt() ){ }
};
itl_pt _itl_pt;
public:
ui_component1():base_ui_component(),_itl_pt(){}
}
calss ui_component2:public ui_component1
{
protected:
struct itl_pt2
{
int p0,p1;
itl_pt2() ){ }
};
itl_pt2 _itl_pt2;
public:
ui_component2():ui_component1(),_itl_pt2(){}
}

calss ui_component3:public base_ui_component
{
protected:
struct itl_pt3
{
int p0,p1;
itl_pt3() ){ }
};
itl_pt3 _itl_pt3;
public:
ui_component3():base_ui_component(),_itl_pt3(){}
}

int main()
{
base_ui_component root;
root.add_child(new ui_component2());
root.add_child(new ui_component3());
root.add_child(new ui_component2());
base_ui_component* pchild1=root.get_child(1);
pchild1->add_child(new ui_component3() );

//so how can I serialize root with msgpack-c?
return 0;
}
```

**Comment by redboltz** [comment]
Here is online compiler named Wandbox. That supports msgpack-c.
I copy-pasted your code to Wandbox.
https://wandbox.org/permlink/mV7EvIbrR6OsqD4V

Then I got compile error. It doesn't seems to relate to msgpack-c.
Could you fix this? And the code is difficult to read for me. Proper indentation is better.

**Comment by redboltz** [comment]
After fixing the code on Wandbox, click run and share button. Then you will get updated permalink at your browser's address bar. Please post the updated link here.

**Comment by viter-oliver** [comment]
https://wandbox.org/permlink/saz5EV3ONV3l0q2j

**Comment by redboltz** [comment]
Thank you for updating.
Unfortunately, msgpack-c doesn't support polymorphic serialization directly.
So, you need to use virtual function and `msgpack::packer`.

Here is an example:

https://wandbox.org/permlink/vmBpD7AoS7nVmV1k

```cpp
#include <msgpack.hpp>
#include <sstream>
#include <memory>
#include <iostream>

struct base {
    base(int i):a(i) {}
    virtual ~base() = default;
    
    virtual void pack(msgpack::packer<std::stringstream>& pk) const {
        pk.pack_array(2);
        pk.pack(a);
        pk.pack_array(v.size());
        for (auto const& e : v) {
            e->pack(pk);
        }
    }
    int a;
    std::vector<std::shared_ptr<base>> v;
};

struct sub : base {
    sub(int i):base(i/10), b(i) {}
    virtual void pack(msgpack::packer<std::stringstream>& pk) const override {
        pk.pack_array(2);
        base::pack(pk);
        pk.pack(b);                
    }
    int b = 0;
};

int main() {
    auto p = std::make_shared<base>(0);
    p->v.push_back(std::make_shared<sub>(10));
    p->v.push_back(std::make_shared<sub>(20));
    p->v.push_back(std::make_shared<sub>(30));
    p->v.back()->v.push_back(std::make_shared<sub>(40));
    std::stringstream ss;
    msgpack::packer<std::stringstream> pk(ss);
    p->pack(pk);
    
    auto oh = msgpack::unpack(ss.str().data(), ss.str().size());
    std::cout << oh.get() << std::endl;
}
```

**Comment by viter-oliver** [comment]
Ok, thanks for your reply, I get it
