### ISSUE TITLE
How can i get value of a particular element which is packed into a  data stream?

### ISSUE THREAD

**Issue by viter-oliver** [msgpack/msgpack-c#692]
I am still confused about the process of deserialization when using msgpack-c, could you give me more details? 
here is an example:
```cpp
#include<msgpack.hpp>
#include <sstream>
#include <memory>
#include <iostream>
static char* test_content[] =
{
	"hello world",
	"hello msgpack",
	"hello test msgpack",
};
static char* child_content[] =
{
	"name0",
	"name1",
	"name2",
};

int main(int argc, char* argv[])
{
	std::stringstream sbuf;
	msgpack::packer<std::stringstream> pk(sbuf);
	float w = 1920.f, h = 720.f;
	pk.pack_array(3);
	pk.pack_float(w);
	pk.pack_float(h);
	pk.pack_array(sizeof(test_content) / sizeof(char*));
	for (auto it : test_content)
	{
		pk.pack_array(2);
		int sl=strlen(it);
		pk.pack_bin(sl);
		pk.pack_bin_body(it, sl);
		pk.pack_array(sizeof(child_content) / sizeof(char*));
		for (auto iit : child_content)
		{
			pk.pack_array(5);
			int csl = strlen(iit);
			pk.pack_str(csl);
			pk.pack_str_body(iit, csl);
			float x0 = 1.f, x1 = 2.f, x2 = 3.f, x3 = 4.f;
			pk.pack_float(x0);
			pk.pack_float(x1);
			pk.pack_float(x2);
			pk.pack_float(x3);
		}
	}
	/*auto oh = msgpack::unpack(sbuf.str().data(), sbuf.str().size());
	std::cout << oh.get() << std::endl;*/
	static char* type_str[] = { "nil", "bool", "pint", "nint", "float32", "float64", "float", "str", "array", "map", "ext" };
	msgpack::object_handle oh;
	msgpack::unpacker unpac;
	unpac.reserve_buffer(sbuf.str().size());
	memcpy(unpac.buffer(), sbuf.str().data(), sbuf.str().size());
	unpac.buffer_consumed(sbuf.str().size());
	unpac.next(oh);
	
	std::cout<<type_str[oh.get().type] << std::endl;//float
	float fv;
	oh.get().convert(fv);//fail to convert
	unpac.next(oh);
	std::cout<<type_str[oh.get().type] << std::endl;//nil
	unpac.next(oh);
	std::cout<<type_str[oh.get().type] << std::endl;//nil
	unpac.next(oh);
	std::cout<<type_str[oh.get().type] << std::endl;//nil

	return 0;
}
```
what I want is get the value of variables one by one.

**Comment by redboltz** [comment]
In your example, the value is NOT float.
The value of `oh.get().type` is 6.

Here is `msgpack::type` definition:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/object_fwd_decl.hpp#L28

C++ enumerator is refer to C's one: 
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/object.h#L39

6 means ARRAY.

Here is running demo of your code. I added some assertions and debug prints:
https://wandbox.org/permlink/VkQOdcfXUtoAl6O1

NOTE: `msgpack::type::FLOAT` is an alias of `msgpack::type::FLOAT64`.

```c

    MSGPACK_OBJECT_NIL                  = 0x00,
    MSGPACK_OBJECT_BOOLEAN              = 0x01,
    MSGPACK_OBJECT_POSITIVE_INTEGER     = 0x02,
    MSGPACK_OBJECT_NEGATIVE_INTEGER     = 0x03,
    MSGPACK_OBJECT_FLOAT32              = 0x0a, // NOT simple increment
    MSGPACK_OBJECT_FLOAT64              = 0x04, // NOT simple increment
    MSGPACK_OBJECT_FLOAT                = 0x04, // NOT simple increment
#if defined(MSGPACK_USE_LEGACY_NAME_AS_FLOAT)
    MSGPACK_OBJECT_DOUBLE               = MSGPACK_OBJECT_FLOAT, /* obsolete */
#endif /* MSGPACK_USE_LEGACY_NAME_AS_FLOAT */
    MSGPACK_OBJECT_STR                  = 0x05,
    MSGPACK_OBJECT_ARRAY                = 0x06,
    MSGPACK_OBJECT_MAP                  = 0x07,
    MSGPACK_OBJECT_BIN                  = 0x08,
    MSGPACK_OBJECT_EXT                  = 0x09
} msgpack_object_type;
```

**Comment by viter-oliver** [comment]
Finally, I get all of the value of elements which are packed into std::stringstream.
Here is demo:
https://wandbox.org/permlink/TV1raZ9ak0KTXPCl
but I am still not sure whether the method I used is a formal one.

**Comment by redboltz** [comment]
I'm not sure what you want to do. Do you want to convert `msgpack::object` to some class? If it does, you can define your class and `auto yc = obj.as<your_class>()`. You don't need to access `msgpack::object`'s internal member.

**Comment by viter-oliver** [comment]
If I want to convert msgpack::object to my class, I must use MSGPACK_DEFINE_MAP inside my class. this kind of method will increase the degree of coupling, I just want to store particular member of my class while my class knows nothing about msgpack, so must I access msgpack::object 's internal member?

**Comment by redboltz** [comment]
Ah, I understand what you want do to.

You can use non-intrusive approach.
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#non-intrusive-approach
https://github.com/msgpack/msgpack-c/blob/master/example/cpp03/class_non_intrusive.cpp

In those adaptors, you needed to access `msgpack::object` internal structure.
Recently, I introduced `msgpack::object_parser` (#676) for internal use. But I think that it is useful to do user defined process to `msgpack::object` structure. It is not documented yet but you can use it.

Here is running demo:
https://wandbox.org/permlink/myaEwraqiQuF5q1E

It demonstrates how to define your visitor and how to use object_parser.
You can replace `std::ostream` with your class and assign its member variables in the visitor callback functions.

**Comment by redboltz** [comment]
`msgpack::object_parser` is going to be public interface. It has already been implemented. I don't have any plan to apply breaking change to it. I will add the document for it later. (I don't have much time, so far).

**Comment by viter-oliver** [comment]
thank you so much for your suggestion.
the non-intrusive approach is just what I want.
