### ISSUE TITLE
possible bug with msgpack map

### ISSUE THREAD

**Issue by danpf** [msgpack/msgpack-c#695]
I'm not entirely sure that this is a bug, maybe just something wrong with my environment, but figured I'd ask.

I'm on a new install of kubuntu 18.04, with
```
g++ --version
g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

this is the stdout of wandbox
https://wandbox.org/permlink/XhQJQKvUIAB4euAh
```
Hello
myobj
{"int1":12,"string2":"string_two"}
obj_TWO!!
null
```

But on my computer:
```
Hello

{"int1":12,"string2":"string_two"}
obj_TWO!!
null
```

For some reason I'm missing that 'myobj' print statement.... Any ideas of what could be happening?

**Comment by redboltz** [comment]
It seems that `obj` is dangling pointer.

```cpp
	msgpack::object obj = msgpack::unpack(ss.str().data(), ss.str().size()).get();
```

should be 

```cpp
	msgpack::object_handle oh = msgpack::unpack(ss.str().data(), ss.str().size());
	msgpack::object obj = oh.get();
```

See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_unpacker#accessing-unpacked-data

**Comment by danpf** [comment]
Awesome that works! So weird that it works on wandbox but not on the computer though.... I wonder why!
