### ISSUE TITLE
Where is the "EXPECT_TRUE" macro?

### ISSUE THREAD

**Issue by d223chen** [msgpack/msgpack-c#696]
I am trying to run the Visitor example from the Wiki. I am getting the error "identifier 'EXPECT_TRUE' is undefined". 

	#include <msgpack.hpp>

	struct json_like_visitor : msgpack::v2::null_visitor {
		json_like_visitor(std::string& s) :m_s(s) {}

		bool visit_nil() {
			m_s += "null";
			return true;
		}
		bool visit_boolean(bool v) {
			if (v) m_s += "true";
			else m_s += "false";
			return true;
		}
		bool visit_positive_integer(uint64_t v) {
			std::stringstream ss;
			ss << v;
			m_s += ss.str();
			return true;
		}
		bool visit_negative_integer(int64_t v) {
			std::stringstream ss;
			ss << v;
			m_s += ss.str();
			return true;
		}
		bool visit_str(const char* v, uint32_t size) {
			m_s += '"' + std::string(v, size) + '"';
			return true;
		}
		bool start_array(uint32_t /*num_elements*/) {
			m_s += "[";
			return true;
		}
		bool end_array_item() {
			m_s += ",";
			return true;
		}
		bool end_array() {
			m_s.erase(m_s.size() - 1, 1); // remove the last ','
			m_s += "]";
			return true;
		}
		bool start_map(uint32_t /*num_kv_pairs*/) {
			m_s += "{";
			return true;
		}
		bool end_map_key() {
			m_s += ":";
			return true;
		}
		bool end_map_value() {
			m_s += ",";
			return true;
		}
		bool end_map() {
			m_s.erase(m_s.size() - 1, 1); // remove the last ','
			m_s += "}";
			return true;
		}
		void parse_error(size_t /*parsed_offset*/, size_t /*error_offset*/) {
			EXPECT_TRUE(false);
		}
		void insufficient_bytes(size_t /*parsed_offset*/, size_t /*error_offset*/) {
			EXPECT_TRUE(false);
		}
		std::string& m_s;
	};

**Comment by redboltz** [comment]
@d223chen , thank you for reporting the issue.
It is defined at gtest. But it should be removed from the visitor example.
When I copy-pasted from the test code to the wiki, I forgot remove `EXPECT_TRUE`.
I will update the wiki.
