### ISSUE TITLE
Support for bit fields?

### ISSUE THREAD

**Issue by d223chen** [msgpack/msgpack-c#700]
#include <msgpack.hpp> 
     
     struct Bits {
     	uint32_t opCode : 5;
     	uint32_t header : 3;
     	uint32_t source : 5;
     	uint32_t destination : 5;
     	uint32_t offset : 13;

     	MSGPACK_DEFINE(opCode, header, source, destination, offset);
     };

throws MSVC errors:

Error E0304	no instance of overloaded function "msgpack::v2::type::make_define_array" matches the argument list	
message.h	 57	2

Error	 C2228	left of '.msgpack_unpack' must have class/struct/union	
message.h	 57	1

Error C2665	'msgpack::v1::type::make_define_array': none of the 2 overloads could convert all the argument types		
message.h	57	1

**Comment by redboltz** [comment]
msgpack-c doesn't support bit field, so far.

**Comment by redboltz** [comment]
I considered how to support bit-field.

We cannot get bit-field address:
https://wandbox.org/permlink/7zSoiCibyEgNG0Ox

The current MSGPACK_DEFINE implementation requires the address when converting. I'm not sure the requirement can be removed, so far.

I realized that you can pack, unpack, convert using as, creating msgpack::object with zone via non-intrusive approace:
https://wandbox.org/permlink/nHwypB5a0aC0DUMH

I think that it is acceptable solution.

**Comment by d223chen** [comment]
Thanks for the response. So this looks like it will pack each member into a uint32_t of its own, which effectively makes the packed data 5 ints of msgpack data.

I was also thinking about how to pack a 5 member bit field like `Bits` into just 1 int of msgpack format data, since the bitfield is meant to only occupy 1 int of space. Our solution for this was to use a union pattern, where one member of the union is this `Bits` struct, and one is an int acting as "raw" data. Then we use the bitfield for our internal code, but use msgpack to pack the "raw" data when sending a message.
