### ISSUE TITLE
Add option to disable the msgpackc-static target

### ISSUE THREAD

**Issue by urp** [msgpack/msgpack-c#703]
# Problem 
* On Arch linux the msgpack-c package ships a broken cmake package configuration file. It creates an imported target `msgpackc-static` which references a non-existing static library version. The static library was not included in the package due to Arch packaging policies. This renders the package config file useless.
* See https://bugs.archlinux.org/task/59282 for details.

# Solution

1. Add a build option which allows to disable the static target (when the shared target is enabled).
2. Automatically disable the static lib build/install when shared lib is build
3. Just relying on cmakes [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html) option to select a static/shared build might be the cleanest solution.
* Make sure the static target is not referenced in the cmake package configuration if not enabled

What do you think?

**Comment by redboltz** [comment]
Thank you for reporting the issue. I considered the flags.

The points are,
* Keeping the current behavior.
* User should be able to create both static and shared library on one setting.

So I got the following result:

* If BUILD_SHARED_LIBS == ON(default OFF) or MSGPACK_ENABLE_SHARED == ON(default ON) then build shared library.
  * It keeps the current behavior.
  * If the user set BUILD_SHARED_LIBS to OFF explicitly, the shared library is still built. It might unexpected, but keeping the current behavior is higher priority for me.
  * Those options are not affected to the static library.
    * I think that independent flag is easy to understand.
* If MSGPACK_ENABLE_STATIC == ON(default ON newly introduced) then build static library.

**Comment by urp** [comment]
Sounds great. Although it would be nice to have a deprecation of MSGPACK_ENABLE_SHARED in the future and replace it with `BUILD_SHARED_LIBS`. This could be done with `CMAKE_WARN_DEPRECATED` and `message( DEPRECATION "" )`

**Comment by redboltz** [comment]
Fixed by #713
