### ISSUE TITLE
Is msgpack hardware agnostic?

### ISSUE THREAD

**Issue by d223chen** [msgpack/msgpack-c#708]
What I mean is, for example, if I send msgpack data from one x64 bit little-endian machine to a x32 big-endian machine, can I be sure that the unpacked data on the receiving end is equivalent to the original data on the sending end?

**Comment by redboltz** [comment]
MessagePack is a data format that is defined https://github.com/msgpack/msgpack/blob/master/spec.md.

For example, int data is encoded as big-endian:
https://github.com/msgpack/msgpack/blob/master/spec.md#int-format-family

The format is independent from the machine endians.

msgpack-c detect the environment endian using (converted) boost library https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/predef/other/endian.h

And choose appropriate converting method. So msgpack-c can pack/unpack data between big-endian and little endian machines.
