### ISSUE TITLE
Can not link on 32-bit suse

### ISSUE THREAD

**Issue by y109** [msgpack/msgpack-c#71]
$ gcc -lmsgpack example.c
/usr/local/lib/libmsgpack.so: undefined reference to `__sync_sub_and_fetch_4'
collect2: ld returned 1 exit status

$ gcc -v
Using built-in specs.
Target: i586-suse-linux
Configured with: ../configure --enable-threads=posix --prefix=/usr --with-local-prefix=/usr/local --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib --libexecdir=/usr/lib --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.1.2 --enable-ssp --disable-libssp --disable-libgcj --with-slibdir=/lib --with-system-zlib --enable-shared --enable-__cxa_atexit --enable-libstdcxx-allocator=new --program-suffix= --enable-version-specific-runtime-libs --without-system-libunwind --with-cpu=generic --host=i586-suse-linux
Thread model: posix
gcc version 4.1.2 20070115 (prerelease) (SUSE Linux)

what i should do ? Thanks!

**Comment by redboltz** [comment]
msgpack-c uses std::atomic if -std=c++11 flags is set. If you have a compiler that supports C++11, please try it.

**Comment by edsiper** [comment]
I am facing the same problem with an old toolchain for an ARM device (

```
/home/edsiper/coding/fluent-bit/lib/msgpack-c-068041f/src/unpack.c:285: undefined reference to `__sync_sub_and_fetch_4'
../library/libmsgpackc.a(unpack.c.o): In function `incr_count':
/home/edsiper/coding/fluent-bit/lib/msgpack-c-068041f/src/unpack.c:293: undefined reference to `__sync_add_and_fetch_4'
../library/libmsgpackc.a(unpack.c.o): In function `decr_count':
/home/edsiper/coding/fluent-bit/lib/msgpack-c-068041f/src/unpack.c:285: undefined reference to `__sync_sub_and_fetch_4'
/home/edsiper/coding/fluent-bit/lib/msgpack-c-068041f/src/unpack.c:285: undefined reference to `__sync_sub_and_fetch_4'
```

the toolchain is for "ksz9692". Is there any suggestion ?

**Comment by redboltz** [comment]
@edsiper , I don't know much about the toolchain. But I found the following article:
http://vincesoft.blogspot.jp/2012/04/how-to-solve-undefined-reference-to.html

It might be helpful.

**Comment by edsiper** [comment]
thanks @redboltz !, the workaround helped to compile it.

**Comment by redboltz** [comment]
I close the issue. If you have more questions, feel free to re-open it.
