### ISSUE TITLE
maybe-uninitialized warning in GCC 8.2

### ISSUE THREAD

**Issue by drrlvn** [msgpack/msgpack-c#714]
https://github.com/msgpack/msgpack-c/blob/f79606d9ff1e46c33d6195ea0f90d15bddb1360a/include/msgpack/v1/object.hpp#L1127

```
In file included from ../worker_node/worker_node.hpp:3,
                 from ../worker_node/worker_node.cpp:1:
../base_node/base_node.hpp: In member function ‘virtual void HostIo::Nasduck::WorkerNode::handleNodeMessage(HostIo::Link&, HostIo::MessageID, const msgpack::v2::object&)’:
../base_node/base_node.hpp:13:33: error: ‘v’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         handle##MSG(obj.as<MSG>(), link); \
                                 ^
In file included from /root/.conan/data/msgpack/3.0.1/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/msgpack/object.hpp:15,
                 from /root/.conan/data/msgpack/3.0.1/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/msgpack.hpp:10,
                 from ../shared/msgpack_io.hpp:4,
                 from ../shared/dict.hpp:5,
                 from ../base_node/base_node_exceptions.hpp:3,
                 from ../base_node/base_node.hpp:3,
                 from ../worker_node/worker_node.hpp:3,
                 from ../worker_node/worker_node.cpp:1:
/root/.conan/data/msgpack/3.0.1/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/msgpack/v1/object.hpp:1127:7: note: ‘v’ was declared here
     T v;
       ^
```

This happens both in msgpack 2.1.5 and 3.0.1.

**Comment by redboltz** [comment]
I couldn't reproduce the warning.

So I wrote the following code:

https://wandbox.org/permlink/eKhliDKR0R1Rag2x
```cpp
volatile bool some_cond;
struct my_exception {};

struct object {
    template <typename T>
    T as() const {
        T v;
        convert(v);
        return v;
    }
    template <typename T>
    void convert(T& t) const {
        if (some_cond) throw(my_exception());
        t = T();
    }
    
};

using MSG = int; // your type

void handle(MSG const&) {
}

int main() {
    object obj;
    handle(obj.as<MSG>());
}
```

I'm not sure actual type of MSG. Could you test the code above with actual MSG type and your the same compile options as you got the warning.

**Comment by drrlvn** [comment]
The `MSG` type is a struct with `MSGPACK_DEFINE`. I'll try to produce a small reproduction.

**Comment by redboltz** [comment]
Simple MSG and using actual msgpack example:

https://wandbox.org/permlink/RJDa7C0wHD2jMiVf

**Comment by drrlvn** [comment]
The `MSG` type is a struct with `MSGPACK_DEFINE`.

I tried to construct a small test-case but couldn't. However in my own code it seems that if I manually inline `as` as:

```c++
MSG msg;
obj.convert(msg);
handle(msg);
```

Then it compiles, so I think as a workaround I'll do that.

This seems very odd to me and only started happening in GCC 8.2.0 so I think it may be a compiler bug.

**Comment by redboltz** [comment]
Perhaps it could be a hint to check existing bug.
https://gcc.gnu.org/bugzilla/buglist.cgi?quicksearch=maybe%20uninitialized

**Comment by drrlvn** [comment]
@redboltz yeah, `-Wmaybe-uninitialized` seems broken. I disabled it around `obj.as<>()` and will try again with next GCC version.

Thanks for the help and sorry for the noise.
