### ISSUE TITLE
add support for aarch64 windows

### ISSUE THREAD

**Issue by froydnj** [msgpack/msgpack-c#728]
Windows now runs on 64-bit ARM processors, and it seems straightforward enough to add this support alongside the ARM Windows support.

I think I can probably do this myself, but I'm unclear on the best way to go about doing it.  I see `__AARCH64EL__` preprocessor macros for testing endianness, for instance, but no `aarch64.h` header for architecture-specific support.  What's the recommended best way to add this support?

**Comment by redboltz** [comment]
msgpack-c contains https://www.boost.org/doc/html/predef.html internally.
And predef has endian checking macro. https://www.boost.org/doc/html/predef/reference.html#predef.reference.other_macros

Does it help you?

Currently, msgpack-c contains predef 1.61.0 but can update to 1.68.0.
