### ISSUE TITLE
wstring serialization

### ISSUE THREAD

**Issue by taushkanov** [msgpack/msgpack-c#735]
Is there any convenient way to serialize std::wstring? I didnt found better way than converting wstring to array of chars and serializing array. :(

**Comment by redboltz** [comment]
Do you expect serializing to [array](https://github.com/msgpack/msgpack/blob/master/spec.md#array-format-family) of  [uint16](https://github.com/msgpack/msgpack/blob/master/spec.md#int-format-family)?

**Comment by taushkanov** [comment]
I would like to do it in this manner:

	msgpack::packer<msgpack::sbuffer>	packer;

	std::wstring strValue;
	msgpack::object strObj(strValue);

	packer.pack(strObj);

but creating msgpack::object fails with message "unresolved external symbol" (extra quoting removed):

`unresolved external symbol "public: void __thiscall msgpack::v1::adaptor::object<class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,void>::operator()
...
referenced in function "void __cdecl msgpack::v1::operator<<<class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > >
`

**Comment by redboltz** [comment]
My question is what is expected packed data.

wstring is not a string. So it is not suitable for [STR](https://github.com/msgpack/msgpack/blob/master/spec.md#str-format-family).

Hence I think that the expected packed data depends on the application. So msgpack-c doesn't proved wstring adaptor.

But I could help you if I know the expected packed data.

**Comment by taushkanov** [comment]
I'm trying to serialize wstring containing localized data, for example in hex:
---
1F 04 3E 04 3F 04 4B 04 42 04 3A 04 30 04 20 00 41 04 35 04 40 04 38 04 30 04 3B 04 38 04 37 04 30 04 46 04 38 04 38 04 20 00 77 00 73 00 74 00 72 00 69 00 6E 00 67 00 2E 00
---

Or in localized case:
---
Попытка сериализации wstring.
---

May be it is possible to create adaptor to create object as array of uint16?

**Comment by redboltz** [comment]
I sent #737 to add wstring adaptor. wstring is serialized as array of wchar_t.
wchar_t's signed-ness and size seems to unspecified. So wchar_t is mapped to [INT format familiy](https://github.com/msgpack/msgpack/blob/master/spec.md#int-format-family)

**Comment by taushkanov** [comment]
I've checked #737. It works well, thank you :)
For example, now wstring "Description not set" serializes into array:[68,101,115,99,114,105,112,116,105,111,110,32,110,111,116,32,115,101,116]

**Comment by redboltz** [comment]
Thank you for checking. I merged #737 to master.
