### ISSUE TITLE
Get rid of "implicit-fallthrough" warning with GCC

### ISSUE THREAD

**Issue by DSiekmeier** [msgpack/msgpack-c#738]
Since v7 (?), the GCC warns on implicit fallthroughs in switch statements.

This behaviour, together with using the -Werror flag makes msgpack-c uncompilable because of unpack_template.h:238:1.

**Comment by redboltz** [comment]
https://github.com/msgpack/msgpack-c/blob/0a65c443a260e835e36b4d94b00468d9df1551a2/include/msgpack/unpack_template.h#L239
I think that this comment should suppress the warning(error).

**Comment by DSiekmeier** [comment]
Yes, actually it does. I think I was testing with an older version in which the CMakeLists.txt was very different than now. Sorry.
