### ISSUE TITLE
Suggested way for complex data

### ISSUE THREAD

**Issue by selimanac** [msgpack/msgpack-c#742]
I know this is not an issue and this is not the right place to ask, but I am stuck and couldn't find my way. So I'll be glad if anyone can help me on that. 

I'm trying to understand how msgpack-c works. I am sorry if I made stupid mistakes. 
Basically I am sending(from c++) and receiving (from node.js) data through websocket. 

Details about the message that I'm trying to unpack and convert:

packed
`[14,"\205\253currentTurn\300\247players\200\245board\223\223\223\223\246winner\300\244draw\300",1539531902697,0]`

Actual data
`{currentTurn: "63aRdXAxy", players: {…}, board: Array(3), winner: "63aRdXAxy", draw: null}`

Content of actual data
```
board: Array(3)
   0: (3) ["o", 0, 0]
   1: (3) [0, 0, 0]
   2: (3) [0, 0, 0]
currentTurn: "63aRdXAxy"
draw: null
players:
   5gh5l8Akuw: 1
   63aRdXAxy: 0
winner: null
```

This data easily unpacket with other msgpack libs (js, lua, c#). But when it comes to c++, I couldn't figure it out and it is almost impossible to debug values for me. 

I made a class for converting. It is not right, I know. This is what that I can't figure it out. 

```cpp
class msgParser {
public:
    int _prt; // 14
    std::tuple< std::map<std::string, std::string> , std::map< std::string, int> , std::map<int, int[3]> , std::map< std::string, std::string> , std::map<std::string, std::string> > arrayBuffer; //terrible and wrong
    std::uint64_t _remoteCurrentTime; // 1539531902697
    std::uint64_t _remoteElapsedTime; // 0
   
    MSGPACK_DEFINE(_prt, arrayBuffer, _remoteCurrentTime,_remoteElapsedTime);
};
```
When I try to convert the msgpack::object, I get an unfortunate error. 

```cpp
if(o.type != msgpack::type::ARRAY) { throw msgpack::type_error(); }
```

So is there a easy or suggested way of converting this data?

**Comment by selimanac** [comment]
this look similar with better explanation: https://stackoverflow.com/questions/24412133/deserializing-a-heterogeneous-map-with-messagepack-in-c

**Comment by redboltz** [comment]
Complex data doesn't seems to be the essence of the issue.Could you tell me what the problem is. I'm not sure but C# is similar to C++. Both has statically typed.

```
   0: (3) ["o", 0, 0]
```

seems to be difficult. "o" is `const char*` in C++ but 0 is int. Is this your problem?

**Comment by redboltz** [comment]
If heterogeneous container is the problem use https://stackoverflow.com/a/24468807/1922763 approach.

**Comment by selimanac** [comment]
Yes, my problem is heterogeneous containers. I can't predict the incoming packed data, It can be any.  Unfortunately I can't use the boost libs. I have a strict limitations. 

I'm looking for [visitor](https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_visitor#example). 
Is it the solution for heterogeneous containers?

> "o" is const char* in C++ but 0 is int.

It is a terrible design decision. But I don't care for it right now. 

Thank you @redboltz

**Comment by redboltz** [comment]
> I'm looking for visitor.
> Is it the solution for heterogeneous containers?

Yes. There are some ways.

1. If you can use boost, msgpack-c support msgpack::type::variant. It can treat well heterogeneous type.
2. If you can use C++17, you can use std::variant. Unfortunately, msgpack-c uses boost::variant to implement msgpack::type::variant. But you can implement similar type using std::variant.
3. Use visitor with parse(). In this way, msgpack::object is not created. You need to process SAX (compare to DOM) like approach.
4. Use visitor with msgpack::object. (Recently added. Not documented well, sorry.) I think it is good for your case.

This is an example.
https://wandbox.org/permlink/sKMPyBFR1oAeDEMP

**Comment by redboltz** [comment]
This approach is once creating msgpack::object, then parse the msgpack::object. msgpack::object is a kind of variant type. It doesn't require boost and C++17 feature.

**Comment by selimanac** [comment]
Since I can't use boost and C++17, msgpack::object_parser looks great for me and thank you for the example 🙏

Now I have other questions :)
- Is it expensive to use object_parser for mem and performance? 
- How can I handle/consume the parsed objects from object_parser like map or array properly? Is there a easy way of handling them?

Since you example works [great](https://wandbox.org/permlink/Xp2kpxZCKooVOGGT), I have an issue with the current data which I'm trying to parse. parser can't find the map or array in second field.

I'm going to investigate it but do you have any idea why parser can't parse the second field? Am I doing something wrong?

Data:

`[14,"\205\253currentTurn\300\247players\200\245board\223\223\223\223\246winner\300\244draw\300",1539601538980,0] `

It parse ints perfectly, but not the second field which has heterogeneous container.

```
array (size:4)[
INT:14
INT:1539601538980
INT:0
]
```

Using

```cpp
struct your_visitor : msgpack::null_visitor {
    bool start_map(uint32_t /*num_kv_pairs*/) {
        std::cout << "start_map:" << std::endl;
        return true;
    }
    
    bool end_map() {
        std::cout << "end_map:" << std::endl;
        return true;
    }
    
    bool start_array(uint32_t size) {
        std::cout << "array (size:" << size << ")[" << std::endl;
        return true;
    }
    bool end_array() {
        std::cout << "]" << std::endl;
        return true;
    }
    bool visit_positive_integer(uint64_t v) {
        std::cout << "INT:" << v << std::endl;
        return true;
    }
    bool visit_float64(double v) {
        std::cout << "FLOAT64:" << v << std::endl;
        return true;
    }
    bool visit_str(const char* v, uint32_t size) {
        std::cout << "STR:" << std::string(v, size) << std::endl;
        return true;
    }
};
```

**Comment by redboltz** [comment]
> Is it expensive to use object_parser for mem and performance?

I don't think it is expensive. But you can check the implementation. See
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/object.hpp#L151

> How can I handle/consume the parsed objects from object_parser like map or array properly? Is there a easy way of handling them?

Here are visitor implementations:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/object.hpp#L315
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/object.hpp#L396

Basically, pass to your object to the visitor by reference. The visitor stores it as reference. Then call parse(). In each handler you need, you can access the reference of your object.

**Comment by selimanac** [comment]
@redboltz  Thank you for your time and your help, appreciated. 
(look like my data is binary :) )
