### ISSUE TITLE
Error while running test programs

### ISSUE THREAD

**Issue by acad2** [msgpack/msgpack-c#745]
Hi,

After installing the library, I am getting an error, `error while loading shared libraries: libmsgpackc.so.2: cannot open shared object file: No such file or directory`. Any idea how to fix this?

**Comment by redboltz** [comment]
First, find the installed path.

```
find / -name libmsgpackc.so.2
```

You can get the path.

```
/usr/local/lib/libmsgpackc.so.2
```

Then, add the path to LD_LIBRARY_PATH

```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
```
