### ISSUE TITLE
[C lib] Packed float32 unpacks with object type MSGPACK_OBJECT_FLOAT64

### ISSUE THREAD

**Issue by randallpittman** [msgpack/msgpack-c#749]
MessagePack Version: msgpack-c v3.1.1
Platform: Linux x64 (gcc)

Sample code:
```c
#include <stdint.h>
#include <stdio.h>
#include <msgpack.h>
int main() {
  uint8_t packed[] = {0xca, 0x40, 0x20, 0x00, 0x00}; /* float32 2.5 */
  msgpack_unpacked msg;
  msgpack_unpacked_init(&msg);
  if (!msgpack_unpack_next(&msg, (char *)packed, 5, NULL))
    fprintf(stderr, "Unpacking error.\n");
  msgpack_object obj = msg.data;
  printf("Obj type is %u.\n", obj.type);
}
```
Result is:
```
Obj type is 4.
```
Instead of 

```
Obj type is 10.
```

I'm working on [an updated fork](https://github.com/randallpittman/msgpack-matlab) of [yida/msgpack-matlab](https://github.com/yida/msgpack-matlab) and I want to be able to detect if it's a float32 to unpack to a MATLAB `single`.

**Comment by randallpittman** [comment]
Accidentally closed.

**Comment by redboltz** [comment]
@randallpittman , it works for me.
The hash of the tag `cpp-3.1.1` is 83a82e3eb512b18d4149cabb7eb43c7e8bc081af.

Could you check the version of msgpack-c as follows?

```c
#include <stdint.h>
#include <stdio.h>
#include <msgpack.h>
int main() {
  uint8_t packed[] = {0xca, 0x40, 0x20, 0x00, 0x00}; /* float32 2.5 */
  msgpack_unpacked msg;
  printf("%s\n", MSGPACK_VERSION); /* add this */
  msgpack_unpacked_init(&msg);
  if (!msgpack_unpack_next(&msg, (char *)packed, 5, NULL))
    fprintf(stderr, "Unpacking error.\n");
  msgpack_object obj = msg.data;
  printf("Obj type is %u.\n", obj.type);
}
```

I got the following result:

```
3.1.1
Obj type is 10.
```

In addition, linking library path is  important.

Here is the compiling command that I got the output above.
```
 gcc -ggdb3  issue749.c -I/home/kondo/work/msgpack-c/include/ -L/home/kondo/work/msgpack-c/build/ -lmsgpackc  
```

I guess that the include path or the library path might be wrong.

**Comment by randallpittman** [comment]
Yeah I got 3.1.1 when I did that. I'll try nuking any and all msgpack on my system in /usr and /usr/local and try again.

**Comment by randallpittman** [comment]
Ok, the issue was that it was using the previously `yum install`'d v1.4.1 share library files because when I `make install`ed v3.1.1 to `/usr/local` it put `libmsgpackc.so.2` in `/usr/local/lib` instead of `/usr/local/lib64`. It doesn't help to link with `-L/usr/local/lib`. The only way I could get it to work was to run my test program with `LD_LIBRARY_PATH=/usr/local/lib ./mp_test_float`.
Is there any way to get `make install` to install the shared library files to the lib64 directory, or do i need to manually create a symlink or something?

**Comment by randallpittman** [comment]
Maybe if I build msgpack-c static-only my test proram will use the static version I specify with `-L`...

**Comment by redboltz** [comment]
You can use CMAKE_INSTALL_PREFIX to control the install location.
https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html

But I'm not sure how to control `lib`, `lib32`, or `lib64`. It's distribution dependent.

I recommend that check your local directory. Something like

```
cmake -DCMAKE_INSTALL_PREFIX=~/tmp ..
```

to avoid unexpected system directory writing.

> Maybe if I build msgpack-c static-only my test proram will use the static version I specify with -L...

Yes, it is another choice. You can set the cmake flag BUILD_SHARED_LIBS=OFF to make static library.

**Comment by randallpittman** [comment]
Ok, so I ran cmake with `-DCMAKE_INSTALL_PREFIX=/shared/opt/msgpack-c` and `-DBUILD_SHARED_LIBS=OFF` and ran `make install`. The header and .a files are where they should be.
Now if I try to build my test program with 
```bash
gcc -lmsgpackc -I/shared/opt/msgpack-c/include/ -L/shared/opt/msgpack-c/lib/ mp_unpack_float.c -o mp_unpack_float
```
I get the following linker error:
```
/tmp/ccmzqyeL.o: In function `main':
mp_unpack_float.c:(.text+0x62): undefined reference to `msgpack_unpack_next'
```

I've also tried a few other incantations like including the full path to the .a file etc. Not sure what the linker's problem is, but I'm out of my depth at this point.

**Comment by redboltz** [comment]
Maybe `-lmsgpackc` should place after `-L` option.

**Comment by randallpittman** [comment]
Thank you for your help, by the way. But no, that didn't work.

**Comment by randallpittman** [comment]
This could probably be closed--my original problem is solved--when I use the *actual* 3.1.1 I get the right type.
And apparently on CentOS `/usr/local/lib` isn't a default place to look for using dynamic libraries, so I have to do `ldconfig` stuff as per [this ServerFault comment](https://serverfault.com/questions/372987/centos-usr-local-lib-system-wide-ld-library-path).
However, I do still have the problem of being unable to link in the static library. I'll let you know if I come up with anything on that. Thanks again for your help.

**Comment by redboltz** [comment]
> Maybe -lmsgpackc should place after -L option.

Aha, if that is the  reason, the error message should be something like `library not found`.

In your case, library is found, but the function in the library not found.

Most likely reason, libmsgpackc.a not contains the function. Perhaps 32bit/64bit build issue.

**Comment by randallpittman** [comment]
Yeah, I used `nm` with the .a file and the function is in there, but like you say, maybe it's some 32/64bit issue. If I can dive more in at some point I will.
