### ISSUE TITLE
Can msgpack::unpack support advanced buffer like boost::asio::streambuf in msgpack-c-cpp-3.1.1?

### ISSUE THREAD

**Issue by nobody93** [msgpack/msgpack-c#752]
Hi,

I fixed segmentation issue (issue 750) by changing to use following unpack statements, it seems that unpack only worked for raw buffer, it could not compile for boost::asio::streambuf:

boost::asio::streambuf sb;
msgpack::object_handle oh = msgpack::unpack(sb, size);

error: no matching function for call to ‘unpack(boost::asio::streambuf&, int)’

Any luck I can  use unpack for boost::asio::streambuf?

BTW, are there any msgpack forum or mailing list for asking C++ msgpack questions?

Thank you.

**Comment by nobody93** [comment]
I could be wrong, but seems to me that the msgpack::unpack has no capability to support advanced boost buffer which made boost asio socket communication so difficult, how do you use msgpack for asio socket communication without using the raw char array buffer? Appreciate your inside comments.

Could you please also point me if there is a msgpack forum or mailing list for developers to ask C++ msgpack implementation questions?

Thank you.

**Comment by redboltz** [comment]
Hi @nobody93 ,
https://github.com/msgpack/msgpack-c/blob/master/example/boost/asio_send_recv.cpp
might be helpful.

**Comment by redboltz** [comment]
> Could you please also point me if there is a msgpack forum or mailing list for developers to ask C++ msgpack implementation questions?

Sorry for my late reply. Here is appropriate place to ask questions.

**Comment by nobody93** [comment]
Thanks redboltz, I did use that sample code in the first place which caused segmentation fault if you are running it for an hour or longer as I described in issue 750. Then I changed to use a raw buffer and deserialized by msgpack::object_handle oh = msgpack::unpack(this->mData, size); and     msgpack::object deserialized = oh.get();, that works well and it is much stable now, the only issue is the raw buffer is not a good structure to run asio socket communication, but if there is no good solution, I'll have to use raw buffer. 

Appreciate to clarify I can ask questions here.

Thank you very much

**Comment by redboltz** [comment]
> Thanks redboltz, I did use that sample code in the first place which caused segmentation fault if you are running it for an hour or longer as I described in issue 750. 

Really ? I didn't understand you mean the example https://github.com/msgpack/msgpack-c/blob/master/example/boost/asio_send_recv.cpp at #750.
But now I understand. And I reproduce the problem now.

I modified `asio_send_recv.cpp` as follows:
(Please search *** in this page. You can see modification point easily.)

```cpp
// MessagePack for C++ example
//
// Copyright (C) 2017 KONDO Takatoshi
//
//    Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//    http://www.boost.org/LICENSE_1_0.txt)
//

#include <string>
#include <sstream>
#include <iostream>

#include <boost/asio.hpp>
#include <boost/lexical_cast.hpp>

#include <msgpack.hpp>

int main() {
    boost::asio::io_service ios;
    std::uint16_t const port = 12345;

    // Server
    std::size_t const window_size = 10;
    boost::asio::ip::tcp::acceptor ac(ios, boost::asio::ip::tcp::endpoint(boost::asio::ip::tcp::v4(), port));
    boost::asio::ip::tcp::socket ss(ios);
    std::function<void()> do_accept;
    std::function<void()> do_async_read_some;

    msgpack::unpacker unp;

    do_accept = [&] {
        ac.async_accept(
            ss,
            [&]
            (boost::system::error_code const& e) {
                if (e) {
                    std::cout << __LINE__ << ":" << e.message() << std::endl;
                    return;
                }
                unp.reserve_buffer(window_size);
                do_async_read_some = [&] {
                    ss.async_read_some(
                        boost::asio::buffer(unp.buffer(), window_size),
                        [&](boost::system::error_code const& e, std::size_t bytes_transferred) {
                            if (e) {
                                std::cout << __LINE__ << ":" << e.message() << std::endl;
                                return;
                            }
                            std::cout << bytes_transferred << " bytes read." << std::endl;
                            unp.buffer_consumed(bytes_transferred);
                            msgpack::object_handle oh;
                            while (unp.next(oh)) {
                                std::cout << oh.get() << std::endl;
                                // In order to finish the program,
                                // return if one complete msgpack is processed.
                                // In actual server, don't return here.
                                // return;  // *** remove return here ***
                            }
                            do_async_read_some();
                        }
                    );
                };
                do_async_read_some();
            }
        );
    };
    do_accept();

    // Client
    auto host = "localhost";
    boost::asio::ip::tcp::resolver r(ios);

#if BOOST_VERSION < 106600
    boost::asio::ip::tcp::resolver::query q(host, boost::lexical_cast<std::string>(port));
    auto it = r.resolve(q);
    boost::asio::ip::tcp::resolver::iterator end;
#else  // BOOST_VERSION < 106600
    auto eps = r.resolve(host, boost::lexical_cast<std::string>(port));
    auto it = eps.begin();
    auto end = eps.end();
#endif // BOOST_VERSION < 106600

    boost::asio::ip::tcp::socket cs(ios);
    boost::asio::async_connect(
        cs,
        it,
        end,
        [&]
        (boost::system::error_code const& e, boost::asio::ip::tcp::resolver::iterator) {
            if (e) {
                std::cout << __LINE__ << ":" << e.message() << std::endl;
                return;
            }
            std::cout << __LINE__ << ":client connected" << std::endl;
            msgpack::sbuffer sb;
            for (int i = 0; i != 100; ++i) { // *** insert loop here ***
                msgpack::pack(sb, std::make_tuple(42, false, "hello world", 12.3456));
                write(cs, boost::asio::buffer(sb.data(), sb.size()));
            }
        }
    );

    // Start
    ios.run();
}
```

The problem is `unp.reserve_buffer(window_size);`.

```cpp
                unp.reserve_buffer(window_size);
                do_async_read_some = [&] {
                    ss.async_read_some(
```

The unpacker's buffer should be reserved for each `do_async_read_some()`.

So I moved it as follows:

```cpp
                do_async_read_some = [&] {
                   unp.reserve_buffer(window_size);
                    ss.async_read_some(
```

The error is disappeared.

I just post #753 to solve the problem.

**Comment by nobody93** [comment]
Thanks redboltz, indeed you fixed it.
