### ISSUE TITLE
mspack::pack of msgpack::object containing time is wrong

### ISSUE THREAD

**Issue by grmcdorman** [msgpack/msgpack-c#754]
The following code:
```c++
	auto time_32bit = std::chrono::system_clock::from_time_t(0x32BCFEDA);

	msgpack::zone zone;
	msgpack::object time_object(time_32bit, zone);
	std::stringstream buffer;
	msgpack::pack(buffer, time_object);
```
results in incorrect output; specifically, the output is:
 * EXT 8 (0xC7) instead of FIXEXT 4 (0xD6)
 * 8 characters instead of six
 * the type byte (0xFF or -1) is repeated
The actual data returned:
  C7 05 FF FF 32 BC FE DA
It appears the following code in object.hpp is at fault (line 354 in the current source):
```c++
    bool visit_ext(const char* v, uint32_t size) {
        m_packer.pack_ext(size, *v);
        m_packer.pack_ext_body(v, size);
        return true;
    }
```
The supplied size is the size including the type byte, but pack_ext and pack_ext_body expect the data-only size. In addition, pack_ext_body is passed the data starting with the type byte.

To correct:
```c++
    bool visit_ext(const char* v, uint32_t size) {
        m_packer.pack_ext(size - 1, *v);
        m_packer.pack_ext_body(v + 1, size - 1);
        return true;
    }
```

Generic ext-object packing in this fashion will of course also be affected.

**Comment by grmcdorman** [comment]
There may also be an error in comparison:
```c++
    bool visit_ext(const char* v, uint32_t size) {
        if (m_ptr->type != msgpack::type::EXT ||
            m_ptr->via.ext.size != size ||
            std::memcmp(m_ptr->via.ext.ptr, v, size) != 0) {
            m_result = false;
            return false;
        }
        return true;
}
```
``size`` does not count the type byte, so the memcmp is one byte short.

**Comment by redboltz** [comment]
@grmcdorman , thank you for reporting the issue. As you mentioned, it is not only `time` issue but also `EXT` issue. I will fix it.

**Comment by redboltz** [comment]
I sent the PR #755 to fix the issue.
@grmcdorman , could you try this?

**Comment by grmcdorman** [comment]
Verified that it works for me. Thank you for the quick fix.

**Comment by redboltz** [comment]
Thank you for checking. Merged.
