### ISSUE TITLE
Unpacking very large file

### ISSUE THREAD

**Issue by danpf** [msgpack/msgpack-c#766]
How would you unpack a large (20-50gb) msgpack file?
It looks like this is maybe not the right format when my data gets this large. but the max size of  a string is ~4gb (0xffffffff).  my data is of format map<std::string, std::list>.  it seems like there is some machinery in the upacker wiki, but it seems very tailored to network io as opposed to a single filehandle (std::ifstream)

**Comment by redboltz** [comment]
I'm not sure what the problem is.

Here is MessagePack format:
https://github.com/msgpack/msgpack/blob/master/spec.md

The data need to be right MessagePack format.
If the file contains multiple (huge number of) MessagePack data, it can be parsed correctly. You need some memory management on your environment.

**Comment by danpf** [comment]
Sorry, I was asking if there were any examples of this, or a relatively easy way to do this.

I think I should be looking here https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_unpacker#memory-management

but I'm not currently sure of how to implement that without hitting the 4gb size limit.

I will keep trying though.

**Comment by redboltz** [comment]
If you want to **pack** a huge data over 4GB, then you can split the file. Each split file can be packed as BIN format: 
https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family

You can treat them as independent MessagePack data, or one ARRAY https://github.com/msgpack/msgpack/blob/master/spec.md#array-format-family.

But your case is **unpack** not pack. That means you already have MessagePack binary file. So the first step is checking https://github.com/msgpack/msgpack/blob/master/spec.md.

If you want to use msgpack-c to check the huge file and `std::bad_alloc` is thrown, you can use parser and visitor. See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_visitor.

**Comment by redboltz** [comment]
Here is stream network send/receive example:
https://github.com/msgpack/msgpack-c/blob/master/example/boost/asio_send_recv.cpp

I think that you can use Boost.Asio stream_descriptor instead of sockets.
See https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/overview/posix/stream_descriptor.html

**Comment by danpf** [comment]
My msgpack binary file is within the spec described at your link.

```
                std::map<std::string, msgpack::object> target_map;
+               std::stringstream buffer;
+               long f_size(get_file_size(current_file));
+               std::ifstream in_reader( std::string(current_file).c_str(), std::ios::in | std::ios::binary );
+               msgpack::unpacker upd;
+               std::size_t const read_size(10000);
+               bool done = false;
+               msgpack::object_handle result;
+               msgpack::zone zoney;
+               msgpack::object t_obj;
+               while (!done) {
+                       upd.reserve_buffer(read_size);
+                       std::size_t actual_read_size = in_reader.readsome(upd.buffer(), read_size);
+                       upd.buffer_consumed(actual_read_size);
+                       while (upd.next(result)) {
+                               t_obj = msgpack::object(result.get(), zoney);
+                               done = true;
+                       }
+               }
                t_obj.convert(target_map);
```

this works nicely for reading.  I do unfortunately get 'bad_alloc'....   I'll be unpacking to a map of msgpack::objects which complicates things.  I will have to think about this some more... maybe I will split my file into many small ones... thank you for your help!

**Comment by redboltz** [comment]
Could you tell me how many times the following line is passed ?

```
+                               t_obj = msgpack::object(result.get(), zoney);
```

One?

**Comment by danpf** [comment]
Yes one.
that's where it fails with bad alloc. I do have 100+ gb of memory so this shouldn't be a problem.

**Comment by redboltz** [comment]
Ok, `upd.next()` returns true if **complete** one MessagePack object is processed. 

Let me show you an example. For convenience, I use json but it actually means MessagePack.

```
1
12.3
"ABC"
{ "ABC":12, "DEF:34.5}
["ABC", "DEFG", "HIJ"]
```

Each line is complete MessagePack object.
If the contents of the file are the example, it contains 5 MessagePack object, so `upd.next()` returns true 5 times.

NOTE: When `upd.next()` returns false, unpack process doesn't complete but several parsing process is done. It doesn't mean do nothing.

Back to your case, I don't know how many complete MessagePack objects are contained but the first one is huge.

In this case, there are some choices.

If you can modify the contents of the file,

modify the contents from

```
{ "ABC":12, "DEF:34.5, ............}
```

to 

```
{ "ABC":12}
{ "DEF:34.5}
...
```

Then, do all things in the following loop. The end of each loop, you can deallocate all memory. It can avoid memory peak.

```cpp
while (upd.next(result)) {
    t_obj = msgpack::object(result.get(), zoney);
    // do all process here, e.g.) convert, store another file, etc
    done = true;
}
```

If you cannot modify the contents of the file, you can use visitor. See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_visitor.

Here is an example:
https://github.com/msgpack/msgpack-c/blob/master/example/cpp11/socket_stream_example.cpp

The concept is visitor handler is called on `V` point the following object. So you can allocate, do something, and deallocate in the handlers.

```
V V     V V V    V   V
{ "ABC":12, "DEF:34.5, ............}
```

**Comment by danpf** [comment]
After trying multiple things, using a multiple-msgpack in one file approach I think is the best. The visitor approach gets too complex when trying to get the data from large MAPs and distribute it into specific vectors.

thank you for your help!
