### ISSUE TITLE
where is `msgpack::object` declared

### ISSUE THREAD

**Issue by walchko** [msgpack/msgpack-c#771]
Where is the class `msgpack::object` defined? I personally find the layout of the library confusing and I cannot find what methods the class has.

**Comment by redboltz** [comment]
`msgpack::object` is defined the following location:

https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/object_fwd.hpp#L75

Here is API reference.

http://c.msgpack.org/cpp/structmsgpack_1_1object.html

**Comment by walchko** [comment]
thanks!
