### ISSUE TITLE
Is msgpack-c thread safe?

### ISSUE THREAD

**Issue by Nik654** [msgpack/msgpack-c#787]
Is msgpack-c thread safe?
I am using msgpack-c from tag cpp-2.1.1, from what i saw it doesn't look thread safe, but i would still like to confirm this?

**Comment by redboltz** [comment]
msgpack-c isn't thread safe basically.

But when unpacking, and unpacker controls buffer lifetime, the reference counter is thread safe.
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_unpacker#msgpack-controls-a-buffer

https://github.com/msgpack/msgpack-c/blob/419877cf3a9d0d7a332cf9cc768c8813c019e00d/include/msgpack/v1/unpack.hpp#L226-L267

It is something similar to `std::shared_ptr`. Reference counter is thread safe but payload is not thread safe.

**Comment by Nik654** [comment]
Thank you for the response, i will close the issue.
