### ISSUE TITLE
zbuffer::flush() raises bad_alloc

### ISSUE THREAD

**Issue by clusby** [msgpack/msgpack-c#794]
Hi,

When using zbuffer on a larger object:
`zbuffer buf(Z_DEFAULT_COMPRESSION, MSGPACK_ZBUFFER_INIT_SIZE, true);`

Successive pack operations are working ok, but when `zbuffer::flush()` after all writes are complete - I get a `std::bad_alloc()`

If I add a case for `Z_BUF_ERROR`, it works as expected:
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/zbuffer.hpp#L71
```
            case Z_OK:
            case Z_BUF_ERROR:
                if(!expand()) {
                    throw std::bad_alloc();
                }
                break;
```

Can you please confirm if this is a bug, or is intentional? As with `zbuffer::write()`, I believe we should be handling `Z_BUF_ERROR`.

As per the docs: https://www.zlib.net/manual.html
> If the parameter flush is set to Z_FINISH, pending input is processed, pending output is flushed and deflate returns with Z_STREAM_END if there was enough output space. If deflate returns with Z_OK or Z_BUF_ERROR, this function must be called again with Z_FINISH and more output space (updated avail_out) but no more input data, until it returns with Z_STREAM_END or an error. After deflate has returned Z_STREAM_END, the only possible operations on the stream are deflateReset or deflateEnd.

**Comment by redboltz** [comment]
I think that you are right. I will fix it. And C part too.
