### ISSUE TITLE
how to build msgpack-c on arm

### ISSUE THREAD

**Issue by haozhuo1987** [msgpack/msgpack-c#798]
hi
      the msgpack-c compilie ,the lib only can run on x86 chip ,but ,i want the lib can run on arm 7 ,so i need to change the complilie tool from cc to arm-linux-gcc tool,and other *.h and lib we need to change the path，i don‘t no how use this cmake  can do this , so ,can you help me ,how to compilie it ,

**Comment by haozhuo1987** [comment]
SET(CMAKE_C_COMPILER “arm-linux-gcc”) i can find the CMAKE_C_COMPILER in CMakeList.txt

**Comment by haozhuo1987** [comment]
/fibocom/haozhuo/ndk_930_0724/fibo-sdk/al930/fibo-al930-sdk/fibo-crosstool/gcc-eglibc-locale-internal-arm-oe-linux-gnueabi-6.4.0/x86_64-linux/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-gcc
  --sysroot=/fibocom/haozhuo/ndk_930_0724/fibo-sdk/al930/fibo-al930-sdk/fibo-crosstool/gcc-eglibc-locale-internal-arm-oe-linux-gnueabi-6.4.0/mdm9607/
  -o CMakeFiles/cmTC_0277b.dir/testCCompiler.c.o -c
  /fibocom/haozhuo/ndk_930_0724/fibo-sdk/al930/fibo-al930-sdk/fibo-extsdk/example/mcm_sample/xiaoniu/msgpack-c/CMakeFiles/CMakeTmp/testCCompiler.c


  Linking C executable cmTC_0277b

  /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0277b.dir/link.txt
  --verbose=1



because my tool not in PATH,so i need to set by myself ,how to do it?

**Comment by redboltz** [comment]
I think that it is cmake issue.
https://cmake.org/cmake/help/v3.6/manual/cmake-toolchains.7.html#cross-compiling-for-linux
might help you.

BTW, if you want to C++ part of msgpack-c, it is header only, just compile on arm environment.

**Comment by haozhuo1987** [comment]
thank you verymach，now i change the CMakeList.txt use the link you give to me，i can compilie the lib ok，but when i compilie the example/cpp03/custom.cpp ，something wrong，can ' t find header file, just like this, do you meet this problem before??

/c++/6.4.0/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>

**Comment by redboltz** [comment]
> do you meet this problem before??

no.

> i can compilie the lib ok，

That means C cross compiler works well.

Are C examples compiled successfully?

`example/cpp03/custom.cpp` is C++ example. It requires C++ setting. How about other C++ examples?

You can make `make filename_without`.cpp`.
For example `make custom`. In addition if you use `make custom VERBOSE=1` then you can see actual compiler command. It may help you.


I think that the C++ cross compiler problem.

```
set(CMAKE_CXX_COMPILER ${tools}/bin/arm-linux-gnueabihf-g++)
```

arm-linux-gnueabihf-g++ and corresponding include files and libraries installed successfully?

**Comment by haozhuo1987** [comment]
libmsgpackc.so.2.0.0 i have got this lib ,did this means, i can use msgpack lib by c now??? others compilier is not necessary??
![image](https://user-images.githubusercontent.com/39908996/61872548-32ec5080-af16-11e9-80a3-5c357db28217.png)

 i don't need other

**Comment by haozhuo1987** [comment]
is this ok?? i can normally use msgpack  by c languege??

**Comment by redboltz** [comment]
I think so. You might have some problems on your C++ cross compiling environment but if you want to use C only, you can do that.

The screen shot is on the target arm machine?
If it does, I think everything works well.

**Comment by haozhuo1987** [comment]
yes  ,it is on the arm machine,but it very strange，i do not copy the libmsgpackc and the msgpack.h to the arm machine,but , the simple_c can run，this simple_c use the api provide by this lib，this simple_c going wrong is we expect，something wrong？？
![image](https://user-images.githubusercontent.com/39908996/61873089-9f1b8400-af17-11e9-822c-167eb26cc150.png)

**Comment by haozhuo1987** [comment]
the lib is static link to simple_c??

**Comment by redboltz** [comment]
Do you understand cross compiling mechanism?
`msgpack.h` and `libmsgpack.a` aren't needed on the target platform.
If you use static link, then you need to transfer the executable file only to the target platform.
If you use dynamic link, then you need to transfer the executable file and `libmsgpackc.so`.

**Comment by haozhuo1987** [comment]
i got that ，yes ，3ks very much。（：

**Comment by redboltz** [comment]
https://github.com/msgpack/msgpack-c/commit/b804e12dec506be93c07869735720991ceee81cc

https://github.com/msgpack/msgpack-c/blob/master/example/c/CMakeLists.txt#L1-L7

**Comment by redboltz** [comment]
You are welcome!
