### ISSUE TITLE
Message batching (It's question not issue)

### ISSUE THREAD

**Issue by nobody93** [msgpack/msgpack-c#810]
Hi,

Does msgpack-c have batching capability? I am currently transfer each message one by one from client to server over TCP socket, I am thinking to batch 10 or 20 messages, both client and server need to handle batching, are there any examples how to format / parse messages in batching?

Thank you.

Kind regards,

- jh

**Comment by redboltz** [comment]
Hi @nobody93 , what does batch mean? 
If it means multiple message packed binary data processing, you can do it as follows.
https://wandbox.org/permlink/eUsOp33Cve3i61No

**Comment by nobody93** [comment]
Thanks redboltz, that is exactly I was looking for.
