### ISSUE TITLE
Is a way to copy or move boost::asio::streambuf to msgpack::unpacker?

### ISSUE THREAD

**Issue by nobody93** [msgpack/msgpack-c#811]
Hi,

I used boost::asio::streambuf in boost asio socket read function to receive generic format of data, is it possible to move or copy boost::asio::streambuf data to msgpack::unpacker when the data is msgpack objects? Appreciate if you could give an example of the conversion between boost::asio::streambuf and msgpack::unpacker.
 
Thank you.

Kind regards.

**Comment by redboltz** [comment]
No, you need to use `msgpack::unpacker` instead of `boost::asio::streambuf`.
`msgpack::unpacker` works well with boost asio APIs.

See #752.

**Comment by nobody93** [comment]
> No, you need to use `msgpack::unpacker` instead of `boost::asio::streambuf`.
> `msgpack::unpacker` works well with boost asio APIs.
> 
> See #752.

That's fine, I'll use msgpack::unpacker for all data type, one feature I need to receive data to msgpack::unpacker, then send msgpack::unpacker.buffer() to async_write boost::asio::buffer(message->buffer(), message->size()), there was an error, no member named size() in msgpack::unpacker, how can I get msgpack::unpacker buffer size?

Thank you redboltz

**Comment by redboltz** [comment]
I'm not sure what you want to do.
You can use the unpacker to provide buffers to write the packed data. The packed data means Message Pack formatted data.
Then, you can get the unpacked object using `next()`.
If you want to convert, then you can use `as<T>()`.

What kind of data you want to send? MessagePacked data? Or other data?

**Comment by redboltz** [comment]
Maybe you can use the following size getting APIs.
https://wandbox.org/permlink/4ThwBFyiMIkk1e1v

Here is internal mechanism.
https://www.slideshare.net/taka111/msgpackc

**Comment by nobody93** [comment]
> I'm not sure what you want to do.
Receive from boost asio socket read to a buffer, then process the message and distributed to different targets via boost asio socket write.

> You can use the unpacker to provide buffers to write the packed data. The packed data means Message Pack formatted data.

So I can use unpacker buffer just like a raw buffer char *buffer, the reserve size call is to set up the buffer maximum size, the consume size call is to trim the buffer size to the real length.

> Then, you can get the unpacked object using `next()`.
Understood.

> If you want to convert, then you can use `as<T>()`.

> What kind of data you want to send? MessagePacked data? Or other data?
some are messagePacked data, some not.

Thanks redboltz for the help, I am going to close it.
