### ISSUE TITLE
Why would unpacker::next release the object_handle when no more entry is present?

### ISSUE THREAD

**Issue by wuyuanyi135** [msgpack/msgpack-c#813]
Hi, I am writing a program that receive buffer from a socket and unpack the buffer with `msgpack::unpacker`. After the the message packet is received, the `object_handle` is stored in a `shared_ptr` for future access. 
```cpp
auto result = std::make_shared<msgpack::object_handle>();
        while (unpacker->next(*result)) {
          auto sending_object =
              std::make_shared<rx_msgpack_object>(session, result);
          msgpack_object_parsed  //
              .get_subscriber()  //
              .on_next(sending_object);
        }
```
However, I noticed that the `zone` object in the `object_handle` was still released even though the `shared_ptr` was intact. I did some research and found that https://github.com/msgpack/msgpack-c/blob/0a65c443a260e835e36b4d94b00468d9df1551a2/include/msgpack/v2/unpack.hpp#L101 was the reason.

The `unpacker::next` intents to explicitly release the `object_handle` after no more object to unpack. I wonder why not just leave it for the caller of `unpacker::next` to destroy the `object_handle`?

In addition, I would like to know how should I unpack the buffer iteratively without having the previous `object_handle` released?

Thanks

**Comment by wuyuanyi135** [comment]
My current work-around is to use `msgpack::clone` to copy the object into a new object_handle.

**Comment by redboltz** [comment]
`msgpack::object_handle` behaves as a kind of smart pointer.  See
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_object
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/object.hpp#L134

Normally, we don't have much motivation to make `shared_ptr<msgpack::object>`

Here is an example of keeping `msgpack::object_handle` for future access. See the variable `ohs`.
https://wandbox.org/permlink/KvDv2HneDoVGqc8A
You don't need to call `clone()`. Zone's lifetime is managed by `msgpack::object_handle`.

`next()` has **overwrite** semantics.

**Comment by wuyuanyi135** [comment]
Thank you
