### ISSUE TITLE
Cjson to msgpack

### ISSUE THREAD

**Issue by jithinthomas0011** [msgpack/msgpack-c#818]
I'm using cjson C library for json creation and processing . can I use mspack on cjson ?

**Comment by jithinthomas0011** [comment]
> I'm using cjson library for json creation and processing . can I use mspack on cjson ?

**Comment by redboltz** [comment]
For C, msgpack-c provides https://github.com/msgpack/msgpack-c/wiki/v2_0_c_overview APIs. msgpack-c doesn't have direct support for json.

For C++, msgpack-c has some json support https://github.com/msgpack/msgpack-c/wiki/v_2_0_cpp_json.
