### ISSUE TITLE
pack result not to spec?

### ISSUE THREAD

**Issue by phylake** [msgpack/msgpack-c#835]
I was trying to send the result of the [quickstart first program](https://github.com/msgpack/msgpack-c/blob/master/QUICKSTART-C.md#first-program) to a service and discovered the data in the buffer doesn't appear to be to spec. Each type is preceded by `0xffffff`. I could be messing up my hex dump but I see what I expect in between the `0xffffff`

Just the relevant bits below. I printed out (print function not shown) the value of `sbuf.data` after each call

```
msgpack_pack_array(&pk, 2);                    // ffffff92
msgpack_pack_bin(&pk, 5);                      // ffffff92ffffffc405
msgpack_pack_bin_body(&pk, "Hello", 5);        // ffffff92ffffffc40548656c6c6f
msgpack_pack_bin(&pk, 11);                     // ffffff92ffffffc40548656c6c6fffffffc40b
msgpack_pack_bin_body(&pk, "MessagePack", 11); // ffffff92ffffffc40548656c6c6fffffffc40b4d6573736167655061636b
```

If the 3 instances of `0xffffff` weren't there this would be to spec afaik

**Comment by phylake** [comment]
This is w/ the latest release: 3.2.1

**Comment by redboltz** [comment]
It is caused by negative value and integral promotion in printing process.
See
https://wandbox.org/permlink/N57kxyVLxssYlRHz

It is not a msgpack-c problem.

**Comment by phylake** [comment]
Thank you @redboltz
