### ISSUE TITLE
[MinGW] Insufficient Bytes when single data is 0

### ISSUE THREAD

**Issue by dellorogiulio** [msgpack/msgpack-c#853]
Hi everybody,
I'm struggling with a very strange (I think) bug.
Here a minimal example:
```
#include <iostream>
#include <msgpack/msgpack.hpp>

struct IntMessage
{
    IntMessage(int _data) :
        data(_data)
    {
    }

    IntMessage() :
        data(0)
    {
    }

    int data;

    MSGPACK_DEFINE(data);

    inline std::string serialize() const
    {
        msgpack::sbuffer buffer;
        msgpack::pack(buffer, *this);
        return std::string{buffer.data()};
    }

    static inline IntMessage deserialize(std::string data)
    {
        IntMessage obj;
        auto oh = msgpack::unpack(data.data(), data.size());
        oh.get().convert(obj);
        return obj;
    }
};

int main(int argc, char const *argv[])
{
    IntMessage msg;
    msg.data = 1;  // set 0 to get 'msgpack::v1::insufficient_bytes'

    std::string buffer = msg.serialize();

    IntMessage new_msg = IntMessage::deserialize(buffer);
    std::cout << "DATA IS " << new_msg.data << std::endl;

    return 0;
}

```
If I set `msg.data = 0`, the deserialization throws a `msgpack::v1::insufficient_bytes` exception,
The strange thing is that, setting a non-zero value, all works fine.

If you are asking, it happens even with ` MSGPACK_DEFINE_MAP(data);`
I'm doing something wrong?

Thanks in advance for any help!

**Comment by redboltz** [comment]
```cpp
        return std::string{buffer.data()};
```

buffer contains MessagePack formatted bytes. It is a binary data. So it may contain 0.
You need to use https://en.cppreference.com/w/cpp/string/basic_string/basic_string (4).
In order to get size, you can use `msgpack::sbuffer::size()`.

**Comment by dellorogiulio** [comment]
Thanks! I knew I was missing something!
Thanks again
