### ISSUE TITLE
std::weak_ptr support?

### ISSUE THREAD

**Issue by NukeBird** [msgpack/msgpack-c#855]
Why std::shared_ptr supported but std::weak_ptr not?

**Comment by redboltz** [comment]
When users convert `std::weak_ptr` from `msgpack::object`, msgpack-c has no way to manage ownership. 

For shared_ptr, convert/as function create a new shared_ptr object. shared information is lost. See https://wandbox.org/permlink/hJ73noh4T5tAmM3J . I think that it is acceptable implementation.

You can write your own adaptor using https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#non-intrusive-approach.

**Comment by redboltz** [comment]
I close the issue, if you are still interested in the issue, reopen it with comment.
