### ISSUE TITLE
static_cast in C header

### ISSUE THREAD

**Issue by KarlVogel** [msgpack/msgpack-c#858]
The zbuffer.h header has C++ constructs (static_cast/reinterpret_cast/...) which causes it to fail compilation in a plain C project:

https://github.com/msgpack/msgpack-c/blob/7893d4d8c9ba8a8699c5c33152deaabf409250b3/include/msgpack/zbuffer.h#L103

Seems to have been introduced by:
https://github.com/msgpack/msgpack-c/pull/770

**Comment by ygj6** [comment]
`zbuffer.h` is only used in the C library,  and there are several `static_cast` and `reinterpret_cast` in it. We should replace it with C syntax expression.
