### ISSUE TITLE
codecov Github Actions failure on cpp_master

### ISSUE THREAD

**Issue by redboltz** [msgpack/msgpack-c#879]
@ygj6 , I noticed that the following CI error on coverage build:
https://github.com/msgpack/msgpack-c/runs/748333816?check_suite_focus=true#step:5:8

It seems that the following access is forbidden, I don't know why.
https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2

It's weird that the access is used not only coverage build but also normal test CI build. Why only coverage build is failed ?

Anyway, it should be fixed. I guess that the easiest solution is downloading boost from other location.

**Comment by ygj6** [comment]
This access was normal a few months ago, but it is forbidden now.
Why there is no error on `CI` workflow? Because the cache of boost works. 
I will find another invalid location and update the `coverage.yml`.

**Comment by redboltz** [comment]
It seems that Forbidden error is resolved on the server side.

**Comment by redboltz** [comment]
I think that it is a temporary trouble. The current download source is not bad.
So I close the issue.
