### ISSUE TITLE
Cmake - don't include examples

### ISSUE THREAD

**Issue by higaski** [msgpack/msgpack-c#880]
I'm including msgpack-c with CMake's FetchContent module into one of my builds like this

```
  FetchContent_Declare(
    msgpack
    GIT_REPOSITORY https://github.com/msgpack/msgpack-c.git
    GIT_TAG origin/cpp_master)
  FetchContent_MakeAvailable(msgpack)
```

Sadly the latest commit and an associated switch to the cpp_master branch broke my own CMake configuration as msgpack now includes the example folder which requires Boost::winapi. Is there any option I can set so that the examples won't be included?

Thanks

**Comment by redboltz** [comment]
Please use `MSGPACK_BUILD_EXAMPLES` option for cmake.
For example,

```sh
cmake -DMSGPACK_BUILD_EXAMPLES=OFF ...
```

Could you try this?


I noticed that it is not documented. 

@ygj6, I think that https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_configure should be updated. There are two kind of configuration switch. One is for source code (C/C++ preprocessor definition), and the other is for cmake.

The current `configuration` should be `configuration(preprocessor macro)`. And `configuration (cmake)` should be added.

**Comment by redboltz** [comment]
I updated https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_configure.

**Comment by higaski** [comment]
Yes thank you, that worked.
