### ISSUE TITLE
unit tests 

### ISSUE THREAD

**Issue by damian123** [msgpack/msgpack-c#9]
How do I run the unit tests when I build from git source myself?

I can see it needs gtest but I can't find any executable after build in test directory.

Would be nice if this was documented anywhere?

**Comment by immo-huneke-zuhlke** [comment]
It would be helpful to include in the documentation some help for installing Google Test. It took me over an hour to discover that you have to execute the make in the make subdirectory and then copy the resulting gtest_main.a to /usr/local/lib/libgtest_main.a, as well as running the manual g++ and ar commands shown in the README, and copying libgtest.a and the contents of the include folder to /usr/local/lib and /usr/local/include respectively.

**Comment by redboltz** [comment]
msgpack-c has a wiki documentation now.
After compiling gtest manually or via package manager such as apt-get, then, you can run the following command:

https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_overview#build-and-execute-tests
https://github.com/msgpack/msgpack-c/wiki/v1_1_cpp_overview#execute-tests

**Comment by redboltz** [comment]
I close the issue because no further comments after my comment.
Feel free to re-open if you have more questions.
