### ISSUE TITLE
Build msgpack C++ without boost

### ISSUE THREAD

**Issue by alxchk** [msgpack/msgpack-c#900]
I don't use boost in my project, and don't want to have any dependency to it. Previously it was possible to build msgpack without boost. Is there any way to do this now? It's now required in Cmake

**Comment by redboltz** [comment]
msgpack-c used to convert boost headers to msgpack. It was just conversion. So msgpack-c implicitly depends on boost.
@ygj6 pointed out it is unnatural way. It is better explicit dependency than implicit one.
So we updated.

Here is conversion code:
https://github.com/msgpack/msgpack-c/blob/cpp-3.3.0/CMakeLists.txt#L131-L149

@ygj6, any ideas?

**Comment by ygj6** [comment]
You can use the c_master branch, which is the C library of msgpack and does not depend on boost. 
If you must use the C++ library, then `boost` will be a must. 
You can build and install `boost` with the following command:
```
./b2 -j4 --toolset=gcc --prefix=/usr/local/boost --with-chrono --with-context --with-filesystem --with-system --with-timer address-model=64 install
```

**Comment by redboltz** [comment]
I think that if you don't want to install boost and just want to use msgpack-c (C++), simply download msgpack-c and boost and extract them.

Then

```sh
g++ -I msgpack-c/include -I path_to_boost_root your_source_file.cpp
```

msgpack-c (C++) library just use boost headers not built library (except some example code).
https://github.com/msgpack/msgpack-c/tree/cpp_master#c-header-only-library

**Comment by alxchk** [comment]
Okay, thanks. For now I'll downgrade to version 2. In future I will try to vendor required boost headers myself.

**Comment by Galicarnax** [comment]
The boost dependency should be stated in the documentation. Currently, only `gcc >= 4.1.0` and `cmake >= 3.0.0` are [mentioned](https://github.com/msgpack/msgpack-c/tree/cpp_master). Boost dependency comes as a surprise at compilation.

**Comment by redboltz** [comment]
Added to the document by #912
