### ISSUE TITLE
[Question Cpp] Unpacking from File is extremly slow compared to packing to File

### ISSUE THREAD

**Issue by CarlosYeverino** [msgpack/msgpack-c#902]
Hi all,

I'm using msgpack to create datasets that will be used afterwards for testing. Datasets are composed of multiple msg packs of different types defined as msgpack::type::tuple. Packing data into a file is performed efficiently, however, it takes a very long time to unpack the data (Example: Packing time takes 3 minutes while Unpacking time of the corresponding file takes 210 minutes) Note: I am not allowed to modify the definition of the structures used.

I pack the data into the file defined as `std::ofstream ofs` in the following way:
```
//Pack ID for msg pack
msgpack::pack(ofs, timestamp + "," + variableName + "," + "complexStructure"); 

msgpack::type::tuple<long long, bool, double, bool> complexStructure(data.timestamp,
                                                                                     data.automaticMode,
                                                                                     data.tractionSpeedSet,
                                                                                     data.brakeOn);
//Pack data
msgpack::pack(ofs, complexStructure);
.
.
.
//Multiple msg packs of different types defined as msgpack::type::tuple are logged into the file defined as ofs
```

I unpack the data from the file defined as `std::ifstream ifs` in the following way:
```
//Relevant variables
std::stringstream buffer;
std::size_t off = 0;
msgpack::object_handle result;

//Read complete File only one time
ifs.open(path + fileName, std::ios::in | std::ios::binary);
buffer << ifs.rdbuf(); //Copy input file content to a stringstream buffer to be processed using msgpack
.
.
.
//Once data type of msg pack is determined based on the ID, then unpack data for specific data type
//Following code is within a function, so the msgpack object should be destroyed after exiting the scope
msgpack::type::tuple<long long, bool, double, bool> complexStructure;
unpack(result, buffer.str().c_str(), ifs.tellg(), off);
msgpack::object obj(result.get());

obj.convert(complexStructure); //Converts msgpack::object instance into the original type.

data->timestamp = std::get<0>(complexStructure);
data->automaticMode = std::get<1>(complexStructure);
data->tractionSpeedSet = std::get<2>(complexStructure);
data->brakeOn = std::get<3>(complexStructure);

//Multiple msg packs of different types defined as msgpack::type::tuple are unpacked from the buffer where the file content was copied. There is a function to unpack data for every data type.
```

**As you can see in the code, a std::stringstream buffer is used to copy all file content and employed in the unpack() function to unpack the data individually depending of the data type (this code is not shown here). Is there a more efficient way to unpack data from a file? Do I need to free memory explicitly after each unpack call?**

Thanks in advance.

**Comment by redboltz** [comment]
@CarlosYeverino , I'm not sure which part of the code takes a long time.

I recommend that do the following approach.

1. Insert time measuring code to detect which part takes a long time. 
    Example: https://wandbox.org/permlink/wVw29MuYSwSQLQcP
2. Shrink the volume of data for testing. And replace store/read target from file to memory.

I believe that this approach helps to solve your problem.


NOTE:

I'm not sure this is essential issue but 

```cpp
unpack(result, buffer.str().c_str(), ifs.tellg(), off);
```

can be replace with

```cpp
std::string const& str = buffer.str();
unpack(result, str.data(), str.size(), off);
```

`tellg()` might be high cost.

**Comment by CarlosYeverino** [comment]
Hi @redboltz,

thanks for your reply. I will measure the code to detect what part is taking the longest time and come back to you.
Replacing `tellg()` by your suggestion improved the performance but just a little so I still need to find the root cause.

I noticed in your code example that you used the `obj.as` function while I use `obj.convert` function in my code. **Do you know which one more efficient is: `object.convert` or `object.as`?**

**Comment by redboltz** [comment]
> I noticed in your code example that you used the `obj.as` function while I use `obj.convert` function in my code. **Do you know which one more efficient is: `object.convert` or `object.as`?**

`convert` requires a default constructed object. And then, assign unpacked values to the object. `as` create the new object that is constructed by unpacked values. Generally, `as` is more efficient than `convert`. But I guess the difference is not so big. The biggest advantage of `as` is supporting non default constructible types.

**Comment by redboltz** [comment]
I close the issue, if you are still interested in the issue, reopen it with comment.
