### ISSUE TITLE
make install still depends on all compilations

### ISSUE THREAD

**Issue by wfjm** [msgpack/msgpack-c#908]
I'm using
-  currently latest commit 7d5324f
-  branch cpp_master

and I'm fully aware that this commit is at the beginning of a major restructuring. I see that
```
mkdir build
cd build
cmake ..
make --dry-run install
```

shows that `make install` still depends on all compilations.

Given that the C++ implementation is _header only_ I'd expect that `make install` simply copies the headers, and that only `make test` depends on all compilations.

**Comment by redboltz** [comment]
I'm not 100% sure but the following cmake options might solve the issue.

```sh
cmake MSGPACK_BUILD_TESTS=OFF MSGPACK_BUILD_EXAMPLES=OFF ..
```

@ygj6 , what do you think?

**Comment by wfjm** [comment]
Tried it on a fresh git clone
```
mkdir build
cd build
cmake MSGPACK_BUILD_TESTS=OFF MSGPACK_BUILD_EXAMPLES=OFF ..
make --dry-run install
```

Still creates a lot of C++ compiles.

But this would only be a work around anyway. There are simpler ones, like
```
    cd include
   sudo cp -a * /usr/local/include
```

My point was more conceptual. Why should a `make install` of a header only package depend at all on compilations. Why not just install the headers. If one wants test `make test` is the way to go,

**Comment by wfjm** [comment]
Opps, overlooked that you omitted the `-d` in the cmake. With
```
mkdir build
cd build
cmake -DMSGPACK_BUILD_TESTS=OFF -DMSGPACK_BUILD_EXAMPLES=OFF ..
make --dry-run install
```

I get essentially
```
/usr/bin/cmake -E cmake_echo_color --switch= --cyan "Install the project..."
/usr/bin/cmake -P cmake_install.cmake
```

So thanks for the workaround !
But my previous comment still holds.

**Comment by ygj6** [comment]
Yes, the correct options are
```
cmake -DMSGPACK_BUILD_TESTS=OFF -DMSGPACK_BUILD_EXAMPLES=OFF ..
```
> But my previous comment still holds.

@wfjm I don't quite understand you. Could you be more specific?

**Comment by redboltz** [comment]
I close the issue, if you are still interested in the issue, reopen it with comment.
