### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by johanjeppsson** [msgpack/msgpack-c#910]
I recently found msgpack when looking for alternative ways to pack debug data that is sent between two applications. I really like the ease of use in combination with very impressive performance when it comes to packing/unpacking. :slightly_smiling_face:

However, when porting our existing solution, I run into some issues with memory management with the msgpack zones.
Our current solution use nlohmann json, which is very easy and nice to use. We use a json-object to store our data as key-value pairs, which makes it easy to update the value for a key when needed, and then simply dump it to a string when we want to serialize. A simplified version of this would look something like this:

```c++
#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include <iostream>
#include <json.hpp>

using json = nlohmann::json;

int main() {
    json data;

    // Update key repeatedly
    for (int i = 0; i < 20000; i++) {
        std::vector<int> v;
        for (int j = 0; j < 1000; j++) {
            v.push_back(j + i);
        }
        data["key"] = v;
    }

    // Serialize
    std::ofstream outfile;
    outfile.open("out.json");
    outfile << data.dump();
    outfile.close();
}
```
```
> /usr/bin/time -f 'Time: %E, Memory: %M kB' ./json
Time: 0:06.62, Memory: 3552 kB
```
When I naively tried to use msgpack instead, I used a `std::map<std::string, msgpack::object>` to do something similar

```c++
#include <vector>
#include <map>
#include <string>
#include <sstream>
#include <fstream>
#include <iostream>
#include <msgpack.hpp>

int main() {
    msgpack::zone z;
    std::map<std::string, msgpack::object> data;

    // Update key repeatedly
    for (int i = 0; i < 20000; i++) {
        std::vector<int> v;
        for (int j = 0; j < 1000; j++) {
            v.push_back(j + i);
        }
        data["key"] = msgpack::object(v, z);
    }

    // Serialize
    std::stringstream ss;
    msgpack::pack(ss, data);

    std::ofstream outfile;
    outfile.open("out.msgpack");
    outfile << ss.str();
    outfile.close();
}
```

This works (nice and fast as well :+1:  ), however, since I keep using the same zone, the memory usage grows each time I update the value for "key". 

```
>/usr/bin/time -f 'Time: %E, Memory: %M kB' ./msgpack
Time: 0:01.06, Memory: 552428 kB
```

I've tried to use one zone per key instead of a global one, but in that case, I (at least I think) that I need data to be `std::map<std::string, msgpack::object_handle>` to ensure that the zone is connected to the msgpack::object and freed when the object is removed from the map. In that case, I cannot simply dump data, but instead need to iterate over the map and convert the `msgpack::object_handle` to `msgpack::object`, before serialization.

The other option that I can think of is to keep the data in a separate data structure (e.g. `std::map<std::string, std::variant<int, float, std::string>>`, and to create a msgpack::object from scratch when I want to serialize the data. That is probably acceptable, but keeping a representation of the data that can be dumped when needed feels nice and clean to me, so If I can avoid this, it would be nice.

Have I missed any obvious way to do what I want here?

**Comment by redboltz** [comment]
I think that using `msgpack::object_handle` is a good way.
As you mentioned, `msgpack::object_handle` is not serializable (packable) and dumpable. 
So just add adaptor for pack and ostream operator for dumping.

Here is the code:

```cpp
#include <vector>
#include <map>
#include <string>
#include <sstream>
#include <fstream>
#include <iostream>
#include <msgpack.hpp>


// For pack (serialize)

// custom adaptor for msgpack::object_handle
namespace msgpack {
MSGPACK_API_VERSION_NAMESPACE(MSGPACK_DEFAULT_API_NS) {
namespace adaptor {

template<>
struct pack<msgpack::object_handle> {
    template <typename Stream>
    packer<Stream>& operator()(msgpack::packer<Stream>& o, msgpack::object_handle const& v) const {
        o.pack(v.get());
        return o;
    }
};

} // namespace adaptor
} // MSGPACK_API_VERSION_NAMESPACE(MSGPACK_DEFAULT_API_NS)
} // namespace msgpack


// For dump

inline std::ostream& operator<<(std::ostream& os, msgpack::object_handle const& oh) {
    os << oh.get();
    return os;
}


int main() {
    std::map<std::string, msgpack::object_handle> data;

    // Update key repeatedly
    for (int i = 0; i < 20000; i++) {
        std::vector<int> v;
        for (int j = 0; j < 1000; j++) {
            v.push_back(j + i);
        }
        auto z = std::make_unique<msgpack::zone>();
        auto* pz = z.get();
        data["key"] = msgpack::object_handle(msgpack::object(v, *pz), std::move(z));
    }

    // Serialize
    std::stringstream ss;
    msgpack::pack(ss, data);

    std::ofstream outfile;
    outfile.open("out.msgpack");
    outfile << ss.str();
    outfile.close();
}
```

It is off topic but you can pack to outfile directly.

```cpp
    std::ofstream outfile;
    outfile.open("out.msgpack");
    msgpack::pack(outfile, data);
    outfile.close();
```

**Comment by johanjeppsson** [comment]
Wow, that was quick! Thanks for the elaborate response! :+1:

Your suggestion works as intended, and even seems to be a little bit faster:
```
/usr/bin/time -f 'Time: %E, Memory: %M kB' ./msgpack_hdl
Time: 0:00.92, Memory: 3600 kB
```

**Comment by johanjeppsson** [comment]
A follow up question:
If I need to have a nested structure, i.e. a case where the object_handles in the map are themselves ```std::map<std::string, msgpack::object_handle>```, I would need an adaptor, right? I've tried to create a 
```
    void operator()(msgpack::object::with_zone& o, msgpack::object_handle const& v) const {
```
adaptor, but haven't been able to get it to work. Or should the adaptor be for the ```std::map<std::string, msgpack::object_handle>``` type?

**Comment by redboltz** [comment]
I don't understand what you want to do.
object_handle holds object. object cannot hold std::map<std::string, msgpack::object_handle>.

Could you show me a minimal and complete code that describes your requirement ?

**Comment by johanjeppsson** [comment]
Sure!

I mean something simliar like the example above, but with extra levels.
The json structure I'm trying to emulate is something like this:

```json
{
    "group1": {
        "int": 1,
        "float": 2.0
    },
    "group2": {
        "vec": [1,2,3],              
    }, 
}
```

 so something like this.

```c++
template<typename T>
inline msgpack::object_handle to_handle(T data) {
    auto z = std::make_unique<msgpack::zone>();
    auto* pz = z.get();
    return msgpack::object_handle(msgpack::object(data, *pz), std::move(z));
}

// "group1"
std::map<std::string, msgpack::object_handle> group1;
group1["int"] = to_handle(1)
group1["float"] = to_handle(2.0);

// "group2"
std::map<std::string, msgpack::object_handle> group2;
v1 = std::vector<int> {1, 2, 3};
group2["vec"] = to_handle(v1);

std::map<std::string, msgpack::object_handle> data;
data["group1"] = to_handle(group1);
data["group2"] = to_handle(group2);

```

**Comment by redboltz** [comment]
> I mean something simliar like the example above, but with extra levels.

I mean http://sscce.org/
I don't have much time to write supplement codes for you.

**Comment by johanjeppsson** [comment]
Sure! Sorry...
Is this OK?

```c++
#include <vector>
#include <map>
#include <string>
#include <sstream>
#include <fstream>
#include <iostream>
#include <msgpack.hpp>


// For pack (serialize)

// custom adaptor for msgpack::object_handle
namespace msgpack {
MSGPACK_API_VERSION_NAMESPACE(MSGPACK_DEFAULT_API_NS) {
namespace adaptor {

template<>
struct pack<msgpack::object_handle> {
    template <typename Stream>
    packer<Stream>& operator()(msgpack::packer<Stream>& o, msgpack::object_handle const& v) const {
        o.pack(v.get());
        return o;
    }
};

} // namespace adaptor
} // MSGPACK_API_VERSION_NAMESPACE(MSGPACK_DEFAULT_API_NS)
} // namespace msgpack


// For dump
inline std::ostream& operator<<(std::ostream& os, msgpack::object_handle const& oh) {
    os << oh.get();
    return os;
}

template<typename T>
inline msgpack::object_handle to_handle(T data) {
    auto z = std::make_unique<msgpack::zone>();
    auto* pz = z.get();
    return msgpack::object_handle(msgpack::object(data, *pz), std::move(z));
}


int main() {
    std::map<std::string, msgpack::object_handle> group1;

    group1["int"] = to_handle(1);
    group1["float"] = to_handle(2.0);

    std::map<std::string, msgpack::object_handle> group2;

    group2["vec"] = to_handle(std::vector<int>{1, 2, 3});

    std::map<std::string, msgpack::object_handle> data;
    // This does not work.
    // data["group1"] = to_handle(group1);
    // data["group2"] = to_handle(group2);

    std::ofstream outfile;
    outfile.open("out.msgpack");
    msgpack::pack(outfile, data);
    outfile.close();
}

```

If group1/group2 are ```std::map<std::string, msgpack::object>``` instead, it works, so my understanding is that an adaptor for ```object_handle``` could solve this. Is this right?

What I've tried is something like this

```c++
template <>
struct object_with_zone<msgpack::object_handle> {
    void operator()(msgpack::object::with_zone& o, msgpack::object_handle const& h) const {
        o.set(v.get());
    }
};
```
But I'm not sure if I'm misunderstanding how the adaptors work, or if I'm going about this the wrong way.

**Comment by redboltz** [comment]
I don't come up with how to treat well `msgpack::object_handle` as the member of `msgpack::object`. It is very complicated.
Perhaps there is a way but you need to read almost whole implementation of msgpack-c.

I recommend a different way to write json like structure.

See 
https://github.com/msgpack/msgpack-c/issues/911#issuecomment-671143874
https://github.com/msgpack/msgpack-c/issues/911#issuecomment-671197863

I think that `msgpack::type::variant` is better choice.

**Comment by redboltz** [comment]
Here is an example code.

https://wandbox.org/permlink/zv9lbldWDWlhYM47

```cpp
#include <msgpack.hpp>
#include <iostream>
#include <sstream>

inline std::ostream& hex_dump(std::ostream& o, std::string const& v) {
    std::ios::fmtflags f(o.flags());
    o << std::hex;
    for (auto c : v) {
        o << "0x" << std::setw(2) << std::setfill('0') << (static_cast<int>(c) & 0xff) << ' ';
    }
    o.flags(f);
    return o;
}


int main() {

    using mp_map = std::map<msgpack::type::variant, msgpack::type::variant>;
    using mp_array = std::vector<msgpack::type::variant>;

    mp_map m {
        { 
            "group1",
            mp_map {
                {
                    "int", 1
                },
                {
                    "float", 2.3
                },
            }
        },
        { 
            "group2", 
            mp_map {
                {
                    "vec",  mp_array {1, 2, 3}
                }
            }
        },
    };

    std::stringstream ss;
    msgpack::pack(ss, m);
    auto const& str = ss.str();
    hex_dump(std::cout, str) << std::endl;

    auto oh = msgpack::unpack(str.data(), str.size());
    std::cout << oh.get() << std::endl;
}
```

**Comment by redboltz** [comment]
I found a way based on your (msgpack::object_handle based) approach.

https://wandbox.org/permlink/tRitMtltILivAsh7

Adding object_with_zone adaptor approach that you mentioned is good way.

```cpp
template <>
struct object_with_zone<msgpack::object_handle>
```

`msgpack::object_handle` is not copy constructible but your original code required copy constructible,

I added `&&` then it becomes forwarding reference.

```cpp
inline msgpack::object_handle to_handle(T&& data) { // The original code required copy constructor
```

I implemented the body of object_with_zone adaptor.

```cpp
template <>
struct object_with_zone<msgpack::object_handle> {
    void operator()(msgpack::object::with_zone& o, msgpack::object_handle const& h) const {
        o << h.get();
    }
};
```

**Comment by johanjeppsson** [comment]
Great, thank you very much! Your final example seems to work as intended for me too.
I'm sure that the variant example would work too, but if I can avoid using boost without too much added complexity, I'd rather go that route.

Once again, your quick and elaborate responses are much appreciated!

**Comment by redboltz** [comment]
You are welcome.

`msgpack::zone` is a kind of memory pool. `msgpack::object` is designed as a read only type basically.

```cpp
o << h.get();
```

At the line above, the zone in the h is not inherited. The object is constructed using o.zone. The all objects under the h are constructed on o.zone. It may different from the original h zone structure.
You always consider the zone very carefully if you use this approach.
`msgpack::object` become dangling reference easily.
