### ISSUE TITLE
Creating and serializing a map changes unsigned value

### ISSUE THREAD

**Issue by mprather** [msgpack/msgpack-c#911]
I've been trying to convert a simple json object into a msgpack representation. I've used two other C# libraries to produce the msgpack data as a comparison point; however, I can't get this library to produce the same output. 

Here's what I would like to create:

{ "Name": "v", "Class": 11, "OtherName": "w", "Class2": 11 <2 other similar pairs omitted> }

My attempts to duplicate this structure involved define_map as shown below:

```
  msgpack::type::define_map<std::string, std::string, 
                                                std::string, unsigned int, 
                                                std::string, unsigned int, 
                                                std::string, std::string> mapx(name, i.name, state, i.s, ch, i.ch, dt, i.dt);

    std::stringstream buffer;

    msgpack::pack(buffer, mapx);

```

The packer does not properly encode the size of the map. Instead of 0x84, the packer always produces 0x7c. The unsigned nature of the 0x84 is dropped in the call to pack_map. You can see the expected value is created but then immediately lost when the call to take8_8 is made.

Is there a better way to create a simple map structure? 

Dev environ: Windows 10, VS 2019 latest.

**Comment by redboltz** [comment]
I'm not 100% sure what you want to do.
I guess that you want to pack a collection of std::string key and variant value type.

You can use `msgpack::type::variant` as follows:

```cpp
#include <msgpack.hpp>
#include <iostream>
#include <sstream>

inline std::ostream& hex_dump(std::ostream& o, std::string const& v) {
    std::ios::fmtflags f(o.flags());
    o << std::hex;
    for (auto c : v) {
        o << "0x" << std::setw(2) << std::setfill('0') << (static_cast<int>(c) & 0xff) << ' ';
    }
    o.flags(f);
    return o;
}


int main() {
    using namespace std::literals::string_literals;

    std::map<std::string, msgpack::type::variant> m {
        { "Name", "v" },
        { "Class", 11 },
        { "OtherName", "w" },
        { "Class2", 11 },
    };

    std::stringstream ss;
    msgpack::pack(ss, m);
    auto const& str = ss.str();
    hex_dump(std::cout, str) << std::endl;

    auto oh = msgpack::unpack(str.data(), str.size());
    std::cout << oh.get() << std::endl;
}
```

Output:

```
0x84 0xa5 0x43 0x6c 0x61 0x73 0x73 0x0b 0xa6 0x43 0x6c 0x61 0x73 0x73 0x32 0x0b 0xa4 0x4e 0x61 0x6d 0x65 0xa1 0x76 0xa9 0x4f 0x74 0x68 0x65 0x72 0x4e 0x61 0x6d 0x65 0xa1 0x77
{"Class":11,"Class2":11,"Name":"v","OtherName":"w"}
```

The key is sorted by `std::map`. If the order is important, then you can use `std::vector<std::pair<std::string, msgpack::type::variant>>`.

**Comment by mprather** [comment]
Thanks for the quick response. I'm not using the boost additions (and can't); otherwise, I would have seen and attempted to use the variant type. 

Is the approach I outlined not suitable/allowed?  The objects are created but the code runs aground with the call to pack_map (lines 1216, 1217). Is this a bug in the underlying methods or is the approach just wrong?   

I've pulled in this type of object into the unpacker and had no problems in the past. This is the first time where I need to create the object directly (i.e. in msgpack format from the get go vs starting out as json then converting it to msgpack). If the define_map struct is not the right approach, what would be the best way to create a simple object with relying on boost?

**Comment by redboltz** [comment]
define_map is a kind of internal type. It is a implementing method for MSGPACK_DEFINE_MAP.
define_map is not designed for direct use.

Maybe you need something variant data type. You can implement your own variant type using C++17 std::variant. The adaptor is not in msgpack-c so you need to implement by yourself.

Or msgpack::object can be used.

See

```cpp
#include <msgpack.hpp>
#include <iostream>
#include <sstream>

inline std::ostream& hex_dump(std::ostream& o, std::string const& v) {
    std::ios::fmtflags f(o.flags());
    o << std::hex;
    for (auto c : v) {
        o << "0x" << std::setw(2) << std::setfill('0') << (static_cast<int>(c) & 0xff) << ' ';
    }
    o.flags(f);
    return o;
}


int main() {
    msgpack::zone z;    
    
    std::map<std::string, msgpack::object> m {
        { "Name", msgpack::object("v", z) },
        { "Class", msgpack::object(11, z) },
        { "OtherName", msgpack::object("w", z) },
        { "Class2", msgpack::object(11, z) },
    };

    std::stringstream ss;
    msgpack::pack(ss, m);
    auto const& str = ss.str();
    hex_dump(std::cout, str) << std::endl;

    auto oh = msgpack::unpack(str.data(), str.size());
    std::cout << oh.get() << std::endl;
}
```

https://wandbox.org/permlink/8LHGmGglYNPG3bIV

NOTE:
msgpack-c (C++) depends on boost now. But only depends on boost headers. So you can just copy boost source tree and set it to the include path. See #900

**Comment by mprather** [comment]
Thanks again for the feedback. The second approach works well.

It's worth noting that setup (manual and vcpkg) haven't mentioned boost. Although I understand the premise behind #900 (reduce duplicated code), the inclusion of boost libraries is often frowned on in our projects. I would encourage you to see how future versions could remove that dependency.
