### ISSUE TITLE
Missing link to gtest

### ISSUE THREAD

**Issue by SeanWeiUBNT** [msgpack/msgpack-c#915]
Build failed with following message:

> [ 44%] Linking CXX executable boost_string_view
> /usr/local/lib/libgtest_main.a(gtest_main.cc.o): In function 'main':
> gtest_main.cc:(.text+0x28): undefined reference to 'testing::InitGoogleTest(int*, char**)'
> /usr/local/lib/libgtest_main.a(gtest_main.cc.o): In function 'RUN_ALL_TESTS()':
> gtest_main.cc:(.text._Z13RUN_ALL_TESTSv[_Z13RUN_ALL_TESTSv]+0x5): undefined reference to 'testing::UnitTest::GetInstance()'
> gtest_main.cc:(.text._Z13RUN_ALL_TESTSv[_Z13RUN_ALL_TESTSv]+0xd): undefined reference to 'testing::UnitTest::Run()'
> collect2: error: ld returned 1 exit status
> test/CMakeFiles/boost_string_view.dir/build.make:97: recipe for target 'test/boost_string_view' failed
> make[2]: *** [test/boost_string_view] Error 1
> CMakeFiles/Makefile2:1975: recipe for target 'test/CMakeFiles/boost_string_view.dir/all' failed
> make[1]: *** [test/CMakeFiles/boost_string_view.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2

By adding "-lgtest" in test/CMakeFiles/boost_string_view.dir/link.txt like this can solve this issue:

> /usr/bin/c++   -DMSGPACK_DEFAULT_API_VERSION=3 -std=c++11    CMakeFiles/boost_string_view.dir/boost_string_view.cpp.o  -o boost_string_view -rdynamic /usr/local/lib/libgtest.a /usr/local/lib/libgtest_main.a -lz -lgtest -lpthread

Sorry for not familiar to CMake to solve the root cause :(

**Comment by redboltz** [comment]
msgpack-c uses gtest 1.7.0, so far.

I think that you need to use custom build version of gtest. gtest should be built the same option as msgpack-c.
pre-installed gtest often cause link error.

See https://github.com/msgpack/msgpack-c/blob/cpp_master/.github/workflows/gha.yml#L70-L82

**Comment by redboltz** [comment]
msgpack-c no longer depends on gtest.
