### ISSUE TITLE
Best way to parse a known msgpack protocol

### ISSUE THREAD

**Issue by shashank88** [msgpack/msgpack-c#925]
Hi, 
Great work on this project! 

We are trying to use msgpack-cpp to parse a buffer that's packed in java and sent over kafka to our C++ service. The protocol for the data inside is consistent. i.e something like:
```[
'description': '',
'ts': 1,
{
'a':  2,
'b': 3
}
'seq': 5
]
```
which would translate to a struct like:
```
struct Test {
    string desc;
    int ts;
     map<string, int> m;
    int seq;
}
```

what would be the best way to coerce the buffer into a struct like above? Currently, I am inheriting from the null visitor and adding explicitly to it by using a global marker to keep track, but I am guessing there is a better way which I am obviously missing.

**Comment by redboltz** [comment]
I'm not sure what you want to do.
Some documents here: https://github.com/msgpack/msgpack-c/wiki

**Comment by redboltz** [comment]
JSON support is https://github.com/msgpack/msgpack-c/wiki/v_2_0_cpp_json

**Comment by shashank88** [comment]
I am trying to parse an already known structure, where I know the order the fields are in. And convert that to the C++ structure (like Test above) matching that equivalent format from Java. So in the incoming msgpack, the data has a string, followed by an integer, followed by a map of str: int which is equivalent to the Test struct above.

**Comment by redboltz** [comment]
I am still not sure. Maybe minimal and complete code that demonstrate your situation.
It must compile and run.

I guess MSGPACK_DEFINE_MAP can be used.
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#defining-custom-adaptors

**Comment by shashank88** [comment]
The adaptor might be what I am looking for. Basically, I want something like this:
```
\x95\xa5MT.NA\xcf\x00\x00\x01u1^ \x16\xa6UPDATE\xde\x00\x1c\xa9PROD_PERM\xcd6\xd5\xaaDelayedEID\x00\xa7. ......
```
converted into a C++ struct (where each field in the struct is in order matching the above payload) like:
```
struct Test {
    string desc;
    int ts;
     map<string, int> m;
}
```

**Comment by redboltz** [comment]
Please read wiki and examples https://github.com/msgpack/msgpack-c/blob/cpp_master/example/cpp03/class_intrusive_map.cpp
If you have further questions, then ask me with complete code.

**Comment by shashank88** [comment]
I tried a few things but they didn't work, basically I am not sure how to convert a variable length MAP to a C++ unordered / map. I keep getting std::bad_cast when using it with adapters.
So if I was writing a map like: {'a': 1, 'b': 2, 'c': 3 ....(N kv pairs) } I am not sure after getting an object_result with this, how do I then convert it to std::map.
```                  auto mp = obj.via.array.ptr[3];    -> MAP type
                    GTEST_COUT << mp.type;
                    std::map<std::string, int> map_;
                    mp.convert(map_);```   -> bad cast

I will create a minimal repro in wandbox and paste it here.
