### ISSUE TITLE
how to pack custom class member?

### ISSUE THREAD

**Issue by gzliudan** [msgpack/msgpack-c#927]
Since MSGPACK_BASE is used to pack base class. If member is also a custom class, not base class, which macro shall we use under below case:

```cpp
    struct type_a {
        uint64_t name;
        std::vector<char> data;
        MSGPACK_DEFINE(name, data);
    };


    struct type_b {
        std::vector<type_a> obj_a;
        MSGPACK_DEFINE(obj_a);
    };


    struct type_c {
        char                id[16];
        std::vector<type_b> obj_b;
        MSGPACK_DEFINE(id, obj_b);
    };
```

**Comment by redboltz** [comment]
I think that your code is right.
`MSGPACK_DEFINE` is for members.

**Comment by gzliudan** [comment]
Yes, the problem is that I should use std::array<char, 16> for member type_c::id, not use C array char[]
