### ISSUE TITLE
How is Cpp version and C version going to be updated in the future?

### ISSUE THREAD

**Issue by FEZZDINO** [msgpack/msgpack-c#928]
Will the Cpp version and the C version msgpack update together or seperately? 
Will you divide Cpp version and the C version into two git repo in the future?

**Comment by redboltz** [comment]
@ygj6 and I discussed at #872

We considered several options. And finally use `c_master` and `cpp_master` branches.
One of the pros of the approach can keep issues, and commit histories.

So we have no plan to separate two different repositories.

**Comment by ndevenish** [comment]
Is the intention that releases are going to be phased roughly in sync or are they on completely separate roadmaps now? e.g. should we be for all intents and purposes treating them as completely separate for downstream versioning?

**Comment by redboltz** [comment]
C and C++ version has been separated. I just released C++ version. The version number of C and C++ are completely unrelated.
The release version is not synced with C version.

```
... 3.0.0 (C/C++) --+--- 4.0.0 (C++) --- ...
                    |      A
                    |      | Unrelated
                    |      |
                    |      V
                    +--- 4.0.0 (C) --- ...

```
