### ISSUE TITLE
cannot find -lmsgpackc

### ISSUE THREAD

**Issue by HuyDuongA** [msgpack/msgpack-c#934]
I ran into this error when use #include <msgpack.h> in my source code.

```
/usr/bin/ld: cannot find -lmsgpackc
collect2: error: ld returned 1 exit status
```

Did anybody else run to the same problem?

**Comment by redboltz** [comment]
If msgpack-c is installed libmsgpack.c libmsgpackc.so should be installed to library directory.

You can check

```sh
sudo find /usr -name "libmsgpackc*"
```

You can also build the library from the source code. See https://github.com/msgpack/msgpack-c/tree/c_master#building-and-installing

**Comment by HuyDuongA** [comment]
`sudo find /usr -name "libmsgpackc*"`

doesn't give me any output. I will try to build the library from the source code. One question though, does that mean if I install msgpack on a new device, I have to build every time before using the library?

**Comment by HuyDuongA** [comment]
The error goes away after following the build instruction from the source code.
