### ISSUE TITLE
Pack boost::unordered_map with msgpack

### ISSUE THREAD

**Issue by jatakiajanvi12** [msgpack/msgpack-c#936]
Is there any adaptor that packs the boost::unordered_map structure using MSGPACK_DEFINE?

I get the following error when I define MSGPACK_USE_BOOST and then use it to pack my custom class that has boost::unordered_map as one of the elements: 

instantiated from 'void msgpack::v1::type::define_array<A0, A1, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void, void>::msgpack_unpack(const msgpack::v2::object&) [with A0 = long int, A1 = boost::unordered::unordered_map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >]'
     [exec] /**h:16:   instantiated from here
     [exec] ../msgpack/include/msgpack/v1/object.hpp:642: error: 'class boost::unordered::unordered_map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::hash<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >' has no member named 'msgpack_unpack'

**Comment by redboltz** [comment]
Currently msgpack-c supports the following boost adaptors:
https://github.com/msgpack/msgpack-c/tree/cpp_master/include/msgpack/adaptor/boost

boost::unordered_map is not supported, so far. You can use `std::unordered_map` instead.

You can write the adaptor by yourself. See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_adaptor#non-intrusive-approach

You can use almost the same implementation as
https://github.com/msgpack/msgpack-c/blob/cpp_master/include/msgpack/v1/adaptor/cpp11/unordered_map.hpp
