### ISSUE TITLE
Does the msgpack pack throw any exceptions?

### ISSUE THREAD

**Issue by jatakiajanvi12** [msgpack/msgpack-c#937]
I was writing a non intrusive class with a lot of data. I wanted to know if msgpack pack API throw any exceptions that needs to be handled?

**Comment by redboltz** [comment]
## Unpack
These exceptions might be thrown during unpacking process.
https://github.com/msgpack/msgpack-c/blob/cpp_master/include/msgpack/v1/unpack_exception.hpp
In addition `std::bad_alloc` is thrown if memory allocation is failed.

## Pack
In addition `std::bad_alloc` is thrown if memory allocation is failed.

If you use fbuffer then `std::runtime_error` might be thrown.
See https://github.com/msgpack/msgpack-c/blob/cpp_master/include/msgpack/v1/fbuffer.hpp#L36

## Convert (As)
If you try converting msgpack::object to the type that doesn't have valid adaptor, then  `msgpack::type_error`  is thrown.
See https://github.com/msgpack/msgpack-c/blob/cpp_master/include/msgpack/v1/object_fwd.hpp#L231
If the converting target type fails memory allocation then `std::bad_alloc` is thrown.
