### ISSUE TITLE
C: empty strings break msgpack_object_print_buffer

### ISSUE THREAD

**Issue by vmallet** [msgpack/msgpack-c#941]
Printing an object to a buffer breaks if the object contains an empty string when using msgpack_object_print_buffer().

For example:
A simple object with just an empty string serializes as:
`"`
instead of:
`""`

An array with an empty string somewhere doesn't get fully serialized. For example,
`[1, 2, "", 3]`
becomes:
`[1, 2, "`

Same thing with a map:
`{"key"=>"", "key2"=>"value2"}`
becomes:
`{"key"=>"`

I have a PR ready to be submitted to resolve the issue.

**Comment by vmallet** [comment]
(continuing text, command-enter submitted the issue too early)

For example:
A simple object with just an empty string serializes as:
"
instead of:
""

An array with an empty string somewhere doesn't get fully serialized. For example,
[1, 2, "", 3] 
becomes:
[1, 2, "

Same thing with a map:
{"key"=>"", "key2"=>"value2"}
becomes:
{"key"=>"

I have a PR ready to be submitted for to resolve the issue.

**Comment by redboltz** [comment]
PR merged.
