### ISSUE TITLE
C: Improve tests visibility

### ISSUE THREAD

**Issue by vmallet** [msgpack/msgpack-c#943]
By default, if one doesn't have gtest installed it is not obvious how to build and run tests on the c_master branch. Once the tests run, it is not obvious to see which particular unit test fails.

Suggestions: 
- improve the README slightly to mention gtest and how to run the tests
- turn on the "output on failure" mode by default. When all goes well no output changes, but when a unit test fails it becomes a lot easier to pinpoint what went wrong.

PR coming in case the suggestions make sense.

**Comment by redboltz** [comment]
PR merged.
