### ISSUE TITLE
Deserialization of std::string and std::wstring silently fails.

### ISSUE THREAD

**Issue by NostalgiaRunner** [msgpack/msgpack-c#945]
Hello, I have a quick issue that I've been stuck on all day and I'm wondering what I'm doing wrong.
I've got code that pipes an int and a wstring to an external program, and now I have a named pipe that is reading back from that program searching for an int and a wstring.

```cpp
std::vector<char> buffer(65536);
DWORD dwRead;
std::cout << ReadFile(hPipe, &buffer[0], buffer.size(), &dwRead, NULL) << std::endl;
std::string str(buffer.begin(), buffer.begin() + dwRead);
msgpack::object_handle oh = msgpack::unpack(str.data(), str.size());
msgpack::object deserialized = oh.get();
msgpack::type::tuple<int, std::wstring> dst;
std::cout << deserialized << std::endl;
deserialized.convert(dst);
std::wstring b = std::get<1>(dst);
std::wcout << b << std::endl;
```
For some reason, if I adjust the tuples and send just an int down the named pipe to the code, it reads and prints fine. But as soon as I send an int and a wstring or just a wstring, it crashes with no error. If on Python, I pack [20, [67,114,97,98]], which is serialized into `b'\x92\x14\x94\Crab'`. The cpp code reads this and is able to output [20, [67,114,97,98]] right before converting to a tuple. However when I convert everything back into an int and a wstring after external processing, it just crashes.

Am I doing something wrong? Please help, thank you.

**Comment by redboltz** [comment]
A simple example of `std::wstring` works well for me:
See https://wandbox.org/permlink/2fajWWdWkNmWPeG0

I need the **minimal and complete** code that reproduces the issue.

**Comment by NostalgiaRunner** [comment]
The issue does not seem to be the library anymore. I'm getting anonymous behavior, but I will reopen this if the issue seems to be with msgpack for certain.
