### ISSUE TITLE
pack/unpack class pointers

### ISSUE THREAD

**Issue by cmastelaro** [msgpack/msgpack-c#950]
i'm having some troubles trying to use mspack with an array of pointers
seems that was not recognized by msgpack
did i have to rewrite some adaptors to make this work ?

I have attached sort of just a simple code to explain what i'm trying to say.

```
class my_class
{
private:
    int a;

public:
    my_class()
    {
    }

    MSGPACK_DEFINE(a)
};

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    std::stringstream ss;

    // THIS CODE GIVES ME AN ERROR error C2228: must have a class/struct/union
    std::vector<my_class*> pointers;
    msgpack::pack(ss, pointers);

   // BUT THIS VERSION INSTEAD WORKS FINE !!!
    std::vector<my_class> not_pointers;
    msgpack::pack(ss, not_pointers);

    return a.exec();
}
```

How to proceed in this case ? it's mandatory create an adaptor for any class pointer in the project to make de pack works ?
in this case how to write the adaptor ?!?! i couldn't found any example going on that way.

Please i apreciate any help.

**Comment by Fastug** [comment]
class my_class
{
private:
    int a;

public:
    my_class()
    {
    }

    MSGPACK_DEFINE(a)
};

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    std::stringstream ss;

    // THIS CODE GIVES ME AN ERROR error C2228: must have a class/struct/union
    std::vector<my_class*> pointers;
    msgpack::pack(ss, pointers);

   // BUT THIS VERSION INSTEAD WORKS FINE !!!
    std::vector<my_class> not_pointers;
    msgpack::pack(ss, not_pointers);

    return a.exec();

**Comment by redboltz** [comment]
If you have further questions about this topic, feel free to reopen the issue.
