### ISSUE TITLE
UB in master

### ISSUE THREAD

**Issue by redboltz** [msgpack/msgpack-c#956]
https://github.com/msgpack/msgpack-c/tree/cpp_master
CI badge failing.

It is caused by https://github.com/msgpack/msgpack-c/actions/runs/828066991
I mean the merged PR isn't wrong. Some of UB is not fixed. And one of them is related to rawref.

https://github.com/msgpack/msgpack-c/runs/2545636092?check_suite_focus=true

@kovdan01 could you check this?

**Comment by kovdan01** [comment]
Yes, I'll do that

**Comment by redboltz** [comment]
Fixed by #957.
