### ISSUE TITLE
Data in sbuffer is not valid

### ISSUE THREAD

**Issue by MrSherish** [msgpack/msgpack-c#958]
Hey,

I need at some point during execution to convert msgpack::object (which represents a map) back to msgpack format and pass it to code that utilizes different library. The problem is the data pulled from msgpack::sbuffer contains `ffffff` between separators and data.

https://wandbox.org/permlink/QcyQIs9na00PCu1S

In the exmple above, I'm just packing a map into buffer which straight away gives same problem.

Maybe reading from msgpack::sbuffer::data is not the right thing? How can one pack data back into char*?

**Comment by redboltz** [comment]
I don't understand what you mean.

> In the exmple above, I'm just packing a map into buffer which straight away gives same problem.

There is no map in the example.

Could you elaborate the question ?

**Comment by MrSherish** [comment]
Sorry, I've posted wrong link accidentaly. Editied original issue with this one: https://wandbox.org/permlink/QcyQIs9na00PCu1S

**Comment by MrSherish** [comment]
Sorry, everything seems right - the `ffffff` were due to int casting
