### ISSUE TITLE
convert throw exception(std::bad_cast msgpack::v1::type_error), after iostream operation

### ISSUE THREAD

**Issue by Zacks7788** [msgpack/msgpack-c#959]
```
        std::tuple<int32_t, int32_t> tp1({1, 2});
        std::ostringstream ss;
        msgpack::pack(ss, tp1);
        std::string s(ss.str());

        msgpack::object obj;
        std::tuple<int32_t, int32_t> tp2;

        obj = msgpack::unpack(s.c_str(), s.length()).get();
        std::cout  << "convert begin" << std::endl;
        obj.convert(tp2);  
```
when I put the output invoke of std::out   between "inovke unpack" and "invoke convert", 
this code will crashed with _" terminate called after throwing an instance of 'msgpack::v1::type_error' what():  std::bad_cast"_
but when I put the output function invoke before unpack,  everything is ok. 
when I replace the std::tuple with a customer struct use "MSGPACK_DEFINE",  it has the same problem.

the following code is safe 

```
      std::tuple<int32_t, int32_t> tp1({1, 2});
        std::ostringstream ss;
        msgpack::pack(ss, tp1);
        std::string s(ss.str());

        msgpack::object obj;
        std::tuple<int32_t, int32_t> tp2;

        std::cout  << "convert begin" << std::endl;
        obj = msgpack::unpack(s.c_str(), s.length()).get();
        obj.convert(tp2);  
```

why does thie happen?   the convert function should be nothing with std stream operation,  I think.

**Comment by redboltz** [comment]
See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_object#what-is-msgpackobject
In your case obj has dangling reference.
Use object_handler as a variable instead of object.

**Comment by redboltz** [comment]
See also https://github.com/msgpack/msgpack-c/blob/cpp_master/example/cpp03/simple.cpp#L30

**Comment by Zacks7788** [comment]
> See https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_object#what-is-msgpackobject
> In your case obj has dangling reference.
> Use object_handler as a variable instead of object.

it's ok now, thanks
