### ISSUE TITLE
Plans about future releases

### ISSUE THREAD

**Issue by kovdan01** [msgpack/msgpack-c#964]
@redboltz It seems that cpp_master contains a bunch of fixes that were submitted after the latest 3.3.0 release. Do you have plans to tag a new release (for example 3.3.1)? Many people prefer to use release versions instead of using cpp_master, it might be cool to make those updates available for them.

**Comment by redboltz** [comment]
Yes, I will release the next c++ version soon.

**Comment by redboltz** [comment]
It will be version 4.0.0.
We have the following versioning policy.

Major.Minor.Patch

- Major
  - If the release contains breaking changes. 
- Minor
  - If the release contains additional functionalities.
- Patch
  - Other (bug fix, etc)

The next (msgpack-c C++) release is the first release that msgpack-c separated C part and C++ part.
In addition, the C++ part of msgpack-c depends on Boost Libraries.

**Comment by redboltz** [comment]
4.0.0 has been released.
https://github.com/msgpack/msgpack-c/releases/tag/cpp-4.0.0

**Comment by kovdan01** [comment]
@redboltz thanks a lot! One more thing: didn't you forget to include `msgpack-config.cmake.in` file to release archive? Otherwise it's impossible to build the library with cmake (see the output below).

```
> cmake -S . -B build -D CMAKE_INSTALL_PREFIX=`pwd`/prefix -D MSGPACK_BUILD_TESTS=ON -D MSGPACK_CXX20=ON 
-- The CXX compiler identification is GNU 11.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/lib64/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0")  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found Boost: /usr/lib64/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0") found components: unit_test_framework system 
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.1") found components: doxygen dot 
CMake Error: File /home/kovdan01/lib/msgpack-cxx-4.0.0/msgpack-config.cmake.in does not exist.
CMake Error at /usr/share/cmake-3.21/Modules/CMakePackageConfigHelpers.cmake:342 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:193 (CONFIGURE_PACKAGE_CONFIG_FILE)


-- Configuring incomplete, errors occurred!
See also "/home/kovdan01/lib/msgpack-cxx-4.0.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/kovdan01/lib/msgpack-cxx-4.0.0/build/CMakeFiles/CMakeError.log".
```

Also it might be useful to include cmake directory to the release archive since `MSGPACK_GEN_COVERAGE` option is available in CMakeLists.txt but cannot be used without `cmake/CodeCoverage.cmake` file.

```
> cmake -S . -B build-coverage -D CMAKE_INSTALL_PREFIX=`pwd`/prefix-coverage -D MSGPACK_BUILD_TESTS=ON -D MSGPACK_CXX20=ON -D MSGPACK_GEN_COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug
-- The CXX compiler identification is GNU 11.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/lib64/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0")  
CMake Error at CMakeLists.txt:116 (INCLUDE):
  INCLUDE could not find requested file:

    CodeCoverage


CMake Error at CMakeLists.txt:119 (SETUP_TARGET_FOR_COVERAGE):
  Unknown CMake command "SETUP_TARGET_FOR_COVERAGE".


-- Configuring incomplete, errors occurred!
See also "/home/kovdan01/lib/msgpack-cxx-4.0.0/build-coverage/CMakeFiles/CMakeOutput.log".
```

**Comment by redboltz** [comment]
Thank you for reporting.
The PR for fixed release is #967 
Could you check this?

**Comment by redboltz** [comment]
I will create preview release 4.0.1 soon. After you checking the preview release, I will update the release to the official.

**Comment by redboltz** [comment]
https://github.com/msgpack/msgpack-c/releases/tag/cpp-4.0.1
Pre-release is published. Please check this.

**Comment by kovdan01** [comment]
> https://github.com/msgpack/msgpack-c/releases/tag/cpp-4.0.1
Pre-release is published. Please check this.

Checked, it is OK now, thanks!

**Comment by redboltz** [comment]
Removed `pre-` checkbox. It is official release now.
