### ISSUE TITLE
C and C++ libraries install headers of the same name

### ISSUE THREAD

**Issue by carlocab** [msgpack/msgpack-c#974]
Based on #928, the C and C++ libraries are meant to be treated as separate packages, given that they are versioned completely independently of each other.

However, both libraries (i.e. the older mixed C/C++ one and the newer C++ only one) install many header files that are named the same, which makes having separate installations of both libraries rather complicated.

Is it possible for you to rename the headers of one library so that they don't conflict with the other? Or, if the conflict is meant to be resolved with the C-only library release, could that release be cut soon, please?

Thanks very much.

**Comment by redboltz** [comment]
> Is it possible for you to rename the headers of one library so that they don't conflict with the other? Or, if the conflict is meant to be resolved with the C-only library release, could that release be cut soon, please?

Yes C-only library release would solve the issue. I will do that ASAP.

Here are separated installed image. 
Let's say the target directory is `/usr/local`

----

```
For C++ (4.0.2)
usr/local/include/*.hpp for C++ (including subdirectories)
          lib/cmake/msgpackc-cxx/*.cmake
```

It is good. Contained headers is *.hpp only.
Cmake files are located on msgpackc-cxx.
NOTE: C++ version is designed as a header-only library

---


```
For C (current c_master)
usr/local/include/*.h for C (including subdirectories)
          lib/cmake/msgpack/*.cmake
              libmsgpackc.a
              libmsgpackc.so
              libmsgpackc.so.2
              libmsgpackc.so.2.0.0
              pkgconfig/msgpack.pc
```

For headers, no problem. Contains *.h only.
In the cmake directory, `msgpack` sub directory is used for C.
It seems that it should be something like `msgpackc-c`.
Then if both C and C++ installed, the cmake directory become as follows:

```
usr/local/lib/cmake/msgpackc-c
                    msgpackc-cxx
```

How about pkgconfig ? I'm not sure how pkgconfig works.
The file originally exists and I didn't touch it so far.

----

Now, I just started preparing C version release.


```
For C (current c_master)
usr/local/include/*.h for C (including subdirectories)
          lib/cmake/msgpackc-c/*.cmake   (renamed to msgpackc-c from msgpack)
              libmsgpackc.a
              libmsgpackc.so
              libmsgpackc.so.2
              libmsgpackc.so.2.0.0
              pkgconfig/msgpackc.pc  (renamed to msgpackc.pc from msgpack.pc)
```

@carlocab, @ygj6 what do you think ?

----

**Comment by redboltz** [comment]
For C, I think that the library name shouldn't be updated. The last mixed version of msgpack-c (3.3.0) has the same library file (libmsgpackc.*) and it contains only C part. (C++ doesn't have library file).
The existing C version users can continue to use without library name updates.

I guess that updating `lib/cmake/msgpack` to `lib/cmake/msgpackc-c` impact is very small.

I just glanced pkgconfig document. It seems that `libxxx.*` is corresponding to `pkgconfig/xxx.pc`. 
So it should be updated from `msgpack.pc` to `msgpackc.pc`. 
But I suspect that this file is really needed. Because there is no problem the name is mismatched.

**Comment by carlocab** [comment]
I suggest keeping the original name of `msgpack.pc`. Renaming it is going to break a lot of build scripts that rely on using `pkg-config` to find `msgpack.pc`, because they won't expect it to be renamed to `msgpackc.pc`. Alternatively, you might consider creating a symlink `msgpack.pc` that points to `msgpackc.pc`.

I'm inclined to say the same about `lib/cmake/msgpack`, as renaming it will also break users who use `find_package(Msgpack)`, but I feel less strongly about this since it seems like your existing CMake scripts are for both your C and C++ libraries (whereas the `.pc` file was only for the C library).

**Comment by redboltz** [comment]
@carlocab thank you for the comment.

There is no actual conflict in the current c_master vs cpp_master. I just came up with name correspondence idea.
But now I understand user's situation.

So I keep the following C setting and continue release process.

```
For C (current c_master)
usr/local/include/*.h for C (including subdirectories)
          lib/cmake/msgpack/*.cmake
              libmsgpackc.a
              libmsgpackc.so
              libmsgpackc.so.2
              libmsgpackc.so.2.0.0
              pkgconfig/msgpack.pc
```

**Comment by carlocab** [comment]
That sounds perfect. Thank you very much.

**Comment by redboltz** [comment]
I just pre-released https://github.com/msgpack/msgpack-c/releases/tag/c-4.0.0

@carlocab , could you check this including tarball ?

**Comment by carlocab** [comment]
Thanks; I've opened Homebrew/homebrew-core#84363 to test this on Homebrew CI, which includes testing this against a few dependent packages.

**Comment by carlocab** [comment]
Some changes in Homebrew CI prevented dependent testing, but I've tested this locally on my machine and it seems to be fine. Thanks for this!

**Comment by redboltz** [comment]
Thank you for checking. 4.0.0 C has been released. (Not pre-release)

**Comment by carlocab** [comment]
Great. Testing with the release on Homebrew CI (which now succeeded) revealed no problems with packaged users of msgpack.

Thank you for your work on this very nice library.
