### ISSUE TITLE
Resetting an unpacker

### ISSUE THREAD

**Issue by rohit-px2** [msgpack/msgpack-c#975]
Hi. My code looks like this:
```cpp
// Setup
...
msgpack::unpacker unpacker;
unpacker.reserve_buffer(buffer_maxsize);
while(true) {
 int msg_size = output.read(unpacker.buffer(), buffer_maxsize);
 unpacker.buffer_consumed(msg_size);
 msgpack::object_handle oh;
 while(unpacker.next(oh)) {
   // Handle message
   ...
 }
}
```
However the unpacker's `buffer_capacity()` gets reduced over each iteration, eventually using up all the space,
I want to reset the state of `unpacker` on each iteration of the loop while keeping the same buffer (avoiding `realloc`-ing multiple times). Is there any way to do this?

**Comment by redboltz** [comment]
`unpacker` is for streaming. The library assume that the message size is unpredictable. So realloc is used.
But in your code, you are using `buffer_maxsize`. It seems that the maximum message size is predictable. It that right ?
And you want to reuse the buffer (size `buffer_maxsize`). It that right?

**Comment by rohit-px2** [comment]
Yes that's right,

**Comment by redboltz** [comment]
In your case, non-streaming interface is appropriate.

How about this?
https://wandbox.org/permlink/hFnIUEvUQhI5VSvN

**Comment by rohit-px2** [comment]
That was my original approach but I was getting the exception `msgpack::v1::insufficient_bytes`, which is why I moved to `msgpack::unpacker`.

**Comment by redboltz** [comment]
unpacker's buffer management as follows:
https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_unpacker
https://www.slideshare.net/taka111/msgpackc

So, you can't reuse the specific part of internal buffer.
It is a different approach from you want to do , but if you want to minimize copy operation, you can use `unpack_reference_func`.

**Comment by rohit-px2** [comment]
Okay, I'll look into that. Thanks for the help!

**Comment by redboltz** [comment]
You can avoid msgpack::v1::insufficient_bytes as follows: (Incomplete code)
https://wandbox.org/permlink/8Uwrer4WYaPb2Jcw
But shift (copy) operation is required.
