### ISSUE TITLE
Packer => class PackStream : std::ostream?

### ISSUE THREAD

**Issue by splinterofchaos** [msgpack/msgpack-c#98]
It occurred to me that `sbuffer` functions very similarly to [`std::streambuf`](http://en.cppreference.com/w/cpp/io/basic_streambuf) and the only feature missing from Packer is the `<<` operator. Also, `fbuffer` is similar to a C version of [`std::filebuf`](http://en.cppreference.com/w/cpp/io/basic_filebuf). The equivalent of `sbuffer::write()` is [`std::streambuf::sputn`](http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn). `std::ostream` also allows the specification of an external buffer to write to. (http://en.cppreference.com/w/cpp/io/basic_ostream/basic_ostream)

As things are, I found that I could replace every instance of `sbuffer` with `std::ostringstream`, which defines the [`write()`](http://en.cppreference.com/w/cpp/io/basic_ostream/write) method. Technically (although this isn't what I'm proposing), `sbuffer` and `fbuffer` could be entirely removed by using `std::ostringstream` and `std::ofstream`, respectively. However, I don't fully understand `zbuffer`, but I imagine it could be implemented as a child class of `std::streambuf`.

To be honest, I haven't done enough research to determine how the best way to integrate this into msgpack would be or if it's even a good idea, I don't know how much code would need to be written, and it's not as if the currently implemented system needs any fixing. But I thought I'd at least put it out there.

I should actually have some time this week to investigate, but as noted before, I can't run the unit tests because of the zlib dependency.

**Comment by redboltz** [comment]
I close the issue because no further comments after my comment.
Feel free to re-open if you have more questions.
