### ISSUE TITLE
C: msgpack_zone configuration.

### ISSUE THREAD

**Issue by gottfriedleibniz** [msgpack/msgpack-c#985]
Referring to: https://github.com/msgpack/msgpack-c/blob/c_master/src/unpack.c#L193-L200. As noted in that comment: "might not be constrained to 4GB on 64-bit systems". Consider the following, and nefariously crafted, input: 

`0xDD 0xFF 0xFF 0xFF 0xFF`  or `0xDF ...`

On x64 builds this will attempt to [malloc](https://github.com/msgpack/msgpack-c/blob/c_master/src/unpack.c#L205) `0xFFFFFFFF * 24` bytes (95.99GB; before alignment). While this should fail on most end-systems, i.e., the OS says no or zero-fill on demand comes into play, it doesn't take many additional steps (or inputs) to halt some systems.

The library currently offers no way to configure (or sanitize) against these edge-cases and subsequent effects. Hardening against these edge-cases should be considered, e.g., an additional `max_zone` field that defaults to `UINT_MAX/sizeof(msgpack_object)`.

Thanks.

**Comment by redboltz** [comment]
I close the issue, if you are still interested in the issue, reopen it with comment.
