### ISSUE TITLE
MSGPack object manipulation

### ISSUE THREAD

**Issue by LendionSematik** [msgpack/msgpack-c#997]
Hello, I am writing a little programs which sends some messages, i would like to inject a interger into the depacked object.
Example:
```
template <typename T>
struct FuncTraits : FuncTraits<decltype(&T::operator())> {};

template <typename C, typename R, typename... Args>
struct FuncTraits<R(C::*)(Args...) const> : FuncTraits<R(*)(Args...)> {};

template <typename R, typename... Args> struct FuncTraits<R(*)(Args...)> {
    using ResultType = R;
    using ArgCount = std::integral_constant<std::size_t, sizeof...(Args)>;
    using ArgsType = std::tuple<typename std::decay<Args>::type...>;
};

#include <msgpack.hpp>

template<typename Func> void depack(Func func, std::shared_ptr<msgpack::sbuffer> object)
{
    msgpack::object_handle unpacked = msgpack::unpack(object.data(), object.size());
    msgpack::object_handle args(unpacked.as<msgpack::object>, std::move(unpacked.zone())).get();
    int toBeInjected = 1000;
//HOW DO I INJECT THE INT SO IT MATCHES THE ARGS TYPE
    func(args.as<FuncTraits<Func>::ArgsType>);
}
void main()
{
    std::shared_ptr<msgpack::sbuffer> buffer = std::make_shared<msgpack::sbuffer>();
    msgpack::pack(*buffer, std::make_tuple(function, std::make_tuple(100, "hfhfh")));
    depack([](int injected, int arg1, std::string arg2){}, buffer);
}
```
Now the real issue here is that i cant just add the int as another arg due to the problem of casting to the args type.
How do i inject the int as the first item in the msgpack array object?

**Comment by redboltz** [comment]
Basically, msgpack::object is not designed to modify.
You can use `msgpack::type::variant`. 
See https://github.com/msgpack/msgpack-c/tree/cpp_master/example/boost
msgpack_variant_*.cpp examples might help you.

**Comment by LendionSematik** [comment]
Hi sadly i cannot figure out how i can do this without making a really advanced and slow visitor.
Due to it being a quite complex data structure. I only need to insert this one integer though.
Is it safe to just modify the array so that i change the size and add a integer.
Or is there a way to do this with some c++20 magic?

**Comment by redboltz** [comment]
Let me clarify what you want to do.

Do you just want to do as follows ?

https://wandbox.org/permlink/rwBOmEoxAJ3TWVIz

```cpp
#include <iostream>
#include <msgpack.hpp>

int main() {
    std::vector<int> v1 {1, 2, 3};
    msgpack::sbuffer buf;
    msgpack::pack(buf, v1);
    
    auto oh = msgpack::unpack(buf.data(), buf.size());
    std::cout << *oh << std::endl;
    // [1,2,3]

    // do some operation then got 9 is pushed front
    // [9,1,2,3] 
}
```
