### ISSUE TITLE
Floats or doubles that are whole numbers always pack incorrectly

### ISSUE THREAD

**Issue by anselanza** [msgpack/msgpack-c#998]
It may be something specific to my environment, but if I try to include a `double` or `float` value that happens to be a whole number, then my message is packed incorrectly (my decoder complains `RangeError: Offset is outside the bounds of the DataView`).

Consider the following custom data structure:
```
struct dummyData {
	std::string name;
	int distance;
  double probabilityOfImpact;
	MSGPACK_DEFINE_MAP(name, distance, probabilityOfImpact);
};
```
When initialising the struct like this...
```
dummyData d {
    "comet", 101, 98.1
  };
```
... Absolutely no problem.

But change the value to something that happens to be a whole number, e.g. (it doesn't matter whether you write `98`, `98.0`, `98.` `(double)(98)` or anything else)
```
dummyData d {
    "comet", 101, 98.0
  };
```

And boom, it's broken:
```
Could not decode message: {
  topic: 'dummy/dummy01/testout',
  message: <Buffer 83 a4 6e 61 6d 65 a5 63 6f 6d 65 74 a8 64 69 73 74 61 6e 63 65 65 b3 70 72 6f 62 61 62 69 6c 69 74 79 4f 66 49 6d 70 61 63 74 cb 40 58 80>,
  error: RangeError: Offset is outside the bounds of the DataView
      at DataView.getFloat64 (<anonymous>)
at Decoder.readF64 (/Users/stephen/repos/tether/tether/utilities/cli/node_modules/@msgpack/msgpack/dist/Decoder.js:577:33)
```

I am using CMake and compiling using Clang, details below:
```
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
```

To be clear, the issue is NOT just with float literals. I noticed the problem when trying to convert values from another API, which were returned as `float` and encountered the same problem. It seems that any time I happen to hit a value that happens to be a full number, it fails to be interpreted as a floating-point value.

**Comment by redboltz** [comment]
Does your decoder implemented using C++ ? Or perhaps JavaScript?

**Comment by redboltz** [comment]
I found `node_modules/@msgpack/msgpack/dist/Decoder.js:577:33`. It is JS.
On C++, the type of probabilityOfImpact is double. 
It is mapped into https://github.com/msgpack/msgpack/blob/master/spec.md#float-format-family

On JS, only Numer type exists. It is difficult point to implement msgpack library using JS.
Ii depends on JS msgpack library.
Some of library mapped 98 to int format family, 98.1 to float format family.
I guess that these kinds of behavior cause the issue.

**Comment by anselanza** [comment]
I tried a different JS decoder and encountered the same behaviour.

I am aware of the type issues with JS, but I don't think this is the problem here. The decoder always interprets the type of the number correctly (F64, F32, etc.) even when the number is a whole number.

**Comment by redboltz** [comment]
You can check the MessagePack format using https://wandbox.org/permlink/CXliiWHfsKXttndn
If it is expected result, msgpack-c has no problem. The problem is decoder side.

**Comment by anselanza** [comment]
Your example did not quite work the same way as mine. For a start, you were packing only the double value, not the whole struct. So I tried the following:
```
int main() {
    dummyData d { "comet", 101, 98.0 };
    // double d = 98.0;
    msgpack::sbuffer b;
    msgpack::pack(b, d);
    hex_dump(std::cout, b) << std::endl;
}
```
The output bytes were as follows:
```
0x83 0xa4 0x6e 0x61 0x6d 0x65 0xa5 0x63 0x6f 0x6d 0x65 0x74 0xa8 0x64 0x69 0x73 0x74 0x61 0x6e 0x63 0x65 0x65 0xb3 0x70 0x72 0x6f 0x62 0x61 0x62 0x69 0x6c 0x69 0x74 0x79 0x4f 0x66 0x49 0x6d 0x70 0x61 0x63 0x74 0xcb 0x40 0x58 0x80 0x00 0x00 0x00 0x00 0x00
```
Compare that what I am receiving on the decoder end:
```
<Buffer 83 a4 6e 61 6d 65 a5 63 6f 6d 65 74 a8 64 69 73 74 61 6e 63 65 65 b3 70 72 6f 62 61 62 69 6c 69 74 79 4f 66 49 6d 70 61 63 74 cb 40 58 80>
```
Identical, except that I appear to be missing 5x `0x00` bytes at the end.

Could my buffer be getting truncated somewhere?

**Comment by anselanza** [comment]
Actually, this is good. I wonder if the problem isn't how I am passing the packed buffer to my message-sending part:
```
// Make a buffer, pack data using messagepack...
  std::stringstream buffer;
  msgpack::pack(buffer, d);
  const std::string& tmp = buffer.str();   
  const char* payload = tmp.c_str();

  outputPlug->publish(payload);
```
Perhaps my conversion to a `const char*` via `c_str()` is truncating the trailing "zero" bytes!

**Comment by redboltz** [comment]
> Perhaps my conversion to a const char* via c_str() is truncating the trailing "zero" bytes!

I guess so. If you set `distance` as 0, 0x00 appears earlier. https://wandbox.org/permlink/DcfGXH09wz2m7Wf5

**Comment by anselanza** [comment]
Thank you for your help! 

I found that all I needed to do was convert the buffer properly using `buffer.str()`!

This apparently keeps the trailing zeros (does not truncate) and the JS msgpack decoder was able to read the number value correctly,
